"use client";
import { useState } from "react";
import { recordListingEngagementAction } from "@/lib/actions/engagement";
import { getListingContactPhoneAction } from "@/lib/actions/inventory";
import { createShareOutputAction } from "@/lib/actions/liquidity";
import type { AppLocale } from "@/lib/i18n/translations";

const COPY={en:{calling:"Connecting…",call:"Call",whatsapp:"WhatsApp",share:"Share",copied:"Link copied",message:"Hello, I found your listing on Sahibash. Is it still available?",blocked:"Contact not available",external:"Confirm availability before sending money."},fa:{calling:"در حال اتصال…",call:"تماس",whatsapp:"واتساپ",share:"اشتراک",copied:"پیوند کاپی شد",message:"سلام، اعلان شما را در صاحباش دیدم. آیا هنوز موجود است؟",blocked:"تماس در دسترس نیست",external:"پیش از پرداخت، موجودیت را تأیید کنید."},ps:{calling:"نښلېږي…",call:"زنګ",whatsapp:"واټس‌اپ",share:"شریکول",copied:"تړونی کاپي شو",message:"سلام، ستاسو اعلان مې په صاحباش کې ولید. آیا لا شته؟",blocked:"اړیکه نشته",external:"له پیسو ورکولو مخکې شتون تایید کړئ."}} as const;

export function ListingContactActions({listingId,title,locale,canContact=true,isExternal=false,hasPhone=true,whatsappEnabled=false}:{listingId:string;title:string;locale:AppLocale;canContact?:boolean;isExternal?:boolean;hasPhone?:boolean;whatsappEnabled?:boolean}){
 const [isCalling,setIsCalling]=useState(false); const [copied,setCopied]=useState(false); const [error,setError]=useState(""); const t=COPY[locale];
 const track=(event:"call"|"whatsapp"|"share")=>{ void recordListingEngagementAction(listingId,event,locale); };
 async function connect(channel:"call"|"whatsapp"){ if(isCalling) return; setError(""); setIsCalling(true); const result=await getListingContactPhoneAction(listingId,locale,channel); setIsCalling(false); if(result.ok){ const digits=result.phone.replace(/[^\d+]/g,""); if(channel === "call") window.location.href=`tel:${digits}`; else window.open(`https://wa.me/${digits.replace(/^\+/g,"")}?text=${encodeURIComponent(`${t.message} ${title}`)}`,"_blank","noopener,noreferrer"); track(channel); return; } setError(result.message || t.blocked); }
 async function share(){ try { const output=await createShareOutputAction(listingId,"generic",locale); const hasOutput=output.ok&&"shareUrl" in output&&"shareText" in output; const url=hasOutput?output.shareUrl:location.href; const text=hasOutput?output.shareText:`${title}\n${location.href}`; if(navigator.share) await navigator.share({title,text,url}); else {await navigator.clipboard.writeText(text);setCopied(true);} track("share"); } catch { /* closed share sheet */ } }
 if(!canContact||!hasPhone) return <div className="rounded-xl border border-[var(--line)] bg-[var(--surface-2)] px-4 py-3 text-sm font-semibold text-[var(--ink-2)]">{t.blocked}</div>;
 return <div className="grid grid-cols-2 gap-2 sm:flex">{isExternal?<p className="col-span-2 text-xs font-semibold text-amber-700 sm:w-full">{t.external}</p>:null}{error?<p className="col-span-2 text-xs font-semibold text-red-600 sm:w-full">{error}</p>:null}<button type="button" onClick={()=>connect("call")} disabled={isCalling} className="min-h-12 rounded-xl bg-emerald-600 px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{isCalling?t.calling:t.call}</button>{whatsappEnabled?<button type="button" onClick={()=>connect("whatsapp")} disabled={isCalling} className="min-h-12 rounded-xl bg-[#25D366] px-4 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-60">{t.whatsapp}</button>:null}<button type="button" onClick={share} className="min-h-12 rounded-xl border border-[var(--line)] bg-white px-4 text-sm font-bold">{copied?t.copied:t.share}</button></div>;
}
