import type { AppLocale } from "@/lib/i18n/translations";

export const ADMIN_CONTROL_COPY = {
  en: {
    tagline: "Tagline", contactEmail: "Contact email", contactPhone: "Contact phone", defaultLocale: "Default language", heroTitle: "Homepage hero title", heroSubtitle: "Homepage hero subtitle", primaryCtaLabel: "Primary action label", primaryCtaPath: "Primary action path", secondaryCtaLabel: "Secondary action label", secondaryCtaPath: "Secondary action path", navigationLinks: "Navigation links", stepUpWindow: "Security confirmation window (minutes)", changeSummary: "Change summary", changeSummaryPlaceholder: "Describe what changed for the version history", saveSettings: "Save settings", slug: "Slug", type: "Type", title: "Title", body: "Body", ctaLabel: "Action label", ctaPath: "Action path", sortOrder: "Sort order", enabled: "Enabled", label: "Label", path: "Path", parentId: "Parent ID", updatedSettings: "Updated settings",
    administrator: "Administrator", adminDescription: "Full configuration and editing tools for site administration.", moderation: "Moderation & listings", moderationDescription: "Review pending ads, approve or reject listings, and monitor workflow state.", siteSettings: "Site settings", settingsDescription: "Manage branding, navigation, homepage content, and the administrator security window.", categoriesSchemas: "Categories & schemas", categoriesDescription: "Create categories, manage aliases, and define schema profiles for posting flows.", schemaBuilder: "Listing Schema Builder", schemaDescription: "Configure multilingual posting fields, filters, cards, and detail sections for every leaf subcategory.", staticPages: "Static pages", pagesDescription: "Create and publish CMS content for policy, help, and informational routes.", users: "Users", usersDescription: "Inspect accounts and coordinate user administration.", rolesPermissions: "Roles & permissions", rolesDescription: "Adjust role-based access and keep administrator capabilities aligned with policy.", auditLog: "Audit log", auditDescription: "Review privileged changes and track the latest administrator activity.", searchAdministration: "Search administration", searchDescription: "Tune search behavior, aliases, and zero-result handling.", administratorAccess: "Administrator access", analytics: "Liquidity analytics", electronics: "Electronics catalog", categories: "Categories", pages: "Pages", roles: "Roles",
    editSettings: "Edit the core public-facing details for the marketplace.", homepageSections: "Homepage sections", homepageSectionsDescription: "Create reusable homepage blocks and publish them instantly.", saveSection: "Save section", delete: "Delete", navigationBuilder: "Navigation builder", navigationDescription: "Manage the public navigation links shown in the header and footer.", saveLink: "Save link", versionHistory: "Version history", versionDescription: "Restore any previous settings snapshot. A restore creates a new version.", version: "Version", summary: "Summary", siteName: "Site name", locale: "Locale", savedAt: "Saved at", noVersions: "No version history yet.", restore: "Restore",
  },
  fa: {
    tagline: "شعار", contactEmail: "ایمیل تماس", contactPhone: "شماره تماس", defaultLocale: "زبان پیش‌فرض", heroTitle: "عنوان اصلی صفحه نخست", heroSubtitle: "زیرعنوان صفحه نخست", primaryCtaLabel: "برچسب اقدام اصلی", primaryCtaPath: "مسیر اقدام اصلی", secondaryCtaLabel: "برچسب اقدام دوم", secondaryCtaPath: "مسیر اقدام دوم", navigationLinks: "پیوندهای راهبری", stepUpWindow: "پنجره تأیید امنیتی (دقیقه)", changeSummary: "خلاصه تغییرات", changeSummaryPlaceholder: "تغییرات این نسخه را توضیح دهید", saveSettings: "ذخیره تنظیمات", slug: "نامک", type: "نوع", title: "عنوان", body: "متن", ctaLabel: "برچسب اقدام", ctaPath: "مسیر اقدام", sortOrder: "ترتیب نمایش", enabled: "فعال", label: "برچسب", path: "مسیر", parentId: "شناسه والد", updatedSettings: "تنظیمات به‌روزرسانی شد",
    administrator: "مدیریت کل", adminDescription: "ابزارهای کامل تنظیم و ویرایش برای مدیریت وب‌سایت.", moderation: "بررسی و مدیریت اعلان‌ها", moderationDescription: "اعلان‌های در انتظار را بررسی، تأیید یا رد کنید و روند کار را پیگیری نمایید.", siteSettings: "تنظیمات وب‌سایت", settingsDescription: "نشان تجاری، راهبری، محتوای صفحه اصلی و پنجره امنیتی مدیریت را تنظیم کنید.", categoriesSchemas: "دسته‌بندی‌ها و ساختارها", categoriesDescription: "دسته‌بندی بسازید، نام‌های جایگزین را مدیریت کنید و ساختار فورم ثبت را تعیین نمایید.", schemaBuilder: "سازنده ساختار اعلان", schemaDescription: "فیلدها، فیلترها، کارت‌ها و بخش‌های جزئیات چندزبانه هر زیرمجموعه نهایی را تنظیم کنید.", staticPages: "صفحه‌های ثابت", pagesDescription: "محتوای قوانین، راهنما و صفحه‌های معلوماتی را ایجاد و منتشر کنید.", users: "کاربران", usersDescription: "حساب‌ها را بررسی و مدیریت کاربران را هماهنگ کنید.", rolesPermissions: "نقش‌ها و دسترسی‌ها", rolesDescription: "دسترسی مبتنی بر نقش و توانایی‌های مدیران را مطابق پالیسی تنظیم کنید.", auditLog: "گزارش فعالیت مدیران", auditDescription: "تغییرات دارای صلاحیت و آخرین فعالیت‌های مدیریتی را بررسی کنید.", searchAdministration: "مدیریت جستجو", searchDescription: "رفتار جستجو، نام‌های جایگزین و جستجوهای بدون نتیجه را تنظیم کنید.", administratorAccess: "دسترسی مدیریت", analytics: "تحلیل نقدشوندگی بازار", electronics: "فهرست الکترونیک", categories: "دسته‌بندی‌ها", pages: "صفحه‌ها", roles: "نقش‌ها",
    editSettings: "مشخصات اصلی و عمومی بازار را ویرایش کنید.", homepageSections: "بخش‌های صفحه اصلی", homepageSectionsDescription: "بخش‌های قابل استفاده مجدد صفحه اصلی را بسازید و فوری منتشر کنید.", saveSection: "ذخیره بخش", delete: "حذف", navigationBuilder: "سازنده راهبری", navigationDescription: "پیوندهای عمومی سربرگ و پابرگ را مدیریت کنید.", saveLink: "ذخیره پیوند", versionHistory: "تاریخچه نسخه‌ها", versionDescription: "هر نسخه قبلی تنظیمات را بازیابی کنید. بازیابی یک نسخه جدید می‌سازد.", version: "نسخه", summary: "خلاصه", siteName: "نام وب‌سایت", locale: "زبان", savedAt: "زمان ذخیره", noVersions: "هنوز تاریخچه نسخه وجود ندارد.", restore: "بازیابی",
  },
  ps: {
    tagline: "لنډ شعار", contactEmail: "د اړیکې برېښنالیک", contactPhone: "د اړیکې شمېره", defaultLocale: "اصلي ژبه", heroTitle: "د کورپاڼې اصلي سرلیک", heroSubtitle: "د کورپاڼې فرعي سرلیک", primaryCtaLabel: "د اصلي کړنې لېبل", primaryCtaPath: "د اصلي کړنې لاره", secondaryCtaLabel: "د دوهمې کړنې لېبل", secondaryCtaPath: "د دوهمې کړنې لاره", navigationLinks: "د لارښوونې اړیکې", stepUpWindow: "د امنیتي تأیید کړکۍ (دقیقې)", changeSummary: "د بدلونونو لنډیز", changeSummaryPlaceholder: "د دې نسخې بدلونونه تشریح کړئ", saveSettings: "تنظیمات خوندي کړئ", slug: "لنډ نوم", type: "ډول", title: "سرلیک", body: "متن", ctaLabel: "د کړنې لېبل", ctaPath: "د کړنې لاره", sortOrder: "د ښودلو ترتیب", enabled: "فعال", label: "لېبل", path: "لاره", parentId: "د مور پېژند", updatedSettings: "تنظیمات تازه شول",
    administrator: "عمومي اداره", adminDescription: "د وېب‌پاڼې د ادارې لپاره بشپړ تنظیمي او سمونیز وسایل.", moderation: "د اعلانونو بیاکتنه او اداره", moderationDescription: "منتظر اعلانونه وګورئ، ومنئ یا رد یې کړئ او کاري بهیر وڅارئ.", siteSettings: "د وېب‌پاڼې تنظیمات", settingsDescription: "نښه، لارښوونه، د کورپاڼې منځپانګه او د ادارې امنیتي کړکۍ تنظیم کړئ.", categoriesSchemas: "کټګورۍ او جوړښتونه", categoriesDescription: "کټګورۍ جوړې کړئ، بدیل نومونه اداره او د اعلان فورم جوړښتونه وټاکئ.", schemaBuilder: "د اعلان جوړښت جوړوونکی", schemaDescription: "د هرې وروستۍ فرعي کټګورۍ څوژبي فیلډونه، فلټرونه، کارتونه او تفصیلي برخې تنظیم کړئ.", staticPages: "ثابتې پاڼې", pagesDescription: "د تګلارې، مرستې او معلوماتي لارو منځپانګه جوړه او خپره کړئ.", users: "کارونکي", usersDescription: "حسابونه وګورئ او د کارونکو اداره همغږې کړئ.", rolesPermissions: "رولونه او اجازې", rolesDescription: "د رول پر بنسټ لاسرسی او د مدیرانو وړتیاوې له تګلارې سره برابرې کړئ.", auditLog: "د ادارې فعالیت راپور", auditDescription: "بااختیاره بدلونونه او وروستي اداري فعالیتونه وګورئ.", searchAdministration: "د لټون اداره", searchDescription: "د لټون چلند، بدیل نومونه او بې‌پایلې لټونونه تنظیم کړئ.", administratorAccess: "اداري لاسرسی", analytics: "د بازار د راکړې ورکړې شننه", electronics: "د الکترونیک فهرست", categories: "کټګورۍ", pages: "پاڼې", roles: "رولونه",
    editSettings: "د بازار اصلي عام معلومات سم کړئ.", homepageSections: "د کورپاڼې برخې", homepageSectionsDescription: "د بیا کارونې وړ کورپاڼې برخې جوړې او سمدستي یې خپرې کړئ.", saveSection: "برخه خوندي کړئ", delete: "ړنګول", navigationBuilder: "د لارښوونې جوړوونکی", navigationDescription: "په سرلیک او پای کې عامه اړیکې اداره کړئ.", saveLink: "اړیکه خوندي کړئ", versionHistory: "د نسخو تاریخچه", versionDescription: "د تنظیماتو هره پخوانۍ نسخه بېرته راولئ. بېرته راوستل نوې نسخه جوړوي.", version: "نسخه", summary: "لنډیز", siteName: "د وېب‌پاڼې نوم", locale: "ژبه", savedAt: "د خوندي کولو وخت", noVersions: "لا تر اوسه د نسخو تاریخچه نشته.", restore: "بېرته راوستل",
  },
} as const satisfies Record<AppLocale, Record<string, string>>;
