import type { AppLocale } from "@/lib/i18n/translations";

export const DASHBOARD_COPY = {
  en: {
    noQa: "No Q&A activity yet", qaHelp: "Listing questions and responses will show up here.", incomingOffers: "Incoming Offers", noIncoming: "No incoming offers yet.", offer: "Offer", status: "Status", listing: "Listing", buyerNote: "Buyer note", accept: "Accept", reject: "Reject", outgoingOffers: "Outgoing Offers", noOutgoing: "No outgoing offers yet.", yourOffer: "Your offer", accepted: "Seller accepted your offer.", rejected: "Seller rejected your offer.", sellerResponse: "Seller response", helpPost: "How to post a listing", helpModeration: "How listing moderation works", helpReport: "How to report suspicious activity", helpContact: "How to contact support", noSavedSearches: "No saved searches yet", savedSearchHelp: "Search presets will appear here after you save a search from the listings page.", alertsEnabled: "Alerts enabled", alertsDisabled: "Alerts disabled", delete: "Delete", userId: "User ID", email: "Email", unavailable: "Not available", newMessages: "New messages", moderation: "Approval or changes requested", expiry: "Listing expiry reminders", searchMatches: "Saved-search matches", listingChanges: "Saved-listing changes", savePreferences: "Save preferences",
  },
  fa: {
    noQa: "هنوز پرسش و پاسخی وجود ندارد", qaHelp: "پرسش‌های خریداران و پاسخ‌های شما در اینجا نمایش داده می‌شوند.", incomingOffers: "پیشنهادهای دریافتی", noIncoming: "هنوز پیشنهاد دریافتی ندارید.", offer: "پیشنهاد", status: "وضعیت", listing: "اعلان", buyerNote: "یادداشت خریدار", accept: "پذیرفتن", reject: "رد کردن", outgoingOffers: "پیشنهادهای ارسالی", noOutgoing: "هنوز پیشنهادی ارسال نکرده‌اید.", yourOffer: "پیشنهاد شما", accepted: "فروشنده پیشنهاد شما را پذیرفت.", rejected: "فروشنده پیشنهاد شما را رد کرد.", sellerResponse: "پاسخ فروشنده", helpPost: "روش ثبت اعلان", helpModeration: "روش بررسی و تأیید اعلان", helpReport: "روش گزارش فعالیت مشکوک", helpContact: "روش تماس با پشتیبانی", noSavedSearches: "هنوز جستجوی ذخیره‌شده ندارید", savedSearchHelp: "پس از ذخیره جستجو در صفحه اعلان‌ها، تنظیمات آن در اینجا نمایش داده می‌شود.", alertsEnabled: "هشدارها فعال‌اند", alertsDisabled: "هشدارها غیرفعال‌اند", delete: "حذف", userId: "شناسه کاربر", email: "ایمیل", unavailable: "در دسترس نیست", newMessages: "پیام‌های جدید", moderation: "تأیید یا درخواست تغییر اعلان", expiry: "یادآوری پایان اعتبار اعلان", searchMatches: "نتایج جستجوهای ذخیره‌شده", listingChanges: "تغییرات اعلان‌های ذخیره‌شده", savePreferences: "ذخیره تنظیمات",
  },
  ps: {
    noQa: "لا تر اوسه پوښتنه او ځواب نشته", qaHelp: "د اعلان پوښتنې او ستاسو ځوابونه به دلته ښکاره شي.", incomingOffers: "ترلاسه شوي وړاندیزونه", noIncoming: "لا تر اوسه ترلاسه شوی وړاندیز نشته.", offer: "وړاندیز", status: "حالت", listing: "اعلان", buyerNote: "د پېرودونکي یادښت", accept: "منل", reject: "ردول", outgoingOffers: "لېږل شوي وړاندیزونه", noOutgoing: "لا تر اوسه مو وړاندیز نه دی لېږلی.", yourOffer: "ستاسو وړاندیز", accepted: "پلورونکي ستاسو وړاندیز ومانه.", rejected: "پلورونکي ستاسو وړاندیز رد کړ.", sellerResponse: "د پلورونکي ځواب", helpPost: "څنګه اعلان ثبت کړئ", helpModeration: "د اعلان بیاکتنه څنګه کار کوي", helpReport: "شکمن فعالیت څنګه راپور کړئ", helpContact: "له ملاتړ سره څنګه اړیکه ونیسئ", noSavedSearches: "لا تر اوسه ساتل شوی لټون نشته", savedSearchHelp: "کله چې د اعلانونو له پاڼې لټون وساتئ، تنظیمات به یې دلته ښکاره شي.", alertsEnabled: "خبرتیاوې فعالې دي", alertsDisabled: "خبرتیاوې غیرفعالې دي", delete: "ړنګول", userId: "د کارونکي پېژند", email: "برېښنالیک", unavailable: "نه شته", newMessages: "نوي پیغامونه", moderation: "تأیید یا د بدلون غوښتنه", expiry: "د اعلان د پای یادونې", searchMatches: "د ساتل شوي لټون پایلې", listingChanges: "د ساتل شوو اعلانونو بدلونونه", savePreferences: "تنظیمات خوندي کړئ",
  },
} as const satisfies Record<AppLocale, Record<string, string>>;

