import type { AppLocale } from "@/lib/i18n/translations";

export const SCHEMA_BUILDER_COPY = {
  en: {
    title: "Listing Schema Builder", description: "Configure posting, search filters, listing cards, and detail pages for every category and subcategory.", back: "Back to categories", saved: "Version published successfully.", statusUpdated: "Category availability updated successfully.", selected: "Selected", none: "None", publishedVersion: "Published version", historyRetained: "History retained", selectToBegin: "Select a category to begin.",
    findCategory: "Find a category", searchPlaceholder: "Search by name or path…", categoryOrSubcategory: "Category or subcategory", inactive: "inactive", activeCategory: "Active category", inactiveCategory: "Inactive category", loadingEditor: "Loading editor…", loadAutomatically: "Select another item to load its editor automatically.", availability: "Category availability", availabilityHelp: "Inactive categories remain editable here but are hidden from public category selection.", deactivate: "Deactivate category", activate: "Activate category", showing: "Showing", of: "of", categoryCount: "categories and subcategories.",
    publish: "Publish new version", sections: "Detail-page sections", addSection: "Add section", preview: "Live detail-page preview", previewHelp: "Only active fields with Detail enabled appear here.", fields: "Fields, filters, cards, and details", addField: "Add field", safety: "Changes are published atomically as a new version. Turning off a field does not delete values from existing listings.", editingLanguage: "Editing language", sectionKey: "Section key", sectionOrder: "Section order", visible: "Visible", remove: "Remove", yesNo: "Yes / No", exampleValue: "Example value", noVisibleFields: "No visible detail fields in this section.", key: "Key", label: "label", type: "Type", section: "Section", order: "Order", text: "Text", number: "Number", boolean: "Yes / no", select: "Select", date: "Date", active: "Active", required: "Required", posting: "Posting", filter: "Filter", card: "Card", detail: "Detail", removeField: "Remove field", options: "Options", optionsHelp: "One per line: stored value | translated label",
  },
  fa: {
    title: "سازنده ساختار اعلان", description: "فیلدهای ثبت، فیلترهای جستجو، کارت اعلان و صفحه جزئیات هر دسته و زیرمجموعه را تنظیم کنید.", back: "برگشت به دسته‌بندی‌ها", saved: "نسخه با موفقیت منتشر شد.", statusUpdated: "وضعیت دسترسی دسته‌بندی با موفقیت تغییر کرد.", selected: "انتخاب‌شده", none: "هیچ‌کدام", publishedVersion: "نسخه منتشرشده", historyRetained: "نسخه‌های نگهداری‌شده", selectToBegin: "برای آغاز یک دسته‌بندی را انتخاب کنید.",
    findCategory: "یافتن دسته‌بندی", searchPlaceholder: "جستجو بر اساس نام یا مسیر…", categoryOrSubcategory: "دسته یا زیرمجموعه", inactive: "غیرفعال", activeCategory: "دسته فعال", inactiveCategory: "دسته غیرفعال", loadingEditor: "در حال بارگذاری ویرایشگر…", loadAutomatically: "برای بارگذاری خودکار ویرایشگر، مورد دیگری را انتخاب کنید.", availability: "دسترسی دسته‌بندی", availabilityHelp: "دسته‌های غیرفعال در اینجا قابل ویرایش‌اند، اما در انتخاب عمومی نمایش داده نمی‌شوند.", deactivate: "غیرفعال کردن دسته", activate: "فعال کردن دسته", showing: "نمایش", of: "از", categoryCount: "دسته و زیرمجموعه.",
    publish: "انتشار نسخه جدید", sections: "بخش‌های صفحه جزئیات", addSection: "افزودن بخش", preview: "پیش‌نمایش زنده صفحه جزئیات", previewHelp: "فقط فیلدهای فعال که نمایش جزئیات دارند در اینجا دیده می‌شوند.", fields: "فیلدها، فیلترها، کارت‌ها و جزئیات", addField: "افزودن فیلد", safety: "تغییرات به‌صورت یک نسخه جدید و یک‌پارچه منتشر می‌شوند. غیرفعال کردن فیلد، اطلاعات اعلان‌های موجود را حذف نمی‌کند.", editingLanguage: "زبان ویرایش", sectionKey: "کلید بخش", sectionOrder: "ترتیب بخش", visible: "قابل نمایش", remove: "حذف", yesNo: "بلی / نخیر", exampleValue: "مقدار نمونه", noVisibleFields: "در این بخش فیلد قابل نمایش وجود ندارد.", key: "کلید", label: "برچسب", type: "نوع", section: "بخش", order: "ترتیب", text: "متن", number: "عدد", boolean: "بلی / نخیر", select: "انتخابی", date: "تاریخ", active: "فعال", required: "الزامی", posting: "ثبت اعلان", filter: "فیلتر", card: "کارت", detail: "جزئیات", removeField: "حذف فیلد", options: "گزینه‌ها", optionsHelp: "هر خط: مقدار ذخیره‌شده | برچسب ترجمه‌شده",
  },
  ps: {
    title: "د اعلان جوړښت جوړوونکی", description: "د هرې کټګورۍ او فرعي کټګورۍ د اعلان فورمه، لټون فلټرونه، اعلان کارت او تفصیلي پاڼه تنظیم کړئ.", back: "کټګوریو ته ستنېدل", saved: "نسخه په بریالیتوب خپره شوه.", statusUpdated: "د کټګورۍ د لاسرسي حالت په بریالیتوب بدل شو.", selected: "ټاکل شوی", none: "هیڅ", publishedVersion: "خپره شوې نسخه", historyRetained: "ساتل شوې تاریخچه", selectToBegin: "د پیل لپاره یوه کټګوري وټاکئ.",
    findCategory: "کټګوري ومومئ", searchPlaceholder: "په نوم یا لاره ولټوئ…", categoryOrSubcategory: "کټګوري یا فرعي کټګوري", inactive: "غیرفعاله", activeCategory: "فعاله کټګوري", inactiveCategory: "غیرفعاله کټګوري", loadingEditor: "سموونکی بارېږي…", loadAutomatically: "د سموونکي د اتومات بارولو لپاره بل مورد وټاکئ.", availability: "د کټګورۍ لاسرسی", availabilityHelp: "غیرفعاله کټګورۍ دلته د سمون وړ دي، خو په عامه ټاکنه کې نه ښکاري.", deactivate: "کټګوري غیرفعاله کړئ", activate: "کټګوري فعاله کړئ", showing: "ښودل کېږي", of: "له", categoryCount: "کټګورۍ او فرعي کټګورۍ.",
    publish: "نوې نسخه خپره کړئ", sections: "د تفصیلي پاڼې برخې", addSection: "برخه زیاته کړئ", preview: "د تفصیلي پاڼې ژوندۍ مخکتنه", previewHelp: "یوازې فعال فیلډونه چې د تفصیل ښودنه لري دلته ښکاري.", fields: "فیلډونه، فلټرونه، کارتونه او تفصیلات", addField: "فیلډ زیات کړئ", safety: "بدلونونه د یوې نوې نسخې په توګه یوځای خپرېږي. د فیلډ بندول د پخوانیو اعلانونو معلومات نه ړنګوي.", editingLanguage: "د سمون ژبه", sectionKey: "د برخې کلید", sectionOrder: "د برخې ترتیب", visible: "د ښودلو وړ", remove: "لرې کول", yesNo: "هو / نه", exampleValue: "بېلګه ارزښت", noVisibleFields: "په دې برخه کې د ښودلو وړ فیلډ نشته.", key: "کلید", label: "لېبل", type: "ډول", section: "برخه", order: "ترتیب", text: "متن", number: "شمېره", boolean: "هو / نه", select: "ټاکنه", date: "نېټه", active: "فعال", required: "اړین", posting: "اعلان ثبتول", filter: "فلټر", card: "کارت", detail: "تفصیل", removeField: "فیلډ لرې کړئ", options: "اختیارونه", optionsHelp: "هره کرښه: ساتل شوی ارزښت | ژباړل شوی لېبل",
  },
} as const satisfies Record<AppLocale, Record<string, string>>;

