-- Phones & Electronics complete catalog and posting system

create table if not exists public.electronics_categories (
  id bigint generated by default as identity primary key,
  name text not null,
  parent_id bigint references public.electronics_categories(id) on delete cascade,
  slug text not null unique,
  icon text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  category_node_id bigint references public.category_nodes(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.electronics_brands (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.electronics_categories(id) on delete cascade,
  name text not null,
  slug text not null,
  logo_url text,
  sort_order int not null default 0,
  is_popular boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(category_id, slug)
);

create table if not exists public.electronics_models (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.electronics_brands(id) on delete cascade,
  category_id bigint not null references public.electronics_categories(id) on delete cascade,
  name text not null,
  slug text not null,
  release_year int,
  image_url text,
  is_popular boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique(brand_id, slug)
);

create table if not exists public.electronics_model_specs (
  id bigint generated by default as identity primary key,
  model_id bigint not null references public.electronics_models(id) on delete cascade,
  spec_key text not null,
  spec_label text not null,
  spec_value text not null,
  spec_group text,
  is_public boolean not null default true,
  is_filterable boolean not null default false,
  created_at timestamptz not null default now(),
  unique(model_id, spec_key)
);

create table if not exists public.electronics_model_options (
  id bigint generated by default as identity primary key,
  model_id bigint not null references public.electronics_models(id) on delete cascade,
  option_type text not null,
  option_value text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  unique(model_id, option_type, option_value)
);

alter table public.posting_category_config
  add column if not exists electronics_category_id bigint references public.electronics_categories(id) on delete cascade,
  add column if not exists allow_manual_model boolean not null default true;

create unique index if not exists ux_posting_category_config_electronics_category_id
  on public.posting_category_config(electronics_category_id)
  where electronics_category_id is not null;

alter table public.category_fields
  alter column category_node_id drop not null;

alter table public.category_fields
  add column if not exists show_condition jsonb;

create table if not exists public.electronics_listings (
  id bigint generated by default as identity primary key,
  listing_id uuid not null unique references public.listings(id) on delete cascade,
  category_id bigint not null references public.electronics_categories(id) on delete restrict,
  brand_id bigint references public.electronics_brands(id) on delete set null,
  model_id bigint references public.electronics_models(id) on delete set null,
  manual_brand text,
  manual_model text,
  condition text,
  price numeric(14,2) not null,
  currency public.currency_code not null default 'AFN',
  storage text,
  ram text,
  color text,
  battery_health text,
  warranty text,
  box_included boolean,
  charger_included boolean,
  repair_history text,
  network_registered text,
  province text,
  district text,
  area text,
  description text,
  created_at timestamptz not null default now()
);

create index if not exists idx_electronics_categories_parent on public.electronics_categories(parent_id, sort_order);
create index if not exists idx_electronics_brands_category on public.electronics_brands(category_id, sort_order);
create index if not exists idx_electronics_models_brand on public.electronics_models(brand_id, is_popular desc, name);
create index if not exists idx_electronics_models_category on public.electronics_models(category_id, is_popular desc, name);
create index if not exists idx_electronics_model_specs_model on public.electronics_model_specs(model_id);
create index if not exists idx_electronics_model_options_model on public.electronics_model_options(model_id, option_type, sort_order);
create index if not exists idx_electronics_listings_category on public.electronics_listings(category_id);
create index if not exists idx_electronics_listings_brand on public.electronics_listings(brand_id);

alter table public.electronics_categories enable row level security;
alter table public.electronics_brands enable row level security;
alter table public.electronics_models enable row level security;
alter table public.electronics_model_specs enable row level security;
alter table public.electronics_model_options enable row level security;
alter table public.electronics_listings enable row level security;

drop policy if exists electronics_categories_public_read on public.electronics_categories;
create policy electronics_categories_public_read
on public.electronics_categories
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists electronics_categories_admin_manage on public.electronics_categories;
create policy electronics_categories_admin_manage
on public.electronics_categories
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists electronics_brands_public_read on public.electronics_brands;
create policy electronics_brands_public_read
on public.electronics_brands
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists electronics_brands_admin_manage on public.electronics_brands;
create policy electronics_brands_admin_manage
on public.electronics_brands
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists electronics_models_public_read on public.electronics_models;
create policy electronics_models_public_read
on public.electronics_models
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists electronics_models_admin_manage on public.electronics_models;
create policy electronics_models_admin_manage
on public.electronics_models
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists electronics_model_specs_public_read on public.electronics_model_specs;
create policy electronics_model_specs_public_read
on public.electronics_model_specs
for select
using (is_public = true or public.is_admin(auth.uid()));

drop policy if exists electronics_model_specs_admin_manage on public.electronics_model_specs;
create policy electronics_model_specs_admin_manage
on public.electronics_model_specs
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists electronics_model_options_public_read on public.electronics_model_options;
create policy electronics_model_options_public_read
on public.electronics_model_options
for select
using (true);

drop policy if exists electronics_model_options_admin_manage on public.electronics_model_options;
create policy electronics_model_options_admin_manage
on public.electronics_model_options
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists electronics_listings_select_public_or_owner_or_admin on public.electronics_listings;
create policy electronics_listings_select_public_or_owner_or_admin
on public.electronics_listings
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = electronics_listings.listing_id
      and (l.status = 'approved' or l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists electronics_listings_write_owner_or_admin on public.electronics_listings;
create policy electronics_listings_write_owner_or_admin
on public.electronics_listings
for all
using (
  exists (
    select 1
    from public.listings l
    where l.id = electronics_listings.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.listings l
    where l.id = electronics_listings.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

-- Ensure Phones & Electronics root node has the full subtree needed for fast posting.
with phones_root as (
  select cn.id as root_id, cn.category_id
  from public.categories c
  join public.category_nodes cn on cn.category_id = c.id and cn.parent_id is null
  where c.slug = 'mobile-phones-tablets'
  limit 1
)
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active, description, icon, sort_order)
select
  pr.category_id,
  pr.root_id,
  x.name,
  x.slug,
  2,
  'mobile-phones-tablets/' || x.slug,
  x.sort_order,
  true,
  x.description,
  x.icon,
  x.sort_order
from phones_root pr
cross join (
  values
    ('Mobile Phones', 'mobile-phones', 1, 'Smartphones and feature phones.', 'smartphone'),
    ('Tablets', 'tablets', 2, 'Tablets and iPads.', 'tablet'),
    ('Smart Watches', 'smart-watches', 3, 'Smart watches and wearables.', 'watch'),
    ('Laptops', 'laptops', 4, 'Laptops and notebooks.', 'laptop'),
    ('Desktop Computers', 'desktop-computers', 5, 'Desktop PCs and towers.', 'monitor'),
    ('Computer Parts', 'computer-parts', 6, 'Components and internal parts.', 'cpu'),
    ('Monitors', 'monitors', 7, 'Computer monitors and displays.', 'monitor'),
    ('TVs', 'tvs', 8, 'Televisions and smart TVs.', 'tv'),
    ('Gaming Consoles', 'gaming-consoles', 9, 'PlayStation, Xbox, Nintendo.', 'gamepad-2'),
    ('Cameras', 'cameras', 10, 'Camera bodies and systems.', 'camera'),
    ('Audio Equipment', 'audio-equipment', 11, 'Audio and sound devices.', 'speaker'),
    ('Networking Equipment', 'networking-equipment', 12, 'Routers, modems, and network devices.', 'router'),
    ('Printers & Scanners', 'printers-scanners', 13, 'Printing and scanning devices.', 'printer'),
    ('Projectors', 'projectors', 14, 'Projectors and accessories.', 'projector'),
    ('Storage Devices', 'storage-devices', 15, 'SSD, HDD, and memory devices.', 'hard-drive'),
    ('Solar & Power Equipment', 'solar-power-equipment', 16, 'Solar and power products.', 'sun'),
    ('Phone Accessories', 'phone-accessories', 17, 'Mobile accessories.', 'headphones'),
    ('Computer Accessories', 'computer-accessories', 18, 'Computer accessories.', 'keyboard'),
    ('Other Electronics', 'other-electronics', 19, 'Other electronic items.', 'dots-horizontal')
) as x(name, slug, sort_order, description, icon)
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  sort_order = excluded.sort_order,
  description = excluded.description,
  icon = excluded.icon,
  is_active = true,
  updated_at = now();

insert into public.electronics_categories (name, parent_id, slug, icon, sort_order, is_active, category_node_id)
values ('Phones & Electronics', null, 'phones-electronics', 'smartphone', 1, true, null)
on conflict (slug) do update
set
  name = excluded.name,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true;

with root as (
  select id from public.electronics_categories where slug = 'phones-electronics' limit 1
), nodes as (
  select cn.id, cn.slug
  from public.category_nodes cn
  where cn.path like 'mobile-phones-tablets/%' and cn.level = 2
)
insert into public.electronics_categories (name, parent_id, slug, icon, sort_order, is_active, category_node_id)
select x.name, r.id, x.slug, x.icon, x.sort_order, true, n.id
from root r
join (
  values
    ('Mobile Phones', 'mobile-phones', 'smartphone', 1),
    ('Tablets', 'tablets', 'tablet', 2),
    ('Smart Watches', 'smart-watches', 'watch', 3),
    ('Laptops', 'laptops', 'laptop', 4),
    ('Desktop Computers', 'desktop-computers', 'monitor', 5),
    ('Computer Parts', 'computer-parts', 'cpu', 6),
    ('Monitors', 'monitors', 'monitor', 7),
    ('TVs', 'tvs', 'tv', 8),
    ('Gaming Consoles', 'gaming-consoles', 'gamepad-2', 9),
    ('Cameras', 'cameras', 'camera', 10),
    ('Audio Equipment', 'audio-equipment', 'speaker', 11),
    ('Networking Equipment', 'networking-equipment', 'router', 12),
    ('Printers & Scanners', 'printers-scanners', 'printer', 13),
    ('Projectors', 'projectors', 'projector', 14),
    ('Storage Devices', 'storage-devices', 'hard-drive', 15),
    ('Solar & Power Equipment', 'solar-power-equipment', 'sun', 16),
    ('Phone Accessories', 'phone-accessories', 'headphones', 17),
    ('Computer Accessories', 'computer-accessories', 'keyboard', 18),
    ('Other Electronics', 'other-electronics', 'dots-horizontal', 19)
) as x(name, slug, icon, sort_order) on true
left join nodes n on n.slug = x.slug
on conflict (slug) do update
set
  name = excluded.name,
  parent_id = excluded.parent_id,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true,
  category_node_id = coalesce(excluded.category_node_id, public.electronics_categories.category_node_id);

-- Seed mobile phone brands with Afghanistan-priority sorting.
with phones as (
  select id from public.electronics_categories where slug = 'mobile-phones' limit 1
)
insert into public.electronics_brands (category_id, name, slug, sort_order, is_popular, is_active)
select phones.id, b.name, b.slug, b.sort_order, b.is_popular, true
from phones
join (
  values
    ('Apple', 'apple', 1, true),
    ('Samsung', 'samsung', 2, true),
    ('Xiaomi', 'xiaomi', 3, true),
    ('Redmi', 'redmi', 4, true),
    ('Huawei', 'huawei', 5, true),
    ('Honor', 'honor', 6, true),
    ('Oppo', 'oppo', 7, true),
    ('Vivo', 'vivo', 8, true),
    ('Nokia', 'nokia', 9, true),
    ('Infinix', 'infinix', 10, true),
    ('Tecno', 'tecno', 11, true),
    ('Realme', 'realme', 12, true),
    ('Poco', 'poco', 13, false),
    ('OnePlus', 'oneplus', 14, false),
    ('Google Pixel', 'google-pixel', 15, false),
    ('Motorola', 'motorola', 16, false),
    ('Sony', 'sony', 17, false),
    ('Asus', 'asus', 18, false),
    ('Nothing', 'nothing', 19, false),
    ('Itel', 'itel', 20, false),
    ('ZTE', 'zte', 21, false),
    ('Other', 'other', 99, false)
) as b(name, slug, sort_order, is_popular) on true
on conflict (category_id, slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_popular = excluded.is_popular,
  is_active = true;

-- Seed laptop brands.
with laptops as (
  select id from public.electronics_categories where slug = 'laptops' limit 1
)
insert into public.electronics_brands (category_id, name, slug, sort_order, is_popular, is_active)
select laptops.id, b.name, b.slug, b.sort_order, b.is_popular, true
from laptops
join (
  values
    ('Apple', 'apple', 1, true),
    ('Dell', 'dell', 2, true),
    ('HP', 'hp', 3, true),
    ('Lenovo', 'lenovo', 4, true),
    ('Asus', 'asus', 5, true),
    ('Acer', 'acer', 6, false),
    ('MSI', 'msi', 7, false),
    ('Microsoft', 'microsoft', 8, false),
    ('Samsung', 'samsung', 9, false),
    ('Huawei', 'huawei', 10, false),
    ('Toshiba', 'toshiba', 11, false),
    ('Other', 'other', 99, false)
) as b(name, slug, sort_order, is_popular) on true
on conflict (category_id, slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_popular = excluded.is_popular,
  is_active = true;

-- Seed TV brands.
with tvs as (
  select id from public.electronics_categories where slug = 'tvs' limit 1
)
insert into public.electronics_brands (category_id, name, slug, sort_order, is_popular, is_active)
select tvs.id, b.name, b.slug, b.sort_order, b.is_popular, true
from tvs
join (
  values
    ('Samsung', 'samsung', 1, true),
    ('LG', 'lg', 2, true),
    ('Sony', 'sony', 3, true),
    ('TCL', 'tcl', 4, true),
    ('Hisense', 'hisense', 5, true),
    ('Panasonic', 'panasonic', 6, false),
    ('Xiaomi', 'xiaomi', 7, false),
    ('Philips', 'philips', 8, false),
    ('Other', 'other', 99, false)
) as b(name, slug, sort_order, is_popular) on true
on conflict (category_id, slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_popular = excluded.is_popular,
  is_active = true;

-- Seed gaming console brands.
with consoles as (
  select id from public.electronics_categories where slug = 'gaming-consoles' limit 1
)
insert into public.electronics_brands (category_id, name, slug, sort_order, is_popular, is_active)
select consoles.id, b.name, b.slug, b.sort_order, b.is_popular, true
from consoles
join (
  values
    ('Sony PlayStation', 'sony-playstation', 1, true),
    ('Microsoft Xbox', 'microsoft-xbox', 2, true),
    ('Nintendo', 'nintendo', 3, true),
    ('Other', 'other', 99, false)
) as b(name, slug, sort_order, is_popular) on true
on conflict (category_id, slug) do update
set
  name = excluded.name,
  sort_order = excluded.sort_order,
  is_popular = excluded.is_popular,
  is_active = true;

-- Seed Apple iPhone model set (new and older) including fallback.
with phones as (
  select id from public.electronics_categories where slug = 'mobile-phones' limit 1
), apple as (
  select b.id as brand_id, p.id as category_id
  from phones p
  join public.electronics_brands b on b.category_id = p.id and b.slug = 'apple'
)
insert into public.electronics_models (brand_id, category_id, name, slug, release_year, is_popular, is_active)
select apple.brand_id, apple.category_id, m.name, m.slug, m.release_year, m.is_popular, true
from apple
join (
  values
    ('iPhone 16 Pro Max', 'iphone-16-pro-max', 2024, true),
    ('iPhone 16 Pro', 'iphone-16-pro', 2024, true),
    ('iPhone 16 Plus', 'iphone-16-plus', 2024, false),
    ('iPhone 16', 'iphone-16', 2024, true),
    ('iPhone 15 Pro Max', 'iphone-15-pro-max', 2023, true),
    ('iPhone 15 Pro', 'iphone-15-pro', 2023, true),
    ('iPhone 15 Plus', 'iphone-15-plus', 2023, false),
    ('iPhone 15', 'iphone-15', 2023, true),
    ('iPhone 14 Pro Max', 'iphone-14-pro-max', 2022, true),
    ('iPhone 14 Pro', 'iphone-14-pro', 2022, true),
    ('iPhone 14 Plus', 'iphone-14-plus', 2022, false),
    ('iPhone 14', 'iphone-14', 2022, true),
    ('iPhone 13 Pro Max', 'iphone-13-pro-max', 2021, true),
    ('iPhone 13 Pro', 'iphone-13-pro', 2021, true),
    ('iPhone 13', 'iphone-13', 2021, true),
    ('iPhone 13 mini', 'iphone-13-mini', 2021, false),
    ('iPhone 12 Pro Max', 'iphone-12-pro-max', 2020, true),
    ('iPhone 12 Pro', 'iphone-12-pro', 2020, false),
    ('iPhone 12', 'iphone-12', 2020, true),
    ('iPhone 11 Pro Max', 'iphone-11-pro-max', 2019, true),
    ('iPhone 11 Pro', 'iphone-11-pro', 2019, false),
    ('iPhone 11', 'iphone-11', 2019, true),
    ('iPhone XS Max', 'iphone-xs-max', 2018, false),
    ('iPhone X', 'iphone-x', 2017, false),
    ('iPhone 8 Plus', 'iphone-8-plus', 2017, false),
    ('iPhone 7 Plus', 'iphone-7-plus', 2016, false),
    ('Other iPhone', 'other-iphone', null, false)
) as m(name, slug, release_year, is_popular) on true
on conflict (brand_id, slug) do update
set
  name = excluded.name,
  release_year = excluded.release_year,
  is_popular = excluded.is_popular,
  is_active = true;

-- Seed baseline popular models for key Afghanistan brands (including other fallback).
with phones as (
  select id from public.electronics_categories where slug = 'mobile-phones' limit 1
), brand_models as (
  select b.id as brand_id, p.id as category_id, b.slug as brand_slug
  from phones p
  join public.electronics_brands b on b.category_id = p.id
  where b.slug in ('samsung', 'xiaomi', 'redmi', 'huawei', 'honor', 'oppo', 'vivo', 'nokia', 'infinix', 'tecno', 'realme')
)
insert into public.electronics_models (brand_id, category_id, name, slug, release_year, is_popular, is_active)
select bm.brand_id, bm.category_id, m.name, m.slug, m.release_year, m.is_popular, true
from brand_models bm
join (
  values
    ('samsung', 'Galaxy S24 Ultra', 'galaxy-s24-ultra', 2024, true),
    ('samsung', 'Galaxy A55', 'galaxy-a55', 2024, true),
    ('samsung', 'Galaxy A34', 'galaxy-a34', 2023, true),
    ('samsung', 'Other Samsung', 'other-samsung', null, false),
    ('xiaomi', 'Xiaomi 14', 'xiaomi-14', 2024, true),
    ('xiaomi', 'Xiaomi 13T', 'xiaomi-13t', 2023, true),
    ('xiaomi', 'Other Xiaomi', 'other-xiaomi', null, false),
    ('redmi', 'Redmi Note 13 Pro', 'redmi-note-13-pro', 2024, true),
    ('redmi', 'Redmi Note 12', 'redmi-note-12', 2023, true),
    ('redmi', 'Other Redmi', 'other-redmi', null, false),
    ('huawei', 'Huawei P60 Pro', 'huawei-p60-pro', 2023, false),
    ('huawei', 'Huawei Nova 11', 'huawei-nova-11', 2023, false),
    ('huawei', 'Other Huawei', 'other-huawei', null, false),
    ('honor', 'Honor 90', 'honor-90', 2023, true),
    ('honor', 'Honor X9b', 'honor-x9b', 2023, true),
    ('honor', 'Other Honor', 'other-honor', null, false),
    ('oppo', 'Oppo Reno 11', 'oppo-reno-11', 2024, true),
    ('oppo', 'Oppo A78', 'oppo-a78', 2023, true),
    ('oppo', 'Other Oppo', 'other-oppo', null, false),
    ('vivo', 'Vivo V30', 'vivo-v30', 2024, true),
    ('vivo', 'Vivo Y27', 'vivo-y27', 2023, true),
    ('vivo', 'Other Vivo', 'other-vivo', null, false),
    ('nokia', 'Nokia G22', 'nokia-g22', 2023, false),
    ('nokia', 'Nokia C32', 'nokia-c32', 2023, false),
    ('nokia', 'Other Nokia', 'other-nokia', null, false),
    ('infinix', 'Infinix Note 40', 'infinix-note-40', 2024, true),
    ('infinix', 'Infinix Hot 40', 'infinix-hot-40', 2023, true),
    ('infinix', 'Other Infinix', 'other-infinix', null, false),
    ('tecno', 'Tecno Camon 30', 'tecno-camon-30', 2024, true),
    ('tecno', 'Tecno Spark 20', 'tecno-spark-20', 2023, true),
    ('tecno', 'Other Tecno', 'other-tecno', null, false),
    ('realme', 'Realme 12 Pro', 'realme-12-pro', 2024, true),
    ('realme', 'Realme C67', 'realme-c67', 2023, true),
    ('realme', 'Other Realme', 'other-realme', null, false)
) as m(brand_slug, name, slug, release_year, is_popular)
  on m.brand_slug = bm.brand_slug
on conflict (brand_id, slug) do update
set
  name = excluded.name,
  release_year = excluded.release_year,
  is_popular = excluded.is_popular,
  is_active = true;

-- Seed console models.
with consoles as (
  select id from public.electronics_categories where slug = 'gaming-consoles' limit 1
), brands as (
  select b.id as brand_id, b.slug as brand_slug, c.id as category_id
  from consoles c
  join public.electronics_brands b on b.category_id = c.id
)
insert into public.electronics_models (brand_id, category_id, name, slug, release_year, is_popular, is_active)
select b.brand_id, b.category_id, m.name, m.slug, m.release_year, true, true
from brands b
join (
  values
    ('sony-playstation', 'PlayStation 5', 'playstation-5', 2020),
    ('sony-playstation', 'PlayStation 5 Slim', 'playstation-5-slim', 2023),
    ('sony-playstation', 'PlayStation 4 Pro', 'playstation-4-pro', 2016),
    ('sony-playstation', 'PlayStation 4', 'playstation-4', 2013),
    ('microsoft-xbox', 'Xbox Series X', 'xbox-series-x', 2020),
    ('microsoft-xbox', 'Xbox Series S', 'xbox-series-s', 2020),
    ('microsoft-xbox', 'Xbox One', 'xbox-one', 2013),
    ('nintendo', 'Nintendo Switch', 'nintendo-switch', 2017),
    ('nintendo', 'Nintendo Switch OLED', 'nintendo-switch-oled', 2021),
    ('nintendo', 'Nintendo Switch Lite', 'nintendo-switch-lite', 2019)
) as m(brand_slug, name, slug, release_year)
  on m.brand_slug = b.brand_slug
on conflict (brand_id, slug) do update
set
  name = excluded.name,
  release_year = excluded.release_year,
  is_active = true;

-- Seed known specs for iPhone 15 Pro Max example.
with model_row as (
  select m.id
  from public.electronics_models m
  join public.electronics_brands b on b.id = m.brand_id
  where b.slug = 'apple' and m.slug = 'iphone-15-pro-max'
  limit 1
)
insert into public.electronics_model_specs (model_id, spec_key, spec_label, spec_value, spec_group, is_public, is_filterable)
select model_row.id, s.spec_key, s.spec_label, s.spec_value, s.spec_group, true, s.is_filterable
from model_row
join (
  values
    ('brand', 'Brand', 'Apple', 'identity', false),
    ('model', 'Model', 'iPhone 15 Pro Max', 'identity', false),
    ('os', 'Operating System', 'iOS', 'platform', true),
    ('screen_size', 'Screen Size', '6.7 inch', 'display', true),
    ('display_type', 'Display', 'OLED', 'display', true),
    ('support_5g', '5G Support', 'Yes', 'network', true),
    ('face_id', 'Face ID', 'Yes', 'security', false),
    ('wireless_charging', 'Wireless Charging', 'Yes', 'power', false),
    ('sim_type', 'SIM Type', 'Nano SIM / eSIM', 'network', true),
    ('release_year', 'Release Year', '2023', 'identity', true),
    ('processor', 'Processor', 'Apple A17 Pro', 'performance', true)
) as s(spec_key, spec_label, spec_value, spec_group, is_filterable) on true
on conflict (model_id, spec_key) do update
set
  spec_label = excluded.spec_label,
  spec_value = excluded.spec_value,
  spec_group = excluded.spec_group,
  is_public = excluded.is_public,
  is_filterable = excluded.is_filterable;

-- Seed iPhone 15 Pro Max options (storage, color).
with model_row as (
  select m.id
  from public.electronics_models m
  join public.electronics_brands b on b.id = m.brand_id
  where b.slug = 'apple' and m.slug = 'iphone-15-pro-max'
  limit 1
)
insert into public.electronics_model_options (model_id, option_type, option_value, sort_order)
select model_row.id, o.option_type, o.option_value, o.sort_order
from model_row
join (
  values
    ('storage', '256GB', 1),
    ('storage', '512GB', 2),
    ('storage', '1TB', 3),
    ('color', 'Natural Titanium', 1),
    ('color', 'Black Titanium', 2),
    ('color', 'White Titanium', 3),
    ('color', 'Blue Titanium', 4)
) as o(option_type, option_value, sort_order) on true
on conflict (model_id, option_type, option_value) do update
set
  sort_order = excluded.sort_order;

-- Posting config by electronics subcategory.
with target as (
  select
    ec.id as electronics_category_id,
    ec.category_node_id,
    true as requires_images,
    1 as min_images,
    case
      when ec.slug in ('mobile-phones', 'laptops', 'tablets', 'smart-watches', 'phone-accessories', 'computer-accessories', 'other-electronics') then 8
      else 10
    end as max_images,
    case
      when ec.slug in ('mobile-phones', 'laptops', 'tablets', 'smart-watches', 'second-hand-items') then '3-8'
      when ec.slug in ('phone-accessories', 'computer-accessories') then '1-4'
      else '3-8'
    end as recommended_images,
    true as allow_manual_model,
    false as allow_video
  from public.electronics_categories ec
  where ec.parent_id is not null
    and ec.category_node_id is not null
), updated as (
  update public.posting_category_config cfg
  set
    requires_images = t.requires_images,
    min_images = t.min_images,
    max_images = t.max_images,
    recommended_images = t.recommended_images,
    allow_manual_model = t.allow_manual_model,
    allow_video = t.allow_video,
    category_node_id = coalesce(cfg.category_node_id, t.category_node_id),
    is_active = true
  from target t
  where cfg.electronics_category_id = t.electronics_category_id
     or (cfg.electronics_category_id is null and cfg.category_node_id = t.category_node_id)
  returning cfg.electronics_category_id
)
insert into public.posting_category_config (
  category_node_id,
  electronics_category_id,
  requires_images,
  min_images,
  max_images,
  recommended_images,
  allow_manual_model,
  allow_video,
  is_active
)
select
  t.category_node_id,
  t.electronics_category_id,
  t.requires_images,
  t.min_images,
  t.max_images,
  t.recommended_images,
  t.allow_manual_model,
  t.allow_video,
  true
from target t
left join updated u on u.electronics_category_id = t.electronics_category_id
where u.electronics_category_id is null;

-- Category fields for mobile phones.
with mobile as (
  select category_node_id from public.electronics_categories where slug = 'mobile-phones' and category_node_id is not null limit 1
), mobile_source as (
  select
    mobile.category_node_id,
    f.field_key,
    f.field_label,
    f.field_type,
    f.options_json,
    f.is_required,
    f.is_filterable,
    f.sort_order,
    f.show_condition
  from mobile
  join (
    values
      ('storage', 'Storage', 'select', '["64GB","128GB","256GB","512GB","1TB","Other"]'::jsonb, true, true, 1, null::jsonb),
      ('battery_health', 'Battery Health', 'select', '["100%","95-99%","90-94%","85-89%","80-84%","Below 80%","Unknown"]'::jsonb, false, true, 2, '{"brand_slug":["apple"]}'::jsonb),
      ('color', 'Color', 'text', null::jsonb, false, true, 3, null::jsonb),
      ('condition', 'Condition', 'select', '["New","Like New","Excellent","Good","Fair","Damaged","For Parts"]'::jsonb, true, true, 4, null::jsonb),
      ('warranty', 'Warranty', 'select', '["No Warranty","Shop Warranty","Official Warranty","International Warranty"]'::jsonb, false, true, 5, null::jsonb),
      ('box_included', 'Box Included', 'boolean', null::jsonb, false, false, 6, null::jsonb),
      ('charger_included', 'Charger Included', 'boolean', null::jsonb, false, false, 7, null::jsonb),
      ('repair_history', 'Repair History', 'select', '["No Repair","Screen Replaced","Battery Replaced","Back Glass Replaced","Camera Repaired","Board Repaired","Unknown"]'::jsonb, false, true, 8, null::jsonb),
      ('network_registered', 'Network Registered', 'select', '["Registered","Not Registered","Unknown"]'::jsonb, false, true, 9, null::jsonb)
  ) as f(field_key, field_label, field_type, options_json, is_required, is_filterable, sort_order, show_condition) on true
), mobile_updated as (
  update public.category_fields cf
  set
    field_label = ms.field_label,
    field_type = ms.field_type,
    options_json = ms.options_json,
    is_required = ms.is_required,
    is_filterable = ms.is_filterable,
    is_searchable = true,
    sort_order = ms.sort_order,
    display_order = ms.sort_order,
    show_condition = ms.show_condition,
    is_active = true,
    updated_at = now()
  from mobile_source ms
  where cf.category_node_id = ms.category_node_id
    and cf.category_id is null
    and cf.field_key = ms.field_key
  returning cf.category_node_id, cf.field_key
)
insert into public.category_fields (
  category_node_id,
  category_id,
  field_key,
  field_label,
  field_type,
  options_json,
  is_required,
  is_filterable,
  is_searchable,
  sort_order,
  display_order,
  is_active,
  show_condition
)
select
  ms.category_node_id,
  null,
  ms.field_key,
  ms.field_label,
  ms.field_type,
  ms.options_json,
  ms.is_required,
  ms.is_filterable,
  true,
  ms.sort_order,
  ms.sort_order,
  true,
  ms.show_condition
from mobile_source ms
left join mobile_updated mu
  on mu.category_node_id = ms.category_node_id
 and mu.field_key = ms.field_key
where mu.category_node_id is null;

-- Fast fields for tablets/laptops/tvs/consoles/accessories.
with target_categories as (
  select category_node_id, slug
  from public.electronics_categories
  where slug in ('tablets', 'smart-watches', 'laptops', 'desktop-computers', 'computer-parts', 'tvs', 'gaming-consoles', 'cameras', 'audio-equipment', 'networking-equipment', 'solar-power-equipment', 'phone-accessories', 'computer-accessories', 'other-electronics')
    and category_node_id is not null
), fast_source as (
  select
    tc.category_node_id,
    f.field_key,
    f.field_label,
    f.field_type,
    f.options_json,
    f.is_required,
    f.is_filterable,
    f.sort_order
  from target_categories tc
  join (
    values
      ('condition', 'Condition', 'select', '["New","Like New","Excellent","Good","Fair","Needs Repair","For Parts"]'::jsonb, true, true, 1),
      ('warranty', 'Warranty', 'select', '["No Warranty","Shop Warranty","Official Warranty","International Warranty"]'::jsonb, false, true, 2),
      ('storage', 'Storage', 'text', null::jsonb, false, true, 3),
      ('ram', 'RAM', 'text', null::jsonb, false, true, 4),
      ('graphics_card', 'Graphics Card', 'text', null::jsonb, false, true, 5),
      ('screen_size', 'Screen Size', 'text', null::jsonb, false, true, 6),
      ('smart_tv', 'Smart TV', 'boolean', null::jsonb, false, true, 7),
      ('controller_count', 'Controller Count', 'number', null::jsonb, false, true, 8),
      ('watt', 'Watt', 'text', null::jsonb, false, true, 9),
      ('voltage', 'Voltage', 'text', null::jsonb, false, true, 10),
      ('item_type', 'Item Type', 'text', null::jsonb, false, true, 11)
  ) as f(field_key, field_label, field_type, options_json, is_required, is_filterable, sort_order) on true
), fast_updated as (
  update public.category_fields cf
  set
    field_label = fs.field_label,
    field_type = fs.field_type,
    options_json = fs.options_json,
    is_required = fs.is_required,
    is_filterable = fs.is_filterable,
    is_searchable = true,
    sort_order = fs.sort_order,
    display_order = fs.sort_order,
    is_active = true,
    updated_at = now()
  from fast_source fs
  where cf.category_node_id = fs.category_node_id
    and cf.category_id is null
    and cf.field_key = fs.field_key
  returning cf.category_node_id, cf.field_key
)
insert into public.category_fields (
  category_node_id,
  category_id,
  field_key,
  field_label,
  field_type,
  options_json,
  is_required,
  is_filterable,
  is_searchable,
  sort_order,
  display_order,
  is_active
)
select
  fs.category_node_id,
  null,
  fs.field_key,
  fs.field_label,
  fs.field_type,
  fs.options_json,
  fs.is_required,
  fs.is_filterable,
  true,
  fs.sort_order,
  fs.sort_order,
  true
from fast_source fs
left join fast_updated fu
  on fu.category_node_id = fs.category_node_id
 and fu.field_key = fs.field_key
where fu.category_node_id is null;

-- Dynamic search filter definitions for key electronics nodes.
insert into public.filter_definitions (
  category_node_id,
  filter_key,
  filter_label,
  filter_type,
  options,
  source_table,
  source_column,
  sort_order,
  is_active
)
select
  ec.category_node_id,
  fd.filter_key,
  fd.filter_label,
  fd.filter_type,
  fd.options,
  fd.source_table,
  fd.source_column,
  fd.sort_order,
  true
from public.electronics_categories ec
join (
  values
    ('brand', 'Brand', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 1),
    ('model', 'Model', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 2),
    ('storage', 'Storage', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 3),
    ('condition', 'Condition', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 4),
    ('battery_health', 'Battery Health', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 5),
    ('network_registered', 'Network Registered', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 6),
    ('ram', 'RAM', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 7),
    ('graphics_card', 'Graphics Card', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 8),
    ('screen_size', 'Screen Size', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 9),
    ('smart_tv', 'Smart TV', 'boolean', null::jsonb, 'listing_attributes', 'attribute_value_boolean', 10),
    ('controller_count', 'Controller Count', 'range', null::jsonb, 'listing_attributes', 'attribute_value_number', 11),
    ('watt', 'Watt', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 12),
    ('voltage', 'Voltage', 'text', null::jsonb, 'listing_attributes', 'attribute_value_text', 13)
) as fd(filter_key, filter_label, filter_type, options, source_table, source_column, sort_order) on true
where ec.category_node_id is not null
  and ec.slug in ('mobile-phones', 'laptops', 'tvs', 'gaming-consoles', 'solar-power-equipment')
on conflict (category_node_id, filter_key) do update
set
  filter_label = excluded.filter_label,
  filter_type = excluded.filter_type,
  options = excluded.options,
  source_table = excluded.source_table,
  source_column = excluded.source_column,
  sort_order = excluded.sort_order,
  is_active = true;
