-- Sahibash location schema upgrade
-- Multilingual names, aliases, optional district for areas, and area moderation queue

begin;

-- =========================================================
-- 1) Multilingual columns + aliases
-- =========================================================

alter table public.provinces
  add column if not exists name_en text,
  add column if not exists name_fa text,
  add column if not exists name_ps text,
  add column if not exists aliases jsonb not null default '[]'::jsonb;

update public.provinces
set
  name_en = coalesce(nullif(name_en, ''), name),
  name_fa = coalesce(nullif(name_fa, ''), name),
  name_ps = coalesce(nullif(name_ps, ''), name),
  aliases = case
    when aliases is null then '[]'::jsonb
    when jsonb_typeof(aliases) = 'array' then aliases
    else '[]'::jsonb
  end;

alter table public.provinces
  alter column name_en set not null,
  alter column name_fa set not null,
  alter column name_ps set not null;

alter table public.districts
  add column if not exists name_en text,
  add column if not exists name_fa text,
  add column if not exists name_ps text,
  add column if not exists aliases jsonb not null default '[]'::jsonb;

update public.districts
set
  name_en = coalesce(nullif(name_en, ''), name),
  name_fa = coalesce(nullif(name_fa, ''), name),
  name_ps = coalesce(nullif(name_ps, ''), name),
  aliases = case
    when aliases is null then '[]'::jsonb
    when jsonb_typeof(aliases) = 'array' then aliases
    else '[]'::jsonb
  end;

alter table public.districts
  alter column name_en set not null,
  alter column name_fa set not null,
  alter column name_ps set not null;

alter table public.areas
  add column if not exists province_id bigint references public.provinces(id) on delete cascade,
  add column if not exists name_en text,
  add column if not exists name_fa text,
  add column if not exists name_ps text,
  add column if not exists aliases jsonb not null default '[]'::jsonb,
  add column if not exists is_popular boolean not null default false;

update public.areas a
set province_id = d.province_id
from public.districts d
where a.district_id = d.id
  and a.province_id is null;

update public.areas
set
  name_en = coalesce(nullif(name_en, ''), name),
  name_fa = coalesce(nullif(name_fa, ''), name),
  name_ps = coalesce(nullif(name_ps, ''), name),
  aliases = case
    when aliases is null then '[]'::jsonb
    when jsonb_typeof(aliases) = 'array' then aliases
    else '[]'::jsonb
  end;

alter table public.areas
  alter column province_id set not null,
  alter column district_id drop not null,
  alter column name_en set not null,
  alter column name_fa set not null,
  alter column name_ps set not null;

-- Existing unique(district_id, slug) cannot enforce uniqueness for nullable district_id rows.
alter table public.areas
  drop constraint if exists areas_unique_per_district;

create unique index if not exists uq_areas_province_district_slug
  on public.areas (province_id, coalesce(district_id, 0), slug);

create index if not exists idx_provinces_aliases_gin on public.provinces using gin (aliases);
create index if not exists idx_districts_aliases_gin on public.districts using gin (aliases);
create index if not exists idx_areas_aliases_gin on public.areas using gin (aliases);
create index if not exists idx_areas_province_id on public.areas (province_id);
create index if not exists idx_areas_popular_active on public.areas (is_popular, is_active);

-- Keep exact GPS private by default unless seller explicitly opts in.
alter table public.listings
  alter column location_visibility set default 'province_district'::public.location_visibility;

-- =========================================================
-- 2) Area moderation queue (admin can approve/edit/merge)
-- =========================================================

create table if not exists public.area_suggestions (
  id bigint generated by default as identity primary key,
  province_id bigint not null references public.provinces(id) on delete cascade,
  district_id bigint references public.districts(id) on delete set null,
  suggested_name text not null,
  suggested_name_en text,
  suggested_name_fa text,
  suggested_name_ps text,
  suggested_aliases jsonb not null default '[]'::jsonb,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'merged')),
  approved_area_id bigint references public.areas(id) on delete set null,
  submitted_by uuid references auth.users(id) on delete set null,
  admin_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_area_suggestions_status on public.area_suggestions(status);
create index if not exists idx_area_suggestions_province_district on public.area_suggestions(province_id, district_id);

alter table public.area_suggestions enable row level security;

drop policy if exists "area_suggestions_public_insert" on public.area_suggestions;
create policy "area_suggestions_public_insert" on public.area_suggestions
for insert
with check (auth.uid() is not null);

drop policy if exists "area_suggestions_owner_read" on public.area_suggestions;
create policy "area_suggestions_owner_read" on public.area_suggestions
for select
using (submitted_by = auth.uid());

drop policy if exists "area_suggestions_admin_read" on public.area_suggestions;
create policy "area_suggestions_admin_read" on public.area_suggestions
for select
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

drop policy if exists "area_suggestions_admin_update" on public.area_suggestions;
create policy "area_suggestions_admin_update" on public.area_suggestions
for update
using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

commit;
