begin;

create table if not exists public.homepage_sections (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  section_type text not null default 'hero',
  title text not null default 'Untitled section',
  body text not null default 'No content yet',
  cta_label text,
  cta_path text,
  sort_order integer not null default 0,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.homepage_sections enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'homepage_sections' and policyname = 'homepage_sections_readable_by_all'
  ) then
    create policy "homepage_sections_readable_by_all"
    on public.homepage_sections
    for select
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'homepage_sections' and policyname = 'homepage_sections_writeable_by_admins'
  ) then
    create policy "homepage_sections_writeable_by_admins"
    on public.homepage_sections
    for all
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;
end
$$;

commit;
