-- Reviewed production policy snapshot, 2026-09-16.
-- Preserve all SELECT access and every owner/participant branch at AAL1.
-- Require AAL2 only for administrator mutation authority.
-- No changes to role helpers, table data, grants, or service-role operations.
-- Scope: 116 public policies + 3 listing-image storage policies.
-- Already-AAL2 policies and owner-only policies are deliberately not touched.
-- Abort on ANY targeted policy drift before changing ANY policy.

do $admin_mutation_mfa$
declare
  targets constant jsonb := $reviewed_policy_snapshot$
[
  {
    "tablename": "admin_permissions",
    "policyname": "admin_permissions_admin_only",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "admin_role_permissions",
    "policyname": "admin_role_permissions_admin_only",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "admin_roles",
    "policyname": "admin_roles_admin_only",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "admin_user_roles",
    "policyname": "admin_user_roles_admin_only",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "ai_moderation_reviews",
    "policyname": "ai_moderation_reviews_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'ai.moderate'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission))",
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'ai.moderate'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission))",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'ai.moderate'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'ai.moderate'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "area_suggestions",
    "policyname": "area_suggestions_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "areas",
    "policyname": "areas_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "areas",
    "policyname": "areas_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "audit_logs",
    "policyname": "audit_logs_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "((admin_user_id = ( SELECT auth.uid() AS uid)) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (((admin_user_id = ( SELECT auth.uid() AS uid)) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))",
    "schemaname": "public"
  },
  {
    "tablename": "categories",
    "policyname": "categories_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "category_aliases",
    "policyname": "category_aliases_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "category_aliases",
    "policyname": "category_aliases_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "category_aliases",
    "policyname": "category_aliases_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "category_fields",
    "policyname": "category_fields_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "category_fields",
    "policyname": "category_fields_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "category_fields",
    "policyname": "category_fields_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "category_nodes",
    "policyname": "category_nodes_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "category_schema_profiles",
    "policyname": "category_schema_profiles_writeable_by_super_administrators",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "countries",
    "policyname": "countries_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "countries",
    "policyname": "countries_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "districts",
    "policyname": "districts_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "districts",
    "policyname": "districts_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_brands",
    "policyname": "electronics_brands_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "electronics_brands",
    "policyname": "electronics_brands_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_brands",
    "policyname": "electronics_brands_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_categories",
    "policyname": "electronics_categories_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "electronics_categories",
    "policyname": "electronics_categories_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_categories",
    "policyname": "electronics_categories_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_listings",
    "policyname": "electronics_listings_delete_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "electronics_listings",
    "policyname": "electronics_listings_insert_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_listings",
    "policyname": "electronics_listings_update_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = electronics_listings.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_model_options",
    "policyname": "electronics_model_options_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "electronics_model_options",
    "policyname": "electronics_model_options_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_model_options",
    "policyname": "electronics_model_options_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_model_specs",
    "policyname": "electronics_model_specs_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "electronics_model_specs",
    "policyname": "electronics_model_specs_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_model_specs",
    "policyname": "electronics_model_specs_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_models",
    "policyname": "electronics_models_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "electronics_models",
    "policyname": "electronics_models_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "electronics_models",
    "policyname": "electronics_models_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "external_import_opt_outs",
    "policyname": "external_import_opt_outs_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "favorites",
    "policyname": "favorites_delete_own_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "filter_definitions",
    "policyname": "filter_definitions_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "filter_definitions",
    "policyname": "filter_definitions_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "filter_definitions",
    "policyname": "filter_definitions_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "homepage_sections",
    "policyname": "homepage_sections_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "homepage_sections",
    "policyname": "homepage_sections_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "homepage_sections",
    "policyname": "homepage_sections_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_attributes",
    "policyname": "listing_attributes_delete_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "listing_attributes",
    "policyname": "listing_attributes_insert_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_attributes",
    "policyname": "listing_attributes_update_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_attributes.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_category_path",
    "policyname": "listing_category_path_delete_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "listing_category_path",
    "policyname": "listing_category_path_insert_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_category_path",
    "policyname": "listing_category_path_update_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_category_path.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_drafts",
    "policyname": "listing_drafts_owner_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "listing_drafts",
    "policyname": "listing_drafts_owner_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_drafts",
    "policyname": "listing_drafts_owner_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "strategy": "gate_admin_branch",
    "new_using": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_duplicate_group_members",
    "policyname": "listing_duplicate_members_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_duplicate_groups",
    "policyname": "listing_duplicate_groups_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_freshness_policies",
    "policyname": "listing_freshness_policies_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_images",
    "policyname": "listing_images_delete_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "listing_images",
    "policyname": "listing_images_insert_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_images",
    "policyname": "listing_images_update_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_images.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_ingest_candidate_media",
    "policyname": "listing_ingest_candidate_media_super_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_ingest_candidates",
    "policyname": "listing_ingest_candidates_super_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_ingest_jobs",
    "policyname": "listing_ingest_jobs_super_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_price_history",
    "policyname": "listing_price_history_insert_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_price_history.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "(EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_price_history.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_provenance_events",
    "policyname": "listing_provenance_events_system_insert",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "((actor_user_id = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_provenance_events.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text))))))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "((actor_user_id = ( SELECT auth.uid() AS uid)) AND (EXISTS ( SELECT 1\n   FROM listings l\n  WHERE ((l.id = listing_provenance_events.listing_id) AND ((l.user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text)))))))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_quality_signals",
    "policyname": "listing_quality_signals_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_risk_signals",
    "policyname": "listing_risk_signals_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_source_observations",
    "policyname": "listing_source_observations_super_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_sources",
    "policyname": "listing_sources_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "with_check": "( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_super_administrator(( SELECT auth.uid() AS uid)) AS is_super_administrator)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_translation_jobs",
    "policyname": "Admins manage translation jobs",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "ALL",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_translations",
    "policyname": "listing_translations_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "listing_translations",
    "policyname": "listing_translations_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "listing_translations",
    "policyname": "listing_translations_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "listings",
    "policyname": "listings_delete_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "DELETE",
    "qual": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "listings",
    "policyname": "listings_update_owner_limited_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "UPDATE",
    "qual": "((user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": "(( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin) OR ((user_id = ( SELECT auth.uid() AS uid)) AND (featured = false) AND (urgent = false) AND (approved_by IS NULL) AND (approved_at IS NULL) AND (status = ANY (ARRAY['pending'::listing_status, 'rejected'::listing_status, 'sold'::listing_status, 'expired'::listing_status]))))",
    "strategy": "gate_admin_branch",
    "new_using": "((user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "((( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)) OR ((user_id = ( SELECT auth.uid() AS uid)) AND (featured = false) AND (urgent = false) AND (approved_by IS NULL) AND (approved_at IS NULL) AND (status = ANY (ARRAY['pending'::listing_status, 'rejected'::listing_status, 'sold'::listing_status, 'expired'::listing_status]))))",
    "schemaname": "public"
  },
  {
    "tablename": "market_cell_retirement_policies",
    "policyname": "market_cell_retirement_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "market_cell_rollup_runs",
    "policyname": "market_cell_rollup_runs_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "messages",
    "policyname": "messages_update_recipient_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "((recipient_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": "((recipient_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "strategy": "gate_admin_branch",
    "new_using": "((recipient_user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "((recipient_user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "moderation_workflow_entries",
    "policyname": "moderation_workflow_entries_authorized_write",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "navigation_items",
    "policyname": "navigation_items_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "navigation_items",
    "policyname": "navigation_items_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "navigation_items",
    "policyname": "navigation_items_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "offers",
    "policyname": "offers_update_seller_or_buyer_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "((buyer_user_id = ( SELECT auth.uid() AS uid)) OR (seller_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "with_check": "((buyer_user_id = ( SELECT auth.uid() AS uid)) OR (seller_user_id = ( SELECT auth.uid() AS uid)) OR ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin))",
    "strategy": "gate_admin_branch",
    "new_using": "((buyer_user_id = ( SELECT auth.uid() AS uid)) OR (seller_user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "((buyer_user_id = ( SELECT auth.uid() AS uid)) OR (seller_user_id = ( SELECT auth.uid() AS uid)) OR (( SELECT private.is_aal2() AS is_aal2) AND ( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "organization_members",
    "policyname": "organization_members_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "organizations",
    "policyname": "organizations_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "posting_category_config",
    "policyname": "posting_category_config_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "posting_category_config",
    "policyname": "posting_category_config_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "posting_category_config",
    "policyname": "posting_category_config_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "price_intelligence_snapshots",
    "policyname": "price_intelligence_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "product_specs",
    "policyname": "product_specs_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "product_specs",
    "policyname": "product_specs_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "product_specs",
    "policyname": "product_specs_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "provinces",
    "policyname": "provinces_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "provinces",
    "policyname": "provinces_admin_write",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((EXISTS ( SELECT 1\n   FROM profiles p\n  WHERE ((p.id = ( SELECT auth.uid() AS uid)) AND (p.role = 'admin'::profile_role))))))",
    "schemaname": "public"
  },
  {
    "tablename": "reports",
    "policyname": "reports_delete_admin_only",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "reports",
    "policyname": "reports_update_admin_only",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "scout_submissions",
    "policyname": "scout_submissions_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "UPDATE",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "search_alias_dictionary",
    "policyname": "search_alias_dictionary_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "search_alias_dictionary",
    "policyname": "search_alias_dictionary_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "search_alias_dictionary",
    "policyname": "search_alias_dictionary_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "seller_entities",
    "policyname": "seller_entities_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'users.verify'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "seller_lead_summaries",
    "policyname": "seller_lead_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "site_settings",
    "policyname": "site_settings_authorized_insert",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "site_settings",
    "policyname": "site_settings_authorized_update",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "UPDATE",
    "qual": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))",
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "site_settings_versions",
    "policyname": "site_settings_versions_authorized_insert",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'settings.publish'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "static_page_versions",
    "policyname": "static_page_versions_authorized_insert",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.publish'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.publish'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "static_pages",
    "policyname": "static_pages_authorized_insert",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "static_pages",
    "policyname": "static_pages_authorized_update",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "UPDATE",
    "qual": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.publish'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))",
    "with_check": "(( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.publish'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.publish'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND ((( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.update'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'pages.publish'::text) AS has_admin_permission) OR ( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'configuration.rollback'::text) AS has_admin_permission))))",
    "schemaname": "public"
  },
  {
    "tablename": "subcategories",
    "policyname": "subcategories_admin_delete",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "DELETE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": null,
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": null,
    "schemaname": "public"
  },
  {
    "tablename": "subcategories",
    "policyname": "subcategories_admin_insert",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": null,
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "subcategories",
    "policyname": "subcategories_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{public}",
    "cmd": "UPDATE",
    "qual": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "with_check": "( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT is_admin(( SELECT auth.uid() AS uid)) AS is_admin)))",
    "schemaname": "public"
  },
  {
    "tablename": "support_requests",
    "policyname": "support_requests_admin_update",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "UPDATE",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'audit_logs.view'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'audit_logs.view'::text) AS has_admin_permission)",
    "strategy": "gate_admin_operation",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'audit_logs.view'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'audit_logs.view'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "tablename": "wanted_request_matches",
    "policyname": "wanted_matches_admin_manage",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "ALL",
    "qual": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "with_check": "( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)",
    "strategy": "split_admin_all",
    "new_using": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "new_check": "(( SELECT private.is_aal2() AS is_aal2) AND (( SELECT has_admin_permission(( SELECT auth.uid() AS uid), 'listings.moderate'::text) AS has_admin_permission)))",
    "schemaname": "public"
  },
  {
    "schemaname": "storage",
    "tablename": "objects",
    "policyname": "listing_images_delete_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "DELETE",
    "qual": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR is_admin(auth.uid())))",
    "with_check": null,
    "strategy": "gate_admin_branch",
    "new_using": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR (( SELECT private.is_aal2() AS is_aal2) AND is_admin(auth.uid()))))",
    "new_check": null
  },
  {
    "schemaname": "storage",
    "tablename": "objects",
    "policyname": "listing_images_update_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "UPDATE",
    "qual": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR is_admin(auth.uid())))",
    "with_check": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR is_admin(auth.uid())))",
    "strategy": "gate_admin_branch",
    "new_using": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR (( SELECT private.is_aal2() AS is_aal2) AND is_admin(auth.uid()))))",
    "new_check": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR (( SELECT private.is_aal2() AS is_aal2) AND is_admin(auth.uid()))))"
  },
  {
    "schemaname": "storage",
    "tablename": "objects",
    "policyname": "listing_images_upload_owner_or_admin",
    "permissive": "PERMISSIVE",
    "roles": "{authenticated}",
    "cmd": "INSERT",
    "qual": null,
    "with_check": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR is_admin(auth.uid())))",
    "strategy": "gate_admin_branch",
    "new_using": null,
    "new_check": "((bucket_id = 'listing-images'::text) AND (((storage.foldername(name))[1] = (auth.uid())::text) OR (( SELECT private.is_aal2() AS is_aal2) AND is_admin(auth.uid()))))"
  }
]
$reviewed_policy_snapshot$::jsonb;
  target jsonb;
  actual record;
  roles_sql text;
  using_sql text;
  check_sql text;
  operation text;
  new_name text;
begin
  perform set_config('search_path', 'pg_catalog, public, pg_temp', true);
  if to_regprocedure('private.is_aal2()') is null then
    raise exception 'Required existing private.is_aal2() helper is missing';
  end if;

  -- Validate the complete fixed target set first. This is not a pattern-based
  -- rewrite of live policy definitions: all names and expressions are pinned.
  for target in select value from jsonb_array_elements(targets)
  loop
    select * into actual
    from pg_policies p
    where p.schemaname = target->>'schemaname'
      and p.tablename = target->>'tablename'
      and p.policyname = target->>'policyname';

    if not found
       or actual.cmd is distinct from target->>'cmd'
       or actual.permissive is distinct from target->>'permissive'
       or actual.roles::text is distinct from target->>'roles'
       or actual.qual is distinct from target->>'qual'
       or actual.with_check is distinct from target->>'with_check' then
      raise exception 'Policy drift: %.%.%',
        target->>'schemaname', target->>'tablename', target->>'policyname';
    end if;

    if target->>'strategy' = 'split_admin_all' then
      foreach operation in array array['insert', 'update', 'delete']
      loop
        new_name := 'mfa2_' || (target->>'tablename') || '_' || operation;
        if octet_length(new_name) > 63 or exists (
          select 1 from pg_policies p
          where p.schemaname = target->>'schemaname'
            and p.tablename = target->>'tablename'
            and p.policyname = new_name
        ) then
          raise exception 'MFA policy name is unavailable: %', new_name;
        end if;
      end loop;
    end if;
  end loop;

  for target in select value from jsonb_array_elements(targets)
  loop
    select string_agg(quote_ident(role_name::text), ', ')
      into roles_sql
      from unnest((target->>'roles')::name[]) as role_names(role_name);
    using_sql := target->>'new_using';
    check_sql := target->>'new_check';

    if target->>'strategy' = 'split_admin_all' then
      -- Keep the original policy name for its unchanged read authorization.
      execute format('drop policy %I on %I.%I',
        target->>'policyname', target->>'schemaname', target->>'tablename');
      execute format('create policy %I on %I.%I as %s for select to %s using (%s)',
        target->>'policyname', target->>'schemaname', target->>'tablename',
        target->>'permissive', roles_sql, target->>'qual');
      execute format('create policy %I on %I.%I as %s for insert to %s with check (%s)',
        'mfa2_' || (target->>'tablename') || '_insert',
        target->>'schemaname', target->>'tablename', target->>'permissive', roles_sql, check_sql);
      execute format('create policy %I on %I.%I as %s for update to %s using (%s) with check (%s)',
        'mfa2_' || (target->>'tablename') || '_update',
        target->>'schemaname', target->>'tablename', target->>'permissive', roles_sql, using_sql, check_sql);
      execute format('create policy %I on %I.%I as %s for delete to %s using (%s)',
        'mfa2_' || (target->>'tablename') || '_delete',
        target->>'schemaname', target->>'tablename', target->>'permissive', roles_sql, using_sql);
    elsif target->>'cmd' = 'INSERT' then
      execute format('alter policy %I on %I.%I with check (%s)',
        target->>'policyname', target->>'schemaname', target->>'tablename', check_sql);
    elsif target->>'cmd' = 'UPDATE' then
      execute format('alter policy %I on %I.%I using (%s) with check (%s)',
        target->>'policyname', target->>'schemaname', target->>'tablename', using_sql, check_sql);
    elsif target->>'cmd' = 'DELETE' then
      execute format('alter policy %I on %I.%I using (%s)',
        target->>'policyname', target->>'schemaname', target->>'tablename', using_sql);
    else
      raise exception 'Unexpected reviewed mutation command: %', target->>'cmd';
    end if;
  end loop;
end;
$admin_mutation_mfa$;
