begin;

create table if not exists public.moderation_workflow_entries (
  id bigint generated by default as identity primary key,
  entity_type text not null default 'listing',
  entity_id bigint not null,
  status text not null default 'pending',
  summary text not null default 'Needs review',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.moderation_workflow_entries enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'moderation_workflow_entries' and policyname = 'moderation_workflow_entries_readable_by_admins'
  ) then
    create policy "moderation_workflow_entries_readable_by_admins"
    on public.moderation_workflow_entries
    for select
    using (public.is_admin(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'moderation_workflow_entries' and policyname = 'moderation_workflow_entries_writeable_by_admins'
  ) then
    create policy "moderation_workflow_entries_writeable_by_admins"
    on public.moderation_workflow_entries
    for all
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;
end
$$;

commit;
