begin;

create table if not exists public.vehicle_series (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.vehicle_brands(id) on delete cascade,
  name text not null,
  slug text not null,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_series_brand_slug_unique unique (brand_id, slug)
);

alter table public.vehicle_models
  add column if not exists series_id bigint references public.vehicle_series(id) on delete set null;

alter table public.vehicle_variants
  add column if not exists body_type text,
  add column if not exists engine_power text,
  add column if not exists engine_capacity text,
  add column if not exists wheel_drive text,
  add column if not exists doors int,
  add column if not exists seats int;

create table if not exists public.vehicle_feature_groups (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.vehicle_features (
  id bigint generated by default as identity primary key,
  group_id bigint not null references public.vehicle_feature_groups(id) on delete cascade,
  name text not null,
  slug text not null unique,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_vehicle_features (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  feature_id bigint not null references public.vehicle_features(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint listing_vehicle_features_unique unique (listing_id, feature_id)
);

alter table public.listings
  add column if not exists neighborhood text,
  add column if not exists video_url text;

create index if not exists idx_vehicle_series_brand on public.vehicle_series(brand_id, is_active, display_order);
create index if not exists idx_vehicle_models_series on public.vehicle_models(series_id, is_active, display_order);
create index if not exists idx_vehicle_variants_model_filters on public.vehicle_variants(generation_id, fuel_type, transmission, is_active);
create index if not exists idx_listing_vehicle_features_listing on public.listing_vehicle_features(listing_id);
create index if not exists idx_listing_vehicle_features_feature on public.listing_vehicle_features(feature_id);
create index if not exists idx_listings_province_status on public.listings(province, status, created_at desc);
create index if not exists idx_listings_district_status on public.listings(district, status, created_at desc);

alter table public.vehicle_series enable row level security;
alter table public.vehicle_feature_groups enable row level security;
alter table public.vehicle_features enable row level security;
alter table public.listing_vehicle_features enable row level security;

drop policy if exists vehicle_series_public_read on public.vehicle_series;
create policy vehicle_series_public_read on public.vehicle_series for select using (is_active = true);

drop policy if exists vehicle_feature_groups_public_read on public.vehicle_feature_groups;
create policy vehicle_feature_groups_public_read on public.vehicle_feature_groups for select using (true);

drop policy if exists vehicle_features_public_read on public.vehicle_features;
create policy vehicle_features_public_read on public.vehicle_features for select using (is_active = true);

drop policy if exists listing_vehicle_features_visible_read on public.listing_vehicle_features;
create policy listing_vehicle_features_visible_read on public.listing_vehicle_features
for select using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_vehicle_features.listing_id
      and (l.status = 'approved' or l.user_id = auth.uid())
  )
);

drop policy if exists listing_vehicle_features_owner_write on public.listing_vehicle_features;
create policy listing_vehicle_features_owner_write on public.listing_vehicle_features
for all using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_vehicle_features.listing_id
      and l.user_id = auth.uid()
  )
);

insert into public.vehicle_feature_groups (name, slug, sort_order)
values
  ('Security', 'security', 1),
  ('Interior', 'interior', 2),
  ('Exterior', 'exterior', 3),
  ('Multimedia', 'multimedia', 4)
on conflict (slug) do update
set name = excluded.name,
    sort_order = excluded.sort_order;

with grouped_features as (
  select 'security'::text as group_slug, unnest(array[
    'ABS','EBD','Air Bag Driver','Air Bag Passenger','Blind Spot Detection','Children Lock','ESP / VSA',
    'Hill Holder','Immobilizer','Isofix','Lane Tracking System','Night Vision','Power Door Locks'
  ]) as feature_name
  union all
  select 'interior', unnest(array[
    'Air Conditioning','Cruise Control','Electric Windows','Functional Steering Wheel','Head-up Display',
    'Heated Wheel','Hydraulic Steering','Keyless Start','Leather Seat','Rear View Camera','Electric Seats',
    'Memory Seats','Heated Seats','Cooling Seats','Auto-darkening Rearview Mirror','Fabric Seat',
    'Front Seat Armrest','Start / Stop','Trip Computer'
  ])
  union all
  select 'exterior', unnest(array[
    'Adaptive Headlights','Electric Mirrors','Heated Mirrors','Parking Sensor Rear','Parking Sensor Front',
    'Parking Assistant','Sunroof','Glass Roof','Smart Boot Lid','Trailer Tow Bar'
  ])
  union all
  select 'multimedia', unnest(array[
    'Android Auto','Apple CarPlay','Bluetooth','USB / AUX','Touch Screen','Navigation','Sound System'
  ])
)
insert into public.vehicle_features (group_id, name, slug, sort_order, is_active)
select g.id,
       f.feature_name,
       lower(regexp_replace(regexp_replace(f.feature_name, '[^a-zA-Z0-9]+', '-', 'g'), '(^-|-$)', '', 'g')),
       row_number() over (partition by g.id order by f.feature_name),
       true
from grouped_features f
join public.vehicle_feature_groups g on g.slug = f.group_slug
on conflict (slug) do update
set name = excluded.name,
    group_id = excluded.group_id,
    sort_order = excluded.sort_order,
    is_active = true;

commit;