-- Category-based posting flow configuration for Post Ad

create table if not exists public.posting_category_config (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete cascade,
  category_node_id bigint references public.category_nodes(id) on delete cascade,
  requires_images boolean not null default true,
  min_images int not null default 1,
  max_images int not null default 15,
  recommended_images text,
  allow_video boolean not null default false,
  posting_flow_type text not null default 'standard',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint posting_category_config_valid_images check (min_images >= 0 and max_images >= min_images),
  constraint posting_category_config_target_required check (category_id is not null or category_node_id is not null)
);

create unique index if not exists ux_posting_category_config_category_id
  on public.posting_category_config(category_id)
  where category_id is not null;

create unique index if not exists ux_posting_category_config_node_id
  on public.posting_category_config(category_node_id)
  where category_node_id is not null;

alter table public.category_fields
  add column if not exists category_id bigint references public.categories(id) on delete cascade,
  add column if not exists is_filterable boolean not null default false,
  add column if not exists is_searchable boolean not null default true,
  add column if not exists sort_order int not null default 0;

update public.category_fields cf
set category_id = cn.category_id
from public.category_nodes cn
where cf.category_node_id = cn.id
  and cf.category_id is null;

create table if not exists public.listing_category_path (
  id bigint generated by default as identity primary key,
  listing_id uuid not null unique references public.listings(id) on delete cascade,
  main_category_id bigint not null references public.categories(id) on delete restrict,
  subcategory_id bigint not null references public.category_nodes(id) on delete restrict,
  child_category_id bigint not null references public.category_nodes(id) on delete restrict,
  brand_id bigint,
  model_id bigint,
  created_at timestamptz not null default now()
);

create index if not exists idx_listing_category_path_main on public.listing_category_path(main_category_id);
create index if not exists idx_listing_category_path_sub on public.listing_category_path(subcategory_id);
create index if not exists idx_listing_category_path_child on public.listing_category_path(child_category_id);

alter table public.posting_category_config enable row level security;
alter table public.listing_category_path enable row level security;

drop policy if exists posting_category_config_public_read on public.posting_category_config;
create policy posting_category_config_public_read
on public.posting_category_config
for select
using (is_active = true);

drop policy if exists posting_category_config_admin_manage on public.posting_category_config;
create policy posting_category_config_admin_manage
on public.posting_category_config
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists listing_category_path_owner_or_admin_read on public.listing_category_path;
create policy listing_category_path_owner_or_admin_read
on public.listing_category_path
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_category_path.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_category_path_owner_or_admin_write on public.listing_category_path;
create policy listing_category_path_owner_or_admin_write
on public.listing_category_path
for all
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_category_path.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_category_path.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

with target as (
  select
    c.id as category_id,
    case when c.slug = 'real-estate' then false else true end as requires_images,
    case when c.slug = 'real-estate' then 0 else 1 end as min_images,
    case
      when c.slug in ('vehicles', 'real-estate') then 15
      when c.slug in ('mobile-phones-tablets', 'second-hand-items') then 10
      else 10
    end as max_images,
    case
      when c.slug = 'vehicles' then '6-15'
      when c.slug = 'real-estate' then '5-15'
      when c.slug in ('mobile-phones-tablets', 'second-hand-items') then '3-8'
      else null
    end as recommended_images,
    case when c.slug in ('vehicles', 'real-estate') then true else false end as allow_video,
    'category_adaptive'::text as posting_flow_type
  from public.categories c
  where c.slug in ('vehicles', 'real-estate', 'mobile-phones-tablets', 'second-hand-items')
), updated as (
  update public.posting_category_config cfg
  set
    requires_images = t.requires_images,
    min_images = t.min_images,
    max_images = t.max_images,
    recommended_images = t.recommended_images,
    allow_video = t.allow_video,
    posting_flow_type = t.posting_flow_type,
    is_active = true
  from target t
  where cfg.category_id = t.category_id
  returning cfg.category_id
)
insert into public.posting_category_config (
  category_id,
  requires_images,
  min_images,
  max_images,
  recommended_images,
  allow_video,
  posting_flow_type,
  is_active
)
select
  t.category_id,
  t.requires_images,
  t.min_images,
  t.max_images,
  t.recommended_images,
  t.allow_video,
  t.posting_flow_type,
  true
from target t
left join updated u on u.category_id = t.category_id
where u.category_id is null;

update public.posting_category_config cfg
set
  requires_images = false,
  min_images = 0,
  max_images = greatest(cfg.max_images, 10),
  recommended_images = 'optional',
  allow_video = true
where cfg.category_node_id in (
  select id
  from public.category_nodes
  where path like 'real-estate/land%'
);
