-- Launch phase category lifecycle and waitlist support

alter table public.categories
  add column if not exists is_coming_soon boolean not null default false,
  add column if not exists launch_date date;

create table if not exists public.category_waitlists (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  email text,
  created_at timestamptz not null default now(),
  constraint category_waitlists_contact_required check (user_id is not null or email is not null)
);

create index if not exists idx_category_waitlists_category_id
  on public.category_waitlists(category_id);

create index if not exists idx_category_waitlists_created_at
  on public.category_waitlists(created_at desc);

create unique index if not exists ux_category_waitlists_category_email
  on public.category_waitlists(category_id, lower(email))
  where email is not null;

create unique index if not exists ux_category_waitlists_category_user
  on public.category_waitlists(category_id, user_id)
  where user_id is not null;

alter table public.category_waitlists enable row level security;

drop policy if exists category_waitlists_insert_public on public.category_waitlists;
create policy category_waitlists_insert_public
on public.category_waitlists
for insert
to anon, authenticated
with check (user_id is null or auth.uid() = user_id);

drop policy if exists category_waitlists_select_own on public.category_waitlists;
create policy category_waitlists_select_own
on public.category_waitlists
for select
to authenticated
using (auth.uid() = user_id);

update public.categories
set
  is_coming_soon = case
    when slug in ('vehicles', 'real-estate', 'mobile-phones-tablets', 'second-hand-items') then false
    else true
  end,
  launch_date = case
    when slug in ('vehicles', 'real-estate', 'mobile-phones-tablets', 'second-hand-items') then null
    else launch_date
  end
where is_active = true;
