begin;

create table if not exists public.static_pages (
  id bigint generated by default as identity primary key,
  page_key text not null unique,
  slug_en text not null,
  slug_fa text not null,
  slug_ps text not null,
  title_en text not null default '',
  title_fa text not null default '',
  title_ps text not null default '',
  body_en text not null default '',
  body_fa text not null default '',
  body_ps text not null default '',
  seo_title_en text,
  seo_title_fa text,
  seo_title_ps text,
  seo_description_en text,
  seo_description_fa text,
  seo_description_ps text,
  is_published boolean not null default false,
  published_at timestamptz,
  archived_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists static_pages_slug_en_key on public.static_pages (slug_en) where archived_at is null;
create unique index if not exists static_pages_slug_fa_key on public.static_pages (slug_fa) where archived_at is null;
create unique index if not exists static_pages_slug_ps_key on public.static_pages (slug_ps) where archived_at is null;

create table if not exists public.static_page_versions (
  id bigint generated by default as identity primary key,
  static_page_id bigint not null references public.static_pages(id) on delete cascade,
  version_number integer not null,
  change_summary text,
  page_snapshot jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz not null default now(),
  constraint static_page_versions_unique_version unique (static_page_id, version_number)
);

create index if not exists static_page_versions_created_at_idx
  on public.static_page_versions (static_page_id, created_at desc);

alter table public.static_pages enable row level security;
alter table public.static_page_versions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'static_pages' and policyname = 'static_pages_public_read_published'
  ) then
    create policy "static_pages_public_read_published"
    on public.static_pages
    for select
    using (is_published = true and archived_at is null);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'static_pages' and policyname = 'static_pages_admin_all'
  ) then
    create policy "static_pages_admin_all"
    on public.static_pages
    for all
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'static_page_versions' and policyname = 'static_page_versions_admin_select'
  ) then
    create policy "static_page_versions_admin_select"
    on public.static_page_versions
    for select
    using (public.is_admin(auth.uid()));
  end if;
end
$$;

create or replace function public.publish_static_page(
  page_row_id bigint,
  change_summary text,
  editor_id uuid
)
returns public.static_pages
language plpgsql
security definer
set search_path = public
as $$
declare
  draft_row public.static_pages;
  next_version integer;
begin
  select *
  into draft_row
  from public.static_pages
  where id = page_row_id
    and archived_at is null;

  if not found then
    raise exception 'Static page not found';
  end if;

  select coalesce(max(version_number), 0) + 1
  into next_version
  from public.static_page_versions
  where static_page_id = page_row_id;

  insert into public.static_page_versions (
    static_page_id,
    version_number,
    change_summary,
    page_snapshot,
    created_by
  ) values (
    page_row_id,
    next_version,
    nullif(btrim(change_summary), ''),
    to_jsonb(draft_row),
    editor_id
  );

  update public.static_pages
  set is_published = true,
      published_at = now(),
      updated_at = now()
  where id = page_row_id
  returning * into draft_row;

  return draft_row;
end;
$$;

create or replace function public.restore_static_page_version(
  version_row_id bigint,
  change_summary text,
  editor_id uuid
)
returns public.static_pages
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot_row record;
  restored_row public.static_pages;
  next_version integer;
begin
  select *
  into snapshot_row
  from public.static_page_versions
  where id = version_row_id;

  if not found then
    raise exception 'Static page version not found';
  end if;

  insert into public.static_pages (
    id,
    page_key,
    slug_en,
    slug_fa,
    slug_ps,
    title_en,
    title_fa,
    title_ps,
    body_en,
    body_fa,
    body_ps,
    seo_title_en,
    seo_title_fa,
    seo_title_ps,
    seo_description_en,
    seo_description_fa,
    seo_description_ps,
    is_published,
    published_at,
    archived_at,
    updated_at,
    created_at
  )
  select
    (snapshot_row.page_snapshot->>'id')::bigint,
    snapshot_row.page_snapshot->>'page_key',
    snapshot_row.page_snapshot->>'slug_en',
    snapshot_row.page_snapshot->>'slug_fa',
    snapshot_row.page_snapshot->>'slug_ps',
    snapshot_row.page_snapshot->>'title_en',
    snapshot_row.page_snapshot->>'title_fa',
    snapshot_row.page_snapshot->>'title_ps',
    snapshot_row.page_snapshot->>'body_en',
    snapshot_row.page_snapshot->>'body_fa',
    snapshot_row.page_snapshot->>'body_ps',
    nullif(snapshot_row.page_snapshot->>'seo_title_en', ''),
    nullif(snapshot_row.page_snapshot->>'seo_title_fa', ''),
    nullif(snapshot_row.page_snapshot->>'seo_title_ps', ''),
    nullif(snapshot_row.page_snapshot->>'seo_description_en', ''),
    nullif(snapshot_row.page_snapshot->>'seo_description_fa', ''),
    nullif(snapshot_row.page_snapshot->>'seo_description_ps', ''),
    true,
    now(),
    null,
    now(),
    coalesce((snapshot_row.page_snapshot->>'created_at')::timestamptz, now())
  on conflict (id) do update set
    page_key = excluded.page_key,
    slug_en = excluded.slug_en,
    slug_fa = excluded.slug_fa,
    slug_ps = excluded.slug_ps,
    title_en = excluded.title_en,
    title_fa = excluded.title_fa,
    title_ps = excluded.title_ps,
    body_en = excluded.body_en,
    body_fa = excluded.body_fa,
    body_ps = excluded.body_ps,
    seo_title_en = excluded.seo_title_en,
    seo_title_fa = excluded.seo_title_fa,
    seo_title_ps = excluded.seo_title_ps,
    seo_description_en = excluded.seo_description_en,
    seo_description_fa = excluded.seo_description_fa,
    seo_description_ps = excluded.seo_description_ps,
    is_published = true,
    published_at = now(),
    archived_at = null,
    updated_at = now()
  returning * into restored_row;

  select coalesce(max(version_number), 0) + 1
  into next_version
  from public.static_page_versions
  where static_page_id = restored_row.id;

  insert into public.static_page_versions (
    static_page_id,
    version_number,
    change_summary,
    page_snapshot,
    created_by
  ) values (
    restored_row.id,
    next_version,
    coalesce(nullif(btrim(change_summary), ''), 'Restored static page version ' || version_row_id::text),
    to_jsonb(restored_row),
    editor_id
  );

  return restored_row;
end;
$$;

insert into public.static_pages (
  page_key,
  slug_en,
  slug_fa,
  slug_ps,
  title_en,
  title_fa,
  title_ps,
  body_en,
  body_fa,
  body_ps,
  seo_title_en,
  seo_title_fa,
  seo_title_ps,
  seo_description_en,
  seo_description_fa,
  seo_description_ps,
  is_published
)
values
  (
    'about-sahibash',
    'about-sahibash',
    'about-sahibash',
    'about-sahibash',
    'About Sahibash',
    'د صاحباش په اړه',
    'د صاحباش په اړه',
    'Sahibash is a marketplace for Afghanistan.',
    'Sahibash د افغانستان لپاره د اعلانونو بازار دی.',
    'Sahibash د افغانستان لپاره د اعلانونو بازار دی.',
    'About Sahibash',
    'د صاحباش په اړه',
    'د صاحباش په اړه',
    'Learn about the Sahibash marketplace.',
    'د صاحباش بازار په اړه ولولئ.',
    'د صاحباش بازار په اړه ولولئ.',
    true
  ),
  (
    'safety',
    'safety',
    'safety',
    'safety',
    'Safety',
    'خوندیتوب',
    'خوندیتوب',
    'Read the marketplace safety guidance before posting or buying.',
    'د اعلان کولو او پېرودلو څخه مخکې د خوندیتوب لارښوونې ولولئ.',
    'د اعلان کولو او پېرودلو څخه مخکې د خوندیتوب لارښوونې ولولئ.',
    'Safety',
    'خوندیتوب',
    'خوندیتوب',
    'Marketplace safety guidance and reporting tips.',
    'د بازار د خوندیتوب لارښوونې او د راپور ورکولو لارې چارې.',
    'د بازار د خوندیتوب لارښوونې او د راپور ورکولو لارې چارې.',
    true
  ),
  (
    'privacy-policy',
    'privacy-policy',
    'privacy-policy',
    'privacy-policy',
    'Privacy Policy',
    'د محرمیت تګلاره',
    'د محرمیت تګلاره',
    'This page explains how Sahibash handles user data.',
    'دا پاڼه تشریح کوي چې صاحباش د کاروونکو معلومات څنګه سمبالوي.',
    'دا پاڼه تشریح کوي چې صاحباش د کاروونکو معلومات څنګه سمبالوي.',
    'Privacy Policy',
    'د محرمیت تګلاره',
    'د محرمیت تګلاره',
    'How Sahibash handles user data.',
    'صاحباش د کاروونکو معلومات څنګه سمبالوي.',
    'صاحباش د کاروونکو معلومات څنګه سمبالوي.',
    true
  )
on conflict (page_key) do update set
  slug_en = excluded.slug_en,
  slug_fa = excluded.slug_fa,
  slug_ps = excluded.slug_ps,
  title_en = excluded.title_en,
  title_fa = excluded.title_fa,
  title_ps = excluded.title_ps,
  body_en = excluded.body_en,
  body_fa = excluded.body_fa,
  body_ps = excluded.body_ps,
  seo_title_en = excluded.seo_title_en,
  seo_title_fa = excluded.seo_title_fa,
  seo_title_ps = excluded.seo_title_ps,
  seo_description_en = excluded.seo_description_en,
  seo_description_fa = excluded.seo_description_fa,
  seo_description_ps = excluded.seo_description_ps,
  is_published = excluded.is_published,
  updated_at = now();

insert into public.static_page_versions (
  static_page_id,
  version_number,
  change_summary,
  page_snapshot
)
select
  p.id,
  1,
  'Initial static page',
  to_jsonb(p)
from public.static_pages p
where p.page_key in ('about-sahibash', 'safety', 'privacy-policy')
on conflict (static_page_id, version_number) do nothing;

commit;