begin;

create table if not exists public.category_schema_profiles (
  id bigint generated by default as identity primary key,
  category_slug text not null,
  schema_key text not null,
  title text not null default 'Untitled schema',
  description text not null default 'Schema profile',
  is_enabled boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint category_schema_profiles_unique unique (category_slug, schema_key)
);

alter table public.category_schema_profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'category_schema_profiles' and policyname = 'category_schema_profiles_readable_by_all'
  ) then
    create policy "category_schema_profiles_readable_by_all"
    on public.category_schema_profiles
    for select
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'category_schema_profiles' and policyname = 'category_schema_profiles_writeable_by_admins'
  ) then
    create policy "category_schema_profiles_writeable_by_admins"
    on public.category_schema_profiles
    for all
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;
end
$$;

commit;
