-- Sahibash Location System
-- Adds geographical hierarchy for Afghanistan (countries, provinces, districts, areas)
-- Extends listings table with location fields and privacy controls

begin;

-- =========================================================
-- 1) Location Enums
-- =========================================================

do $$
begin
  if not exists (select 1 from pg_type where typname = 'location_source') then
    create type public.location_source as enum ('manual', 'browser', 'gps', 'map_pin');
  end if;

  if not exists (select 1 from pg_type where typname = 'location_visibility') then
    create type public.location_visibility as enum ('exact', 'approximate', 'hidden');
  end if;
end $$;

-- =========================================================
-- 2) Location Tables
-- =========================================================

-- countries
create table if not exists public.countries (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  iso_code text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint countries_slug_format check (slug = lower(slug))
);

-- provinces
create table if not exists public.provinces (
  id bigint generated by default as identity primary key,
  country_id bigint not null references public.countries(id) on delete cascade,
  name text not null,
  slug text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint provinces_unique_per_country unique (country_id, slug),
  constraint provinces_slug_format check (slug = lower(slug))
);

-- districts
create table if not exists public.districts (
  id bigint generated by default as identity primary key,
  province_id bigint not null references public.provinces(id) on delete cascade,
  name text not null,
  slug text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint districts_unique_per_province unique (province_id, slug),
  constraint districts_slug_format check (slug = lower(slug))
);

-- areas (neighborhoods)
create table if not exists public.areas (
  id bigint generated by default as identity primary key,
  district_id bigint not null references public.districts(id) on delete cascade,
  name text not null,
  slug text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint areas_unique_per_district unique (district_id, slug),
  constraint areas_slug_format check (slug = lower(slug))
);

-- =========================================================
-- 3) Extend listings with location fields
-- =========================================================

-- Add location columns to listings table
alter table public.listings
add column if not exists country_id bigint references public.countries(id) on delete set null,
add column if not exists province_id bigint references public.provinces(id) on delete set null,
add column if not exists district_id bigint references public.districts(id) on delete set null,
add column if not exists area_id bigint references public.areas(id) on delete set null,
add column if not exists address_text text,
add column if not exists latitude numeric(10,8),
add column if not exists longitude numeric(11,8),
add column if not exists location_accuracy int,
add column if not exists location_source public.location_source,
add column if not exists location_visibility public.location_visibility not null default 'approximate';

-- =========================================================
-- 4) Indexes for performance
-- =========================================================

create index if not exists idx_countries_slug on public.countries(slug);
create index if not exists idx_countries_active on public.countries(is_active);

create index if not exists idx_provinces_country_id on public.provinces(country_id);
create index if not exists idx_provinces_slug on public.provinces(slug);
create index if not exists idx_provinces_active on public.provinces(is_active);

create index if not exists idx_districts_province_id on public.districts(province_id);
create index if not exists idx_districts_slug on public.districts(slug);
create index if not exists idx_districts_active on public.districts(is_active);

create index if not exists idx_areas_district_id on public.areas(district_id);
create index if not exists idx_areas_slug on public.areas(slug);
create index if not exists idx_areas_active on public.areas(is_active);

-- Listing location indexes
create index if not exists idx_listings_country_id on public.listings(country_id);
create index if not exists idx_listings_province_id on public.listings(province_id);
create index if not exists idx_listings_district_id on public.listings(district_id);
create index if not exists idx_listings_area_id on public.listings(area_id);
create index if not exists idx_listings_location_visibility on public.listings(location_visibility);
create index if not exists idx_listings_coordinates on public.listings(latitude, longitude);
create index if not exists idx_listings_location_source on public.listings(location_source);

-- Combined indexes for common queries
create index if not exists idx_listings_province_status on public.listings(province_id, status);
create index if not exists idx_listings_district_status on public.listings(district_id, status);

-- =========================================================
-- 5) Row Level Security
-- =========================================================

-- Enable RLS on location tables
alter table public.countries enable row level security;
alter table public.provinces enable row level security;
alter table public.districts enable row level security;
alter table public.areas enable row level security;

-- Countries: Public read-only
create policy "countries_public_read" on public.countries
  for select using (true);

create policy "countries_admin_write" on public.countries
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

create policy "countries_admin_update" on public.countries
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

-- Provinces: Public read-only
create policy "provinces_public_read" on public.provinces
  for select using (true);

create policy "provinces_admin_write" on public.provinces
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

create policy "provinces_admin_update" on public.provinces
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

-- Districts: Public read-only
create policy "districts_public_read" on public.districts
  for select using (true);

create policy "districts_admin_write" on public.districts
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

create policy "districts_admin_update" on public.districts
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

-- Areas: Public read-only
create policy "areas_public_read" on public.areas
  for select using (true);

create policy "areas_admin_write" on public.areas
  for insert with check (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

create policy "areas_admin_update" on public.areas
  for update using (
    exists (
      select 1 from public.profiles
      where id = auth.uid()
      and role = 'admin'
    )
  );

-- Update listings RLS to respect location_visibility for coordinates
-- Note: Existing RLS policies on listings remain; this adds location-specific behavior
-- Location coordinates (exact lat/lng) are hidden based on visibility setting via application logic

commit;
