begin;

create table if not exists public.navigation_items (
  id bigint generated by default as identity primary key,
  label text not null default 'Untitled link',
  path text not null default '/',
  parent_id bigint references public.navigation_items(id) on delete cascade,
  sort_order integer not null default 0,
  is_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.navigation_items enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'navigation_items' and policyname = 'navigation_items_readable_by_all'
  ) then
    create policy "navigation_items_readable_by_all"
    on public.navigation_items
    for select
    using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'navigation_items' and policyname = 'navigation_items_writeable_by_admins'
  ) then
    create policy "navigation_items_writeable_by_admins"
    on public.navigation_items
    for all
    using (public.is_admin(auth.uid()))
    with check (public.is_admin(auth.uid()));
  end if;
end
$$;

commit;
