begin;

create table public.listing_engagement_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null check (event_type in ('phone_reveal','call','whatsapp','message','share','favorite','similar_click')),
  locale text not null check (locale in ('en','fa','ps')),
  source text not null default 'listing_detail' check (char_length(source) between 1 and 64),
  created_at timestamptz not null default now()
);

create index listing_engagement_events_listing_created_idx on public.listing_engagement_events(listing_id,created_at desc);
create index listing_engagement_events_type_created_idx on public.listing_engagement_events(event_type,created_at desc);
alter table public.listing_engagement_events enable row level security;

create policy listing_engagement_admin_read on public.listing_engagement_events for select to authenticated
using ((select public.is_admin((select auth.uid()))));

revoke all on table public.listing_engagement_events from anon,authenticated;
grant select on table public.listing_engagement_events to authenticated;

create or replace function private.record_listing_engagement(p_listing_id uuid,p_event_type text,p_locale text,p_source text default 'listing_detail')
returns boolean language plpgsql security definer set search_path=''
as $$
begin
  if p_event_type not in ('phone_reveal','call','whatsapp','message','share','favorite','similar_click')
     or p_locale not in ('en','fa','ps') or char_length(p_source) not between 1 and 64
     or not exists(select 1 from public.listings where id=p_listing_id and status='approved') then
    return false;
  end if;
  insert into public.listing_engagement_events(listing_id,actor_user_id,event_type,locale,source)
  values(p_listing_id,(select auth.uid()),p_event_type,p_locale,p_source);
  return true;
end;
$$;

create function public.record_listing_engagement(p_listing_id uuid,p_event_type text,p_locale text,p_source text default 'listing_detail')
returns boolean language sql security invoker set search_path=''
as $$ select private.record_listing_engagement(p_listing_id,p_event_type,p_locale,p_source); $$;

revoke all on function private.record_listing_engagement(uuid,text,text,text) from public;
grant execute on function private.record_listing_engagement(uuid,text,text,text) to anon,authenticated,service_role;
revoke all on function public.record_listing_engagement(uuid,text,text,text) from public;
grant execute on function public.record_listing_engagement(uuid,text,text,text) to anon,authenticated,service_role;
grant all on table public.listing_engagement_events to service_role;
grant usage,select on sequence public.listing_engagement_events_id_seq to service_role;

commit;
