-- Step 3: Self-sustaining marketplace and bootstrap retirement foundation.
-- Additive, aggregate-first, and privacy-safe. No listings are deleted.

do $$
begin
  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'market_cell_status') then
    create type public.market_cell_status as enum (
      'cold',
      'supply_constrained',
      'demand_constrained',
      'balanced',
      'liquid',
      'saturated_noisy'
    );
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'bootstrap_retirement_stage') then
    create type public.bootstrap_retirement_stage as enum (
      'none',
      'ranking_demotion',
      'quota_reduction',
      'pause_new_ingestion',
      'expiry_only',
      'archive_noindex',
      'rollback_restore'
    );
  end if;

  if not exists (select 1 from pg_type where typnamespace = 'public'::regnamespace and typname = 'trust_quality_band') then
    create type public.trust_quality_band as enum (
      'higher_confidence',
      'standard',
      'needs_review',
      'restricted'
    );
  end if;
end $$;

create table if not exists public.market_cell_retirement_policies (
  id bigint generated by default as identity primary key,
  category_id bigint,
  category_node_id bigint,
  province text,
  district text,
  price_band text,
  attribute_band jsonb not null default '{}'::jsonb,
  min_total_supply integer not null default 12 check (min_total_supply >= 0),
  min_native_or_claimed_share numeric(5,4) not null default 0.65 check (min_native_or_claimed_share between 0 and 1),
  min_search_success_rate numeric(5,4) not null default 0.70 check (min_search_success_rate between 0 and 1),
  min_contact_rate numeric(5,4) not null default 0.08 check (min_contact_rate between 0 and 1),
  max_stale_rate numeric(5,4) not null default 0.25 check (max_stale_rate between 0 and 1),
  min_fresh_native_weekly integer not null default 3 check (min_fresh_native_weekly >= 0),
  rollback_search_success_rate numeric(5,4) not null default 0.45 check (rollback_search_success_rate between 0 and 1),
  rollback_min_total_supply integer not null default 5 check (rollback_min_total_supply >= 0),
  external_quota_percent integer not null default 100 check (external_quota_percent between 0 and 100),
  current_stage public.bootstrap_retirement_stage not null default 'none',
  simulation_only boolean not null default true,
  rollback_enabled boolean not null default true,
  enabled boolean not null default false,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint market_cell_retirement_policy_scope_unique unique (
    category_id,
    category_node_id,
    province,
    district,
    price_band
  )
);

create table if not exists public.market_cell_rollup_runs (
  id uuid primary key default gen_random_uuid(),
  run_kind text not null default 'manual' check (run_kind in ('manual','scheduled','backfill','simulation')),
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null default 'started' check (status in ('started','completed','failed','cancelled')),
  idempotency_key text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  unique (idempotency_key)
);

create table if not exists public.price_intelligence_snapshots (
  id uuid primary key default gen_random_uuid(),
  category_id bigint,
  category_node_id bigint,
  cohort_key text not null,
  province text,
  currency public.currency_code not null default 'AFN',
  sample_count integer not null check (sample_count >= 0),
  p25_price numeric,
  median_price numeric,
  p75_price numeric,
  confidence numeric(5,4) not null default 0 check (confidence between 0 and 1),
  methodology text not null default 'asking_price_cohort_trimmed',
  computed_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '7 days'),
  constraint price_intelligence_snapshot_sample_guard check (
    sample_count < 8
    or (p25_price is not null and median_price is not null and p75_price is not null)
  )
);

alter table public.market_cell_retirement_policies enable row level security;
alter table public.market_cell_rollup_runs enable row level security;
alter table public.price_intelligence_snapshots enable row level security;

drop policy if exists market_cell_retirement_admin_read on public.market_cell_retirement_policies;
create policy market_cell_retirement_admin_read
on public.market_cell_retirement_policies
for select
to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'search.view')));

drop policy if exists market_cell_retirement_admin_write on public.market_cell_retirement_policies;
create policy market_cell_retirement_admin_write
on public.market_cell_retirement_policies
for all
to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'settings.update')))
with check ((select public.has_admin_permission((select auth.uid()), 'settings.update')));

drop policy if exists market_cell_rollup_runs_admin_read on public.market_cell_rollup_runs;
create policy market_cell_rollup_runs_admin_read
on public.market_cell_rollup_runs
for select
to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'search.view')));

drop policy if exists market_cell_rollup_runs_admin_write on public.market_cell_rollup_runs;
create policy market_cell_rollup_runs_admin_write
on public.market_cell_rollup_runs
for insert
to authenticated
with check ((select public.has_admin_permission((select auth.uid()), 'settings.update')));

drop policy if exists price_intelligence_admin_read on public.price_intelligence_snapshots;
create policy price_intelligence_admin_read
on public.price_intelligence_snapshots
for select
to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'search.view')));

drop policy if exists price_intelligence_admin_write on public.price_intelligence_snapshots;
create policy price_intelligence_admin_write
on public.price_intelligence_snapshots
for all
to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'settings.update')))
with check ((select public.has_admin_permission((select auth.uid()), 'settings.update')));

revoke all on table public.market_cell_retirement_policies from anon, authenticated;
revoke all on table public.market_cell_rollup_runs from anon, authenticated;
revoke all on table public.price_intelligence_snapshots from anon, authenticated;
grant select, insert, update, delete on table public.market_cell_retirement_policies to authenticated;
grant select, insert on table public.market_cell_rollup_runs to authenticated;
grant select, insert, update, delete on table public.price_intelligence_snapshots to authenticated;
grant all on table public.market_cell_retirement_policies, public.market_cell_rollup_runs, public.price_intelligence_snapshots to service_role;
grant usage, select on sequence public.market_cell_retirement_policies_id_seq to authenticated, service_role;

create or replace function public.classify_market_cell(
  demand_score numeric,
  fresh_supply_score numeric,
  search_success_rate numeric,
  contact_rate numeric,
  stale_rate numeric,
  native_share numeric
)
returns public.market_cell_status
language sql
immutable
set search_path = ''
as $$
  select case
    when coalesce(demand_score, 0) < 1 and coalesce(fresh_supply_score, 0) < 1 then 'cold'::public.market_cell_status
    when coalesce(stale_rate, 0) >= 0.55 or (coalesce(demand_score, 0) >= 6 and coalesce(fresh_supply_score, 0) < 3) then 'supply_constrained'::public.market_cell_status
    when coalesce(fresh_supply_score, 0) >= 8 and coalesce(contact_rate, 0) < 0.04 and coalesce(search_success_rate, 0) >= 0.75 then 'demand_constrained'::public.market_cell_status
    when coalesce(fresh_supply_score, 0) >= 18 and coalesce(contact_rate, 0) < 0.03 then 'saturated_noisy'::public.market_cell_status
    when coalesce(search_success_rate, 0) >= 0.78 and coalesce(contact_rate, 0) >= 0.08 and coalesce(native_share, 0) >= 0.55 then 'liquid'::public.market_cell_status
    else 'balanced'::public.market_cell_status
  end;
$$;

create or replace function public.next_bootstrap_retirement_stage(
  current_stage public.bootstrap_retirement_stage,
  native_or_claimed_share numeric,
  search_success_rate numeric,
  contact_rate numeric,
  stale_rate numeric,
  fresh_native_weekly integer,
  total_supply integer,
  min_total_supply integer,
  min_native_or_claimed_share numeric,
  min_search_success_rate numeric,
  min_contact_rate numeric,
  max_stale_rate numeric,
  min_fresh_native_weekly integer,
  rollback_enabled boolean,
  rollback_search_success_rate numeric,
  rollback_min_total_supply integer
)
returns public.bootstrap_retirement_stage
language sql
immutable
set search_path = ''
as $$
  select case
    when rollback_enabled
      and current_stage <> 'none'::public.bootstrap_retirement_stage
      and (
        coalesce(search_success_rate, 0) < rollback_search_success_rate
        or coalesce(total_supply, 0) < rollback_min_total_supply
      )
      then 'rollback_restore'::public.bootstrap_retirement_stage
    when coalesce(total_supply, 0) < min_total_supply
      or coalesce(native_or_claimed_share, 0) < min_native_or_claimed_share
      or coalesce(search_success_rate, 0) < min_search_success_rate
      or coalesce(contact_rate, 0) < min_contact_rate
      or coalesce(stale_rate, 1) > max_stale_rate
      or coalesce(fresh_native_weekly, 0) < min_fresh_native_weekly
      then 'none'::public.bootstrap_retirement_stage
    when current_stage = 'none'::public.bootstrap_retirement_stage then 'ranking_demotion'::public.bootstrap_retirement_stage
    when current_stage = 'ranking_demotion'::public.bootstrap_retirement_stage then 'quota_reduction'::public.bootstrap_retirement_stage
    when current_stage = 'quota_reduction'::public.bootstrap_retirement_stage then 'pause_new_ingestion'::public.bootstrap_retirement_stage
    when current_stage = 'pause_new_ingestion'::public.bootstrap_retirement_stage then 'expiry_only'::public.bootstrap_retirement_stage
    when current_stage = 'expiry_only'::public.bootstrap_retirement_stage then 'archive_noindex'::public.bootstrap_retirement_stage
    else current_stage
  end;
$$;

create or replace view public.admin_market_cell_liquidity
with (security_invoker = true)
as
with listing_cells as (
  select
    l.category_id,
    l.category_node_id,
    nullif(l.province, '') as province,
    nullif(l.district, '') as district,
    count(*) filter (where l.status = 'approved')::integer as active_supply,
    count(*) filter (
      where l.status = 'approved'
        and coalesce(l.publication_status::text, 'published') in ('published', 'draft')
        and coalesce(l.freshness_status::text, 'fresh') in ('fresh','seller_confirmed','source_missing')
    )::integer as fresh_supply,
    count(*) filter (
      where l.status = 'approved'
        and (coalesce(l.source_type::text, 'native') = 'native' or coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed')
    )::integer as native_or_claimed_supply,
    count(*) filter (
      where l.status = 'approved'
        and coalesce(l.source_type::text, 'native') = 'external_indexed'
        and coalesce(l.ownership_status::text, 'claimed') = 'unclaimed'
    )::integer as external_unclaimed_supply,
    count(*) filter (
      where l.status = 'approved'
        and coalesce(l.freshness_status::text, 'fresh') in ('aging','stale','source_missing','expired')
    )::integer as stale_supply,
    count(*) filter (
      where l.status = 'approved'
        and l.created_at >= now() - interval '7 days'
        and (coalesce(l.source_type::text, 'native') = 'native' or coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed')
    )::integer as fresh_native_weekly
  from public.listings l
  group by l.category_id, l.category_node_id, nullif(l.province, ''), nullif(l.district, '')
),
search_cells as (
  select
    case when nullif(st.category_filter, '') ~ '^[0-9]+$' then nullif(st.category_filter, '')::bigint else null end as category_node_id,
    nullif(st.province_filter, '') as province,
    nullif(st.district_filter, '') as district,
    count(*)::integer as searches_30d,
    count(*) filter (where st.result_count > 0)::integer as successful_searches_30d,
    count(*) filter (where st.result_count = 0)::integer as zero_result_searches_30d
  from public.search_telemetry st
  where st.created_at >= now() - interval '30 days'
  group by case when nullif(st.category_filter, '') ~ '^[0-9]+$' then nullif(st.category_filter, '')::bigint else null end, nullif(st.province_filter, ''), nullif(st.district_filter, '')
),
contact_cells as (
  select
    l.category_id,
    l.category_node_id,
    nullif(l.province, '') as province,
    nullif(l.district, '') as district,
    count(*) filter (where e.event_type in ('phone_reveal','call','whatsapp','message'))::integer as contact_actions_30d,
    count(distinct e.listing_id) filter (where e.event_type in ('phone_reveal','call','whatsapp','message'))::integer as contacted_listings_30d,
    percentile_cont(0.5) within group (order by extract(epoch from (e.created_at - l.created_at)) / 3600)
      filter (where e.event_type in ('phone_reveal','call','whatsapp','message') and e.created_at >= l.created_at) as median_time_to_contact_hours
  from public.listing_engagement_events e
  join public.listings l on l.id = e.listing_id
  where e.created_at >= now() - interval '30 days'
  group by l.category_id, l.category_node_id, nullif(l.province, ''), nullif(l.district, '')
),
wanted_cells as (
  select
    wr.category_id,
    wr.category_node_id,
    nullif(wr.province, '') as province,
    nullif(wr.district, '') as district,
    count(*) filter (where wr.status = 'active')::integer as active_wanted_requests,
    count(wrm.*)::integer as wanted_matches_30d
  from public.wanted_requests wr
  left join public.wanted_request_matches wrm
    on wrm.wanted_request_id = wr.id
    and wrm.created_at >= now() - interval '30 days'
  where wr.created_at >= now() - interval '90 days'
  group by wr.category_id, wr.category_node_id, nullif(wr.province, ''), nullif(wr.district, '')
),
cell_keys as (
  select category_id, category_node_id, province, district from listing_cells
  union
  select null::bigint as category_id, category_node_id, province, district from search_cells
  union
  select category_id, category_node_id, province, district from contact_cells
  union
  select category_id, category_node_id, province, district from wanted_cells
),
merged as (
  select
    coalesce(k.category_id, lc.category_id, cc.category_id, wc.category_id) as category_id,
    k.category_node_id,
    k.province,
    k.district,
    coalesce(lc.active_supply, 0) as active_supply,
    coalesce(lc.fresh_supply, 0) as fresh_supply,
    coalesce(lc.native_or_claimed_supply, 0) as native_or_claimed_supply,
    coalesce(lc.external_unclaimed_supply, 0) as external_unclaimed_supply,
    coalesce(lc.stale_supply, 0) as stale_supply,
    coalesce(lc.fresh_native_weekly, 0) as fresh_native_weekly,
    coalesce(sc.searches_30d, 0) as searches_30d,
    coalesce(sc.successful_searches_30d, 0) as successful_searches_30d,
    coalesce(sc.zero_result_searches_30d, 0) as zero_result_searches_30d,
    coalesce(cc.contact_actions_30d, 0) as contact_actions_30d,
    coalesce(cc.contacted_listings_30d, 0) as contacted_listings_30d,
    cc.median_time_to_contact_hours,
    coalesce(wc.active_wanted_requests, 0) as active_wanted_requests,
    coalesce(wc.wanted_matches_30d, 0) as wanted_matches_30d
  from cell_keys k
  left join listing_cells lc
    on lc.category_node_id is not distinct from k.category_node_id
    and lc.province is not distinct from k.province
    and lc.district is not distinct from k.district
  left join search_cells sc
    on sc.category_node_id is not distinct from k.category_node_id
    and sc.province is not distinct from k.province
    and sc.district is not distinct from k.district
  left join contact_cells cc
    on cc.category_node_id is not distinct from k.category_node_id
    and cc.province is not distinct from k.province
    and cc.district is not distinct from k.district
  left join wanted_cells wc
    on wc.category_node_id is not distinct from k.category_node_id
    and wc.province is not distinct from k.province
    and wc.district is not distinct from k.district
)
select
  category_id,
  category_node_id,
  province,
  district,
  active_supply,
  fresh_supply,
  native_or_claimed_supply,
  external_unclaimed_supply,
  stale_supply,
  fresh_native_weekly,
  searches_30d,
  successful_searches_30d,
  zero_result_searches_30d,
  contact_actions_30d,
  contacted_listings_30d,
  round(coalesce(successful_searches_30d::numeric / nullif(searches_30d, 0), 0), 4) as search_success_rate,
  round(coalesce(contacted_listings_30d::numeric / nullif(active_supply, 0), 0), 4) as contact_rate,
  round(coalesce(stale_supply::numeric / nullif(active_supply, 0), 0), 4) as stale_rate,
  round(coalesce(native_or_claimed_supply::numeric / nullif(active_supply, 0), 0), 4) as native_or_claimed_share,
  active_wanted_requests,
  wanted_matches_30d,
  round(coalesce(wanted_matches_30d::numeric / nullif(active_wanted_requests, 0), 0), 4) as wanted_match_rate,
  median_time_to_contact_hours,
  (zero_result_searches_30d + active_wanted_requests * 2 + contact_actions_30d)::numeric as demand_score,
  (fresh_supply + fresh_native_weekly * 2)::numeric as fresh_supply_score,
  public.classify_market_cell(
    (zero_result_searches_30d + active_wanted_requests * 2 + contact_actions_30d)::numeric,
    (fresh_supply + fresh_native_weekly * 2)::numeric,
    coalesce(successful_searches_30d::numeric / nullif(searches_30d, 0), 0),
    coalesce(contacted_listings_30d::numeric / nullif(active_supply, 0), 0),
    coalesce(stale_supply::numeric / nullif(active_supply, 0), 0),
    coalesce(native_or_claimed_supply::numeric / nullif(active_supply, 0), 0)
  ) as cell_status
from merged
where
  (searches_30d >= 3 or active_supply >= 3 or active_wanted_requests >= 3 or contact_actions_30d >= 3);

create or replace view public.admin_next_best_markets
with (security_invoker = true)
as
select
  *,
  round(
    (demand_score * 1.8)
    + (zero_result_searches_30d * 2.0)
    + (active_wanted_requests * 1.5)
    + (contact_rate * 40)
    - (fresh_supply_score * 0.7)
    - (native_or_claimed_share * 6)
    - (case when stale_rate > 0.4 then stale_rate * 8 else 0 end),
    2
  ) as priority_score,
  case
    when cell_status = 'supply_constrained' then 'Acquire native/claimed supply in this cell before expanding external volume.'
    when cell_status = 'demand_constrained' then 'Improve buyer demand capture, pricing, and search relevance before acquiring more supply.'
    when cell_status = 'liquid' then 'Candidate for cautious external bootstrap reduction simulation.'
    when cell_status = 'saturated_noisy' then 'Reduce low-quality/noisy inventory and tighten ranking safeguards.'
    else 'Monitor until stronger demand/supply signals accumulate.'
  end as recommended_action
from public.admin_market_cell_liquidity
order by priority_score desc;

create or replace view public.admin_external_retirement_simulation
with (security_invoker = true)
as
select
  m.category_id,
  m.category_node_id,
  m.province,
  m.district,
  p.id as policy_id,
  coalesce(p.current_stage, 'none'::public.bootstrap_retirement_stage) as current_stage,
  public.next_bootstrap_retirement_stage(
    coalesce(p.current_stage, 'none'::public.bootstrap_retirement_stage),
    m.native_or_claimed_share,
    m.search_success_rate,
    m.contact_rate,
    m.stale_rate,
    m.fresh_native_weekly,
    m.active_supply,
    coalesce(p.min_total_supply, 12),
    coalesce(p.min_native_or_claimed_share, 0.65),
    coalesce(p.min_search_success_rate, 0.70),
    coalesce(p.min_contact_rate, 0.08),
    coalesce(p.max_stale_rate, 0.25),
    coalesce(p.min_fresh_native_weekly, 3),
    coalesce(p.rollback_enabled, true),
    coalesce(p.rollback_search_success_rate, 0.45),
    coalesce(p.rollback_min_total_supply, 5)
  ) as recommended_next_stage,
  m.active_supply,
  m.native_or_claimed_supply,
  m.external_unclaimed_supply,
  greatest(0, m.active_supply - m.external_unclaimed_supply) as supply_without_external,
  case
    when m.active_supply = 0 then 0
    else round(greatest(0, m.active_supply - m.external_unclaimed_supply)::numeric / m.active_supply, 4)
  end as simulated_result_retention_rate,
  case
    when m.searches_30d < 3 then null
    when m.active_supply = 0 then 1
    else round(least(1, greatest(0, 1 - (greatest(0, m.active_supply - m.external_unclaimed_supply)::numeric / m.active_supply))) * (1 - m.search_success_rate), 4)
  end as simulated_zero_result_risk,
  coalesce(p.simulation_only, true) as simulation_only,
  coalesce(p.rollback_enabled, true) as rollback_enabled
from public.admin_market_cell_liquidity m
left join public.market_cell_retirement_policies p
  on p.category_id is not distinct from m.category_id
  and p.category_node_id is not distinct from m.category_node_id
  and p.province is not distinct from m.province
  and p.district is not distinct from m.district
  and p.price_band is null;

create or replace view public.admin_price_intelligence_cohorts
with (security_invoker = true)
as
with priced as (
  select
    l.category_id,
    l.category_node_id,
    nullif(l.province, '') as province,
    l.currency,
    l.price,
    l.created_at,
    row_number() over (
      partition by l.category_id, l.category_node_id, nullif(l.province, ''), l.currency
      order by l.price asc
    ) as rn,
    count(*) over (
      partition by l.category_id, l.category_node_id, nullif(l.province, ''), l.currency
    ) as sample_count
  from public.listings l
  where l.status = 'approved'
    and l.price is not null
    and l.price > 0
    and coalesce(l.freshness_status::text, 'fresh') not in ('stale','expired')
    and coalesce(l.publication_status::text, 'published') not in ('archived','removed','hidden')
    and coalesce(l.provenance_confidence, 1) >= 0.5
),
trimmed as (
  select *
  from priced
  where sample_count >= 8
    and rn > greatest(1, floor(sample_count * 0.10)::integer)
    and rn <= least(sample_count, ceil(sample_count * 0.90)::integer)
)
select
  category_id,
  category_node_id,
  province,
  currency,
  sample_count,
  percentile_cont(0.25) within group (order by price)::numeric as p25_price,
  percentile_cont(0.50) within group (order by price)::numeric as median_price,
  percentile_cont(0.75) within group (order by price)::numeric as p75_price,
  round(least(1, sample_count::numeric / 30), 4) as confidence,
  'asking_price_cohort_trimmed'::text as methodology
from trimmed
group by category_id, category_node_id, province, currency, sample_count
having sample_count >= 8;

create or replace view public.admin_listing_trust_quality
with (security_invoker = true)
as
with report_counts as (
  select listing_id, count(*)::integer as report_count
  from public.reports
  where status in ('open','actioned')
  group by listing_id
)
select
  l.id as listing_id,
  l.category_id,
  l.category_node_id,
  l.status,
  l.source_type,
  l.ownership_status,
  l.freshness_status,
  l.publication_status,
  l.provenance_status,
  coalesce(l.provenance_confidence, 0.5) as provenance_confidence,
  coalesce(rc.report_count, 0) as report_count,
  case
    when coalesce(rc.report_count, 0) >= 3 or coalesce(l.publication_status::text, 'published') in ('removed','archived') then 'restricted'::public.trust_quality_band
    when coalesce(l.provenance_confidence, 0.5) < 0.35 or coalesce(l.freshness_status::text, 'fresh') in ('stale','expired') then 'needs_review'::public.trust_quality_band
    when coalesce(l.source_type::text, 'native') in ('native','dealer_managed','partner_feed','seller_approved_import')
      and coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed'
      and coalesce(l.provenance_confidence, 0.5) >= 0.75
      then 'higher_confidence'::public.trust_quality_band
    else 'standard'::public.trust_quality_band
  end as quality_band,
  case
    when coalesce(l.source_type::text, 'native') = 'external_indexed' and coalesce(l.ownership_status::text, 'claimed') = 'unclaimed'
      then 'External seller; availability and ownership are less certain.'
    when coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed'
      then 'Seller owns or manages this listing in Sahibash.'
    else 'Standard marketplace listing; use normal safety checks.'
  end as buyer_label_guidance,
  greatest(
    0,
    least(
      1,
      (coalesce(l.provenance_confidence, 0.5) * 0.45)
      + (case when coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed' then 0.20 else 0 end)
      + (case when coalesce(l.source_type::text, 'native') in ('native','dealer_managed','partner_feed','seller_approved_import') then 0.15 else 0 end)
      + (case when coalesce(l.freshness_status::text, 'fresh') in ('fresh','seller_confirmed') then 0.15 else 0 end)
      - (coalesce(rc.report_count, 0) * 0.08)
    )
  )::numeric(5,4) as internal_quality_score
from public.listings l
left join report_counts rc on rc.listing_id = l.id;

create or replace view public.admin_source_health
with (security_invoker = true)
as
select
  coalesce(l.source_type::text, 'native') as source_type,
  coalesce(l.source_type::text, 'native') as source_name,
  count(*)::integer as total_listings,
  count(*) filter (where l.status = 'approved')::integer as approved_listings,
  count(*) filter (where coalesce(l.publication_status::text, 'published') in ('removed','archived'))::integer as removed_or_archived,
  count(*) filter (where coalesce(l.freshness_status::text, 'fresh') in ('stale','expired'))::integer as stale_or_expired,
  count(*) filter (where coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed')::integer as claimed_or_native,
  round(coalesce(count(*) filter (where coalesce(l.ownership_status::text, 'claimed') <> 'unclaimed')::numeric / nullif(count(*), 0), 0), 4) as claim_or_native_share,
  round(coalesce(count(*) filter (where coalesce(l.freshness_status::text, 'fresh') in ('stale','expired'))::numeric / nullif(count(*), 0), 0), 4) as stale_rate
from public.listings l
group by coalesce(l.source_type::text, 'native')
having count(*) >= 3;

grant execute on function public.classify_market_cell(numeric, numeric, numeric, numeric, numeric, numeric) to authenticated, service_role;
grant execute on function public.next_bootstrap_retirement_stage(public.bootstrap_retirement_stage, numeric, numeric, numeric, numeric, integer, integer, integer, numeric, numeric, numeric, numeric, integer, boolean, numeric, integer) to authenticated, service_role;
grant select on public.admin_market_cell_liquidity to authenticated;
grant select on public.admin_next_best_markets to authenticated;
grant select on public.admin_external_retirement_simulation to authenticated;
grant select on public.admin_price_intelligence_cohorts to authenticated;
grant select on public.admin_listing_trust_quality to authenticated;
grant select on public.admin_source_health to authenticated;

insert into public.feature_flags(key, description, enabled, rollout_percent)
values
  ('step3_network_readiness_dashboard', 'Admin-only marketplace cells, source health, retirement simulation, and readiness reporting.', true, 100),
  ('bootstrap_retirement_enforcement', 'Enforce market-cell-based external bootstrap reduction. Keep disabled until simulations are reviewed.', false, 0),
  ('seller_price_guidance', 'Seller-facing price intelligence ranges for cohorts with sufficient clean samples.', false, 0),
  ('trust_quality_ranking_guardrails', 'Use internal trust/quality bands as ranking safeguards. Promotions cannot override serious risk blocks.', false, 0)
on conflict (key) do update set
  description = excluded.description,
  updated_at = now();
