-- Sahibash V1 - Production Database Setup
-- Safe to paste into Supabase SQL Editor

begin;

create extension if not exists pgcrypto;

-- =========================================================
-- 1) Types / Enums
-- =========================================================
do $$
begin
  if not exists (select 1 from pg_type where typname = 'profile_role') then
    create type public.profile_role as enum ('user', 'admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'listing_status') then
    create type public.listing_status as enum ('pending', 'approved', 'rejected', 'sold', 'expired');
  end if;

  if not exists (select 1 from pg_type where typname = 'currency_code') then
    create type public.currency_code as enum ('AFN', 'USD');
  end if;

  if not exists (select 1 from pg_type where typname = 'report_status') then
    create type public.report_status as enum ('open', 'reviewed', 'dismissed', 'actioned');
  end if;
end $$;

-- =========================================================
-- 2) Core Tables
-- =========================================================

-- profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  city text,
  avatar_url text,
  role public.profile_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- categories
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_slug_format check (slug = lower(slug))
);

-- subcategories
create table if not exists public.subcategories (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name text not null,
  slug text not null,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subcategories_unique_name_per_category unique (category_id, name),
  constraint subcategories_unique_slug_per_category unique (category_id, slug),
  constraint subcategories_slug_format check (slug = lower(slug))
);

-- listings
create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete restrict,
  subcategory_id bigint not null references public.subcategories(id) on delete restrict,
  title text not null check (char_length(title) between 5 and 140),
  description text not null check (char_length(description) between 20 and 8000),
  price numeric(14,2) not null check (price >= 0),
  currency public.currency_code not null default 'AFN',
  city text not null,
  district text not null,
  address_optional text,
  contact_phone text not null,
  whatsapp_enabled boolean not null default false,
  status public.listing_status not null default 'pending',
  featured boolean not null default false,
  views_count bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  published_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  rejection_reason text
);

-- listing_images
create table if not exists public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  storage_path text not null unique,
  public_url text,
  is_primary boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- listing_attributes (flexible category-specific attributes)
create table if not exists public.listing_attributes (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  attribute_key text not null,
  attribute_value_text text,
  attribute_value_number numeric,
  attribute_value_boolean boolean,
  attribute_value_json jsonb,
  unit text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_attributes_unique_key_per_listing unique (listing_id, attribute_key),
  constraint listing_attributes_value_required check (
    attribute_value_text is not null
    or attribute_value_number is not null
    or attribute_value_boolean is not null
    or attribute_value_json is not null
  )
);

-- favorites
create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_unique_user_listing unique (user_id, listing_id)
);

-- reports
create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text,
  status public.report_status not null default 'open',
  admin_note text,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- listing_views
create table if not exists public.listing_views (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  viewer_user_id uuid references auth.users(id) on delete set null,
  viewer_ip inet,
  user_agent text,
  viewed_at timestamptz not null default now()
);

-- =========================================================
-- 3) Indexes
-- =========================================================
create index if not exists idx_subcategories_category_id on public.subcategories(category_id);

create index if not exists idx_listings_status_created_at on public.listings(status, created_at desc);
create index if not exists idx_listings_category_id on public.listings(category_id);
create index if not exists idx_listings_subcategory_id on public.listings(subcategory_id);
create index if not exists idx_listings_city on public.listings(city);
create index if not exists idx_listings_district on public.listings(district);
create index if not exists idx_listings_price on public.listings(price);
create index if not exists idx_listings_featured_status on public.listings(featured, status);
create index if not exists idx_listings_user_id on public.listings(user_id);
create index if not exists idx_listings_expires_at on public.listings(expires_at);

create index if not exists idx_listing_images_listing_id on public.listing_images(listing_id);
create index if not exists idx_listing_images_listing_sort on public.listing_images(listing_id, sort_order);
create unique index if not exists idx_listing_images_primary_once
  on public.listing_images(listing_id)
  where is_primary = true;

create index if not exists idx_listing_attributes_listing_key on public.listing_attributes(listing_id, attribute_key);
create index if not exists idx_listing_attributes_key on public.listing_attributes(attribute_key);
create index if not exists idx_listing_attributes_json on public.listing_attributes using gin(attribute_value_json);

create index if not exists idx_favorites_user_id on public.favorites(user_id);
create index if not exists idx_favorites_listing_id on public.favorites(listing_id);

create index if not exists idx_reports_listing_id on public.reports(listing_id);
create index if not exists idx_reports_reporter_user_id on public.reports(reporter_user_id);
create index if not exists idx_reports_status on public.reports(status);

create index if not exists idx_listing_views_listing_viewed_at on public.listing_views(listing_id, viewed_at desc);
create index if not exists idx_listing_views_viewer_user_id on public.listing_views(viewer_user_id);

-- =========================================================
-- 4) Functions + Triggers
-- =========================================================

-- Generic updated_at automation
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Ensure chosen subcategory belongs to selected category
create or replace function public.validate_listing_category_subcategory()
returns trigger
language plpgsql
as $$
declare
  subcat_category_id bigint;
begin
  select s.category_id into subcat_category_id
  from public.subcategories s
  where s.id = new.subcategory_id;

  if subcat_category_id is null then
    raise exception 'Invalid subcategory_id: %', new.subcategory_id;
  end if;

  if subcat_category_id <> new.category_id then
    raise exception 'subcategory_id % does not belong to category_id %', new.subcategory_id, new.category_id;
  end if;

  return new;
end;
$$;

-- Publish metadata automation on approval status changes
create or replace function public.set_listing_approval_fields()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.approved_at = coalesce(new.approved_at, now());
    new.published_at = coalesce(new.published_at, now());
  end if;

  if new.status = 'rejected' and old.status is distinct from 'rejected' then
    new.featured = false;
  end if;

  if new.status in ('pending', 'rejected') then
    new.approved_by = null;
    if new.status = 'pending' then
      new.approved_at = null;
      new.published_at = null;
      new.rejection_reason = null;
    end if;
  end if;

  return new;
end;
$$;

-- Keep only one primary image per listing
create or replace function public.ensure_single_primary_image()
returns trigger
language plpgsql
as $$
begin
  if new.is_primary then
    update public.listing_images
      set is_primary = false
    where listing_id = new.listing_id
      and id <> coalesce(new.id, '00000000-0000-0000-0000-000000000000'::uuid)
      and is_primary = true;
  end if;
  return new;
end;
$$;

-- If listing has no primary image yet, first image becomes primary
create or replace function public.assign_first_primary_image()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.listing_images li
    where li.listing_id = new.listing_id
      and li.is_primary = true
  ) then
    update public.listing_images
    set is_primary = true
    where id = new.id;
  end if;
  return null;
end;
$$;

-- Increase listing.views_count on every listing_views insert
create or replace function public.increment_listing_view_count()
returns trigger
language plpgsql
as $$
begin
  update public.listings
    set views_count = views_count + 1
  where id = new.listing_id;
  return null;
end;
$$;

-- Auto-create profile after auth signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do nothing;
  return new;
end;
$$;

-- Admin helper
create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$$;

-- Trigger bindings

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists trg_subcategories_updated_at on public.subcategories;
create trigger trg_subcategories_updated_at
before update on public.subcategories
for each row execute function public.set_updated_at();

drop trigger if exists trg_listings_updated_at on public.listings;
create trigger trg_listings_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

drop trigger if exists trg_listings_validate_category_subcategory on public.listings;
create trigger trg_listings_validate_category_subcategory
before insert or update of category_id, subcategory_id on public.listings
for each row execute function public.validate_listing_category_subcategory();

drop trigger if exists trg_listings_approval_fields on public.listings;
create trigger trg_listings_approval_fields
before update of status on public.listings
for each row execute function public.set_listing_approval_fields();

drop trigger if exists trg_listing_images_updated_at on public.listing_images;
create trigger trg_listing_images_updated_at
before update on public.listing_images
for each row execute function public.set_updated_at();

drop trigger if exists trg_listing_images_single_primary on public.listing_images;
create trigger trg_listing_images_single_primary
before insert or update of is_primary on public.listing_images
for each row execute function public.ensure_single_primary_image();

drop trigger if exists trg_listing_images_assign_first_primary on public.listing_images;
create trigger trg_listing_images_assign_first_primary
after insert on public.listing_images
for each row execute function public.assign_first_primary_image();

drop trigger if exists trg_listing_attributes_updated_at on public.listing_attributes;
create trigger trg_listing_attributes_updated_at
before update on public.listing_attributes
for each row execute function public.set_updated_at();

drop trigger if exists trg_reports_updated_at on public.reports;
create trigger trg_reports_updated_at
before update on public.reports
for each row execute function public.set_updated_at();

drop trigger if exists trg_listing_views_increment on public.listing_views;
create trigger trg_listing_views_increment
after insert on public.listing_views
for each row execute function public.increment_listing_view_count();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- 5) RLS + Policies
-- =========================================================

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.subcategories enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.listing_attributes enable row level security;
alter table public.favorites enable row level security;
alter table public.reports enable row level security;
alter table public.listing_views enable row level security;

-- profiles

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin
on public.profiles
for select
using (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin
on public.profiles
for update
using (auth.uid() = id or public.is_admin(auth.uid()))
with check (auth.uid() = id or public.is_admin(auth.uid()));

-- categories

drop policy if exists categories_public_select_active on public.categories;
create policy categories_public_select_active
on public.categories
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists categories_admin_insert on public.categories;
create policy categories_admin_insert
on public.categories
for insert
with check (public.is_admin(auth.uid()));

drop policy if exists categories_admin_update on public.categories;
create policy categories_admin_update
on public.categories
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists categories_admin_delete on public.categories;
create policy categories_admin_delete
on public.categories
for delete
using (public.is_admin(auth.uid()));

-- subcategories

drop policy if exists subcategories_public_select_active on public.subcategories;
create policy subcategories_public_select_active
on public.subcategories
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists subcategories_admin_insert on public.subcategories;
create policy subcategories_admin_insert
on public.subcategories
for insert
with check (public.is_admin(auth.uid()));

drop policy if exists subcategories_admin_update on public.subcategories;
create policy subcategories_admin_update
on public.subcategories
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists subcategories_admin_delete on public.subcategories;
create policy subcategories_admin_delete
on public.subcategories
for delete
using (public.is_admin(auth.uid()));

-- listings

drop policy if exists listings_select_public_or_owner_or_admin on public.listings;
create policy listings_select_public_or_owner_or_admin
on public.listings
for select
using (
  status = 'approved'
  or user_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists listings_insert_owner_only on public.listings;
create policy listings_insert_owner_only
on public.listings
for insert
to authenticated
with check (
  user_id = auth.uid()
  and status = 'pending'
  and featured = false
  and approved_by is null
  and approved_at is null
);

drop policy if exists listings_update_owner_limited_or_admin on public.listings;
create policy listings_update_owner_limited_or_admin
on public.listings
for update
using (user_id = auth.uid() or public.is_admin(auth.uid()))
with check (
  public.is_admin(auth.uid())
  or (
    user_id = auth.uid()
    and featured = false
    and approved_by is null
    and approved_at is null
    and status in ('pending', 'rejected', 'sold', 'expired')
  )
);

drop policy if exists listings_delete_owner_or_admin on public.listings;
create policy listings_delete_owner_or_admin
on public.listings
for delete
using (user_id = auth.uid() or public.is_admin(auth.uid()));

-- listing_images

drop policy if exists listing_images_select_with_visible_listing on public.listing_images;
create policy listing_images_select_with_visible_listing
on public.listing_images
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (
        l.status = 'approved'
        or l.user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists listing_images_insert_owner_or_admin on public.listing_images;
create policy listing_images_insert_owner_or_admin
on public.listing_images
for insert
to authenticated
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_images_update_owner_or_admin on public.listing_images;
create policy listing_images_update_owner_or_admin
on public.listing_images
for update
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_images_delete_owner_or_admin on public.listing_images;
create policy listing_images_delete_owner_or_admin
on public.listing_images
for delete
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

-- listing_attributes

drop policy if exists listing_attributes_select_with_visible_listing on public.listing_attributes;
create policy listing_attributes_select_with_visible_listing
on public.listing_attributes
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (
        l.status = 'approved'
        or l.user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists listing_attributes_insert_owner_or_admin on public.listing_attributes;
create policy listing_attributes_insert_owner_or_admin
on public.listing_attributes
for insert
to authenticated
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_attributes_update_owner_or_admin on public.listing_attributes;
create policy listing_attributes_update_owner_or_admin
on public.listing_attributes
for update
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_attributes_delete_owner_or_admin on public.listing_attributes;
create policy listing_attributes_delete_owner_or_admin
on public.listing_attributes
for delete
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

-- favorites

drop policy if exists favorites_select_own on public.favorites;
create policy favorites_select_own
on public.favorites
for select
using (user_id = auth.uid());

drop policy if exists favorites_insert_own on public.favorites;
create policy favorites_insert_own
on public.favorites
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists favorites_delete_own on public.favorites;
create policy favorites_delete_own
on public.favorites
for delete
using (user_id = auth.uid() or public.is_admin(auth.uid()));

-- reports

drop policy if exists reports_insert_reporter_only on public.reports;
create policy reports_insert_reporter_only
on public.reports
for insert
to authenticated
with check (reporter_user_id = auth.uid());

drop policy if exists reports_select_own_or_admin on public.reports;
create policy reports_select_own_or_admin
on public.reports
for select
using (reporter_user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists reports_update_admin_only on public.reports;
create policy reports_update_admin_only
on public.reports
for update
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists reports_delete_admin_only on public.reports;
create policy reports_delete_admin_only
on public.reports
for delete
using (public.is_admin(auth.uid()));

-- listing_views

drop policy if exists listing_views_insert_anyone on public.listing_views;
create policy listing_views_insert_anyone
on public.listing_views
for insert
with check (true);

drop policy if exists listing_views_select_admin_only on public.listing_views;
create policy listing_views_select_admin_only
on public.listing_views
for select
using (public.is_admin(auth.uid()));

-- =========================================================
-- 6) Storage Bucket + Storage Policies
-- =========================================================

insert into storage.buckets (id, name, public)
values ('listing-images', 'listing-images', true)
on conflict (id) do nothing;

drop policy if exists listing_images_public_read_storage on storage.objects;
create policy listing_images_public_read_storage
on storage.objects
for select
using (bucket_id = 'listing-images');

drop policy if exists listing_images_upload_owner_or_admin on storage.objects;
create policy listing_images_upload_owner_or_admin
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
);

drop policy if exists listing_images_update_owner_or_admin on storage.objects;
create policy listing_images_update_owner_or_admin
on storage.objects
for update
to authenticated
using (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
)
with check (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
);

drop policy if exists listing_images_delete_owner_or_admin on storage.objects;
create policy listing_images_delete_owner_or_admin
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
);

-- =========================================================
-- 7) Seed Data (Categories + Subcategories)
-- =========================================================

insert into public.categories (name, slug, display_order, is_active)
values
  ('Vehicles', 'vehicles', 1, true),
  ('Real Estate', 'real-estate', 2, true),
  ('Phones & Electronics', 'phones-electronics', 3, true),
  ('Second-Hand Items', 'second-hand-items', 4, true)
on conflict (slug) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = now();

-- Vehicles
insert into public.subcategories (category_id, name, slug, display_order, is_active)
select c.id, v.name, v.slug, v.display_order, true
from public.categories c
cross join (
  values
    ('Cars', 'cars', 1),
    ('Motorcycles', 'motorcycles', 2),
    ('Trucks', 'trucks', 3),
    ('Auto Parts', 'auto-parts', 4)
) as v(name, slug, display_order)
where c.slug = 'vehicles'
on conflict (category_id, slug) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

-- Real Estate
insert into public.subcategories (category_id, name, slug, display_order, is_active)
select c.id, v.name, v.slug, v.display_order, true
from public.categories c
cross join (
  values
    ('House for Sale', 'house-for-sale', 1),
    ('House for Rent', 'house-for-rent', 2),
    ('Apartment for Sale', 'apartment-for-sale', 3),
    ('Apartment for Rent', 'apartment-for-rent', 4),
    ('Land', 'land', 5),
    ('Shop/Office', 'shop-office', 6)
) as v(name, slug, display_order)
where c.slug = 'real-estate'
on conflict (category_id, slug) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

-- Phones & Electronics
insert into public.subcategories (category_id, name, slug, display_order, is_active)
select c.id, v.name, v.slug, v.display_order, true
from public.categories c
cross join (
  values
    ('Mobile Phones', 'mobile-phones', 1),
    ('Laptops', 'laptops', 2),
    ('Tablets', 'tablets', 3),
    ('TVs', 'tvs', 4),
    ('Cameras', 'cameras', 5),
    ('Accessories', 'accessories', 6)
) as v(name, slug, display_order)
where c.slug = 'phones-electronics'
on conflict (category_id, slug) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

-- Second-Hand Items
insert into public.subcategories (category_id, name, slug, display_order, is_active)
select c.id, v.name, v.slug, v.display_order, true
from public.categories c
cross join (
  values
    ('Furniture', 'furniture', 1),
    ('Home Appliances', 'home-appliances', 2),
    ('Clothing', 'clothing', 3),
    ('Books', 'books', 4),
    ('Tools', 'tools', 5),
    ('Other', 'other', 6)
) as v(name, slug, display_order)
where c.slug = 'second-hand-items'
on conflict (category_id, slug) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

commit;
