-- Step 1: Safe multi-source inventory and provenance foundation.
-- Additive and production-safe: existing native listings are backfilled as
-- native/claimed records while bridge inventory can remain unclaimed.

create type public.listing_source_type as enum (
  'native',
  'dealer_managed',
  'partner_feed',
  'seller_approved_import',
  'scout_assisted',
  'external_indexed',
  'migrated_legacy'
);

create type public.listing_ownership_status as enum (
  'unclaimed',
  'claim_pending',
  'claimed',
  'partner_managed',
  'staff_managed',
  'disputed',
  'removed',
  'opted_out'
);

create type public.listing_publication_status as enum (
  'draft',
  'pending_review',
  'published',
  'hidden',
  'archived',
  'removed'
);

create type public.listing_freshness_status as enum (
  'fresh',
  'aging',
  'stale',
  'source_missing',
  'seller_confirmed',
  'sold_confirmed',
  'expired'
);

create type public.listing_provenance_status as enum (
  'trusted',
  'authorized',
  'permission_pending',
  'low_confidence',
  'blocked',
  'opted_out'
);

create type public.listing_ingest_job_status as enum (
  'draft',
  'dry_run',
  'awaiting_approval',
  'approved',
  'processing',
  'completed',
  'failed',
  'cancelled'
);

create type public.listing_ingest_candidate_status as enum (
  'staged',
  'validated',
  'rejected',
  'duplicate',
  'needs_review',
  'publishable',
  'published',
  'dead_letter'
);

create type public.listing_claim_status as enum (
  'initiated',
  'challenge_sent',
  'verified',
  'converted',
  'failed',
  'locked',
  'disputed',
  'cancelled'
);

create type public.listing_duplicate_confidence as enum (
  'exact',
  'high_review',
  'medium_possible',
  'low'
);

create type public.listing_contact_event_type as enum (
  'phone_reveal',
  'call_click',
  'whatsapp_click',
  'owner_claim_click',
  'remove_request_click',
  'report_unavailable',
  'report_wrong_info',
  'report_scam'
);

create table public.seller_entities (
  id uuid primary key default gen_random_uuid(),
  linked_user_id uuid references auth.users(id) on delete set null,
  display_name text,
  normalized_phone text,
  phone_hint text,
  original_phone text,
  contact_hash text,
  preferred_locale public.language_code,
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'otp_verified', 'partner_verified', 'staff_verified', 'disputed', 'blocked')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint seller_entities_contact_identity unique nulls not distinct (contact_hash)
);

create table public.listing_sources (
  id uuid primary key default gen_random_uuid(),
  source_type public.listing_source_type not null,
  name text not null,
  slug text not null unique,
  partner_id text,
  platform text,
  permission_basis text not null,
  permission_record_id text,
  ingest_method text not null default 'manual'
    check (ingest_method in ('csv', 'xlsx', 'api', 'webhook', 'manual', 'scout_assisted')),
  status text not null default 'disabled'
    check (status in ('disabled', 'dry_run', 'active', 'paused', 'blocked')),
  quota_per_day int not null default 1000 check (quota_per_day >= 0),
  circuit_breaker_error_rate numeric(5,2) not null default 0.20 check (circuit_breaker_error_rate >= 0 and circuit_breaker_error_rate <= 1),
  last_successful_sync_at timestamptz,
  next_run_at timestamptz,
  kill_switch_enabled boolean not null default true,
  config jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.listing_freshness_policies (
  id bigint generated by default as identity primary key,
  source_type public.listing_source_type not null,
  category_node_id bigint references public.category_nodes(id) on delete cascade,
  aging_after_days int not null default 10 check (aging_after_days >= 0),
  stale_after_days int not null default 21 check (stale_after_days >= 0),
  expire_after_days int not null default 30 check (expire_after_days >= 1),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_freshness_policy_unique unique nulls not distinct (source_type, category_node_id),
  constraint listing_freshness_policy_order check (aging_after_days <= stale_after_days and stale_after_days <= expire_after_days)
);

create table public.listing_ingest_jobs (
  id uuid primary key default gen_random_uuid(),
  source_id uuid references public.listing_sources(id) on delete set null,
  source_type public.listing_source_type not null,
  source_version text,
  idempotency_key text not null,
  checksum text,
  status public.listing_ingest_job_status not null default 'draft',
  dry_run boolean not null default true,
  total_rows int not null default 0 check (total_rows >= 0),
  accepted_rows int not null default 0 check (accepted_rows >= 0),
  rejected_rows int not null default 0 check (rejected_rows >= 0),
  duplicate_rows int not null default 0 check (duplicate_rows >= 0),
  error_rows int not null default 0 check (error_rows >= 0),
  retry_count int not null default 0 check (retry_count >= 0),
  error_summary text,
  started_at timestamptz,
  completed_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_ingest_jobs_idempotency unique (source_type, idempotency_key)
);

create table public.listing_ingest_candidates (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.listing_ingest_jobs(id) on delete cascade,
  source_id uuid references public.listing_sources(id) on delete set null,
  row_number int not null check (row_number > 0),
  source_item_id text,
  idempotency_key text not null,
  status public.listing_ingest_candidate_status not null default 'staged',
  raw_payload jsonb not null default '{}'::jsonb,
  normalized_payload jsonb not null default '{}'::jsonb,
  validation_errors jsonb not null default '[]'::jsonb,
  duplicate_group_id uuid,
  candidate_listing_id uuid references public.listings(id) on delete set null,
  normalized_phone text,
  contact_hash text,
  normalized_title text,
  normalized_location text,
  normalized_price_afn numeric(14,2),
  category_node_id bigint references public.category_nodes(id) on delete set null,
  retry_count int not null default 0 check (retry_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_ingest_candidates_idempotency unique (job_id, idempotency_key)
);

create table public.listing_source_observations (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  source_id uuid references public.listing_sources(id) on delete set null,
  source_type public.listing_source_type not null,
  source_platform text,
  source_account_id text,
  source_item_id text,
  source_url text,
  import_job_id uuid references public.listing_ingest_jobs(id) on delete set null,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  source_posted_at timestamptz,
  permission_basis text,
  permission_record_id text,
  consented_at timestamptz,
  ingest_actor uuid references auth.users(id) on delete set null,
  ingest_version text,
  raw_payload_ref text,
  normalized_payload jsonb not null default '{}'::jsonb,
  provenance_confidence numeric(5,4) not null default 0.5 check (provenance_confidence >= 0 and provenance_confidence <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_source_observations_source_item unique nulls not distinct (source_id, source_item_id)
);

create table public.external_import_opt_outs (
  id uuid primary key default gen_random_uuid(),
  source_id uuid references public.listing_sources(id) on delete set null,
  source_type public.listing_source_type,
  contact_hash text,
  normalized_phone text,
  source_platform text,
  source_account_id text,
  reason text,
  verified_by uuid references auth.users(id) on delete set null,
  verified_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint external_import_opt_out_identity_required check (
    contact_hash is not null or normalized_phone is not null or source_account_id is not null
  )
);

create table public.listing_claims (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  seller_entity_id uuid references public.seller_entities(id) on delete set null,
  claimant_user_id uuid references auth.users(id) on delete set null,
  status public.listing_claim_status not null default 'initiated',
  masked_contact_hint text,
  challenge_channel text check (challenge_channel in ('sms', 'whatsapp', 'partner', 'staff_review')),
  challenge_expires_at timestamptz,
  attempt_count int not null default 0 check (attempt_count >= 0),
  lock_until timestamptz,
  risk_score numeric(5,4) not null default 0 check (risk_score >= 0 and risk_score <= 1),
  evidence jsonb not null default '{}'::jsonb,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.listing_duplicate_groups (
  id uuid primary key default gen_random_uuid(),
  canonical_listing_id uuid references public.listings(id) on delete set null,
  confidence public.listing_duplicate_confidence not null default 'medium_possible',
  score numeric(5,4) not null default 0 check (score >= 0 and score <= 1),
  evidence jsonb not null default '{}'::jsonb,
  status text not null default 'open' check (status in ('open', 'merged', 'dismissed', 'needs_review')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.listing_ingest_candidates
  add constraint listing_ingest_candidates_duplicate_group_fkey
  foreign key (duplicate_group_id) references public.listing_duplicate_groups(id) on delete set null;

create table public.listing_duplicate_group_members (
  group_id uuid not null references public.listing_duplicate_groups(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  role text not null default 'duplicate' check (role in ('canonical', 'duplicate', 'candidate')),
  merge_confidence numeric(5,4) not null default 0 check (merge_confidence >= 0 and merge_confidence <= 1),
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  primary key (group_id, listing_id)
);

create table public.listing_provenance_events (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete set null,
  source_observation_id uuid references public.listing_source_observations(id) on delete set null,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  source_type public.listing_source_type,
  before_state jsonb not null default '{}'::jsonb,
  after_state jsonb not null default '{}'::jsonb,
  reason text,
  job_id uuid references public.listing_ingest_jobs(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.listing_quality_signals (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  signal_type text not null,
  score numeric(5,4) not null check (score >= 0 and score <= 1),
  confidence numeric(5,4) not null default 0.5 check (confidence >= 0 and confidence <= 1),
  source text not null default 'system',
  evidence jsonb not null default '{}'::jsonb,
  expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.listing_contact_events (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  event_type public.listing_contact_event_type not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  session_id text,
  source_type public.listing_source_type,
  locale public.language_code,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.listings
  alter column user_id drop not null,
  add column if not exists seller_entity_id uuid references public.seller_entities(id) on delete set null,
  add column if not exists source_type public.listing_source_type not null default 'native',
  add column if not exists ownership_status public.listing_ownership_status not null default 'claimed',
  add column if not exists publication_status public.listing_publication_status not null default 'pending_review',
  add column if not exists freshness_status public.listing_freshness_status not null default 'seller_confirmed',
  add column if not exists provenance_status public.listing_provenance_status not null default 'trusted',
  add column if not exists source_platform text,
  add column if not exists source_item_id text,
  add column if not exists source_url text,
  add column if not exists source_first_seen_at timestamptz,
  add column if not exists source_last_seen_at timestamptz,
  add column if not exists source_posted_at timestamptz,
  add column if not exists permission_basis text,
  add column if not exists permission_record_id text,
  add column if not exists source_consent_at timestamptz,
  add column if not exists provenance_confidence numeric(5,4) not null default 1 check (provenance_confidence >= 0 and provenance_confidence <= 1),
  add column if not exists allow_contact_display boolean not null default true,
  add column if not exists noindex_external boolean not null default false,
  add column if not exists source_payload_hash text,
  add column if not exists canonical_duplicate_group_id uuid references public.listing_duplicate_groups(id) on delete set null,
  add column if not exists removed_public_at timestamptz;

update public.listings
set
  source_type = coalesce(source_type, 'native'::public.listing_source_type),
  ownership_status = coalesce(ownership_status, 'claimed'::public.listing_ownership_status),
  freshness_status = case
    when status = 'sold' then 'sold_confirmed'::public.listing_freshness_status
    when status = 'expired' then 'expired'::public.listing_freshness_status
    else coalesce(freshness_status, 'seller_confirmed'::public.listing_freshness_status)
  end,
  publication_status = case
    when status = 'approved' then 'published'::public.listing_publication_status
    when status = 'pending' then 'pending_review'::public.listing_publication_status
    when status = 'rejected' then 'hidden'::public.listing_publication_status
    when status in ('sold', 'expired') then 'archived'::public.listing_publication_status
    else coalesce(publication_status, 'pending_review'::public.listing_publication_status)
  end,
  provenance_status = coalesce(provenance_status, 'trusted'::public.listing_provenance_status),
  source_first_seen_at = coalesce(source_first_seen_at, created_at),
  source_last_seen_at = coalesce(source_last_seen_at, updated_at),
  permission_basis = coalesce(permission_basis, 'direct_user_submission'),
  source_consent_at = coalesce(source_consent_at, created_at),
  provenance_confidence = coalesce(provenance_confidence, 1),
  noindex_external = case when source_type in ('native', 'migrated_legacy') then false else true end;

alter table public.listings
  add constraint listings_bridge_owner_required check (
    (source_type = 'native' and user_id is not null)
    or (source_type <> 'native' and (seller_entity_id is not null or ownership_status in ('unclaimed', 'partner_managed', 'staff_managed', 'opted_out', 'removed')))
  ),
  add constraint listings_external_no_fake_owner check (
    source_type = 'native' or ownership_status <> 'claimed' or user_id is not null
  );

create index idx_listings_bridge_discovery
  on public.listings(publication_status, freshness_status, source_type, created_at desc);
create index idx_listings_source_identity
  on public.listings(source_type, source_platform, source_item_id);
create index idx_listings_seller_entity
  on public.listings(seller_entity_id);
create index idx_listing_observations_listing
  on public.listing_source_observations(listing_id, last_seen_at desc);
create index idx_listing_observations_source
  on public.listing_source_observations(source_id, source_item_id);
create index idx_ingest_candidates_status
  on public.listing_ingest_candidates(job_id, status);
create index idx_external_opt_out_contact
  on public.external_import_opt_outs(contact_hash, normalized_phone);
create index idx_listing_claims_listing_status
  on public.listing_claims(listing_id, status, created_at desc);
create index idx_listing_contact_events_listing
  on public.listing_contact_events(listing_id, event_type, created_at desc);
create index idx_listing_quality_signals_listing
  on public.listing_quality_signals(listing_id, signal_type, created_at desc);

insert into public.listing_freshness_policies (source_type, aging_after_days, stale_after_days, expire_after_days)
values
  ('partner_feed', 10, 21, 30),
  ('dealer_managed', 14, 30, 45),
  ('seller_approved_import', 14, 30, 45),
  ('scout_assisted', 10, 21, 30),
  ('external_indexed', 7, 21, 30)
on conflict (source_type, category_node_id) do nothing;

create or replace function public.set_listing_bridge_publication_fields()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.status = 'approved' then
    new.publication_status := 'published'::public.listing_publication_status;
  elsif new.status = 'pending' then
    new.publication_status := 'pending_review'::public.listing_publication_status;
  elsif new.status = 'rejected' then
    new.publication_status := 'hidden'::public.listing_publication_status;
  elsif new.status in ('sold', 'expired') then
    new.publication_status := 'archived'::public.listing_publication_status;
  end if;

  if new.status = 'sold' then
    new.freshness_status := 'sold_confirmed'::public.listing_freshness_status;
  elsif new.status = 'expired' then
    new.freshness_status := 'expired'::public.listing_freshness_status;
  end if;

  if new.source_type <> 'native'::public.listing_source_type then
    new.noindex_external := coalesce(new.noindex_external, true);
  end if;

  return new;
end;
$$;

drop trigger if exists trg_set_listing_bridge_publication_fields on public.listings;
create trigger trg_set_listing_bridge_publication_fields
before insert or update of status, source_type on public.listings
for each row execute function public.set_listing_bridge_publication_fields();

create or replace function public.mask_afghanistan_phone(phone text)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when phone is null or length(regexp_replace(phone, '\D', '', 'g')) < 7 then null
    else left(regexp_replace(phone, '\D', '', 'g'), 4) || repeat('•', greatest(length(regexp_replace(phone, '\D', '', 'g')) - 6, 2)) || right(regexp_replace(phone, '\D', '', 'g'), 2)
  end;
$$;

create or replace function public.record_listing_provenance_event(
  p_listing_id uuid,
  p_event_type text,
  p_after_state jsonb default '{}'::jsonb,
  p_reason text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_event_id uuid;
begin
  insert into public.listing_provenance_events (
    listing_id,
    event_type,
    actor_user_id,
    after_state,
    reason
  )
  values (
    p_listing_id,
    p_event_type,
    (select auth.uid()),
    coalesce(p_after_state, '{}'::jsonb),
    p_reason
  )
  returning id into v_event_id;

  return v_event_id;
end;
$$;

revoke execute on function public.record_listing_provenance_event(uuid, text, jsonb, text) from public;
grant execute on function public.record_listing_provenance_event(uuid, text, jsonb, text) to authenticated, service_role;

alter table public.seller_entities enable row level security;
alter table public.listing_sources enable row level security;
alter table public.listing_freshness_policies enable row level security;
alter table public.listing_ingest_jobs enable row level security;
alter table public.listing_ingest_candidates enable row level security;
alter table public.listing_source_observations enable row level security;
alter table public.external_import_opt_outs enable row level security;
alter table public.listing_claims enable row level security;
alter table public.listing_duplicate_groups enable row level security;
alter table public.listing_duplicate_group_members enable row level security;
alter table public.listing_provenance_events enable row level security;
alter table public.listing_quality_signals enable row level security;
alter table public.listing_contact_events enable row level security;

create policy seller_entities_admin_manage on public.seller_entities for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'users.verify')))
with check ((select public.has_admin_permission((select auth.uid()), 'users.verify')));

create policy seller_entities_linked_user_read on public.seller_entities for select to authenticated
using (linked_user_id = (select auth.uid()) or (select public.has_admin_permission((select auth.uid()), 'users.verify')));

create policy listing_sources_admin_manage on public.listing_sources for all to authenticated
using ((select public.is_super_administrator((select auth.uid()))))
with check ((select public.is_super_administrator((select auth.uid()))));

create policy listing_freshness_policies_admin_manage on public.listing_freshness_policies for all to authenticated
using ((select public.is_super_administrator((select auth.uid()))))
with check ((select public.is_super_administrator((select auth.uid()))));

create policy listing_ingest_jobs_admin_read on public.listing_ingest_jobs for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.view')));
create policy listing_ingest_jobs_super_admin_manage on public.listing_ingest_jobs for all to authenticated
using ((select public.is_super_administrator((select auth.uid()))))
with check ((select public.is_super_administrator((select auth.uid()))));

create policy listing_ingest_candidates_admin_read on public.listing_ingest_candidates for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.view')));
create policy listing_ingest_candidates_super_admin_manage on public.listing_ingest_candidates for all to authenticated
using ((select public.is_super_administrator((select auth.uid()))))
with check ((select public.is_super_administrator((select auth.uid()))));

create policy listing_source_observations_admin_read on public.listing_source_observations for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.view')));
create policy listing_source_observations_super_admin_manage on public.listing_source_observations for all to authenticated
using ((select public.is_super_administrator((select auth.uid()))))
with check ((select public.is_super_administrator((select auth.uid()))));

create policy external_import_opt_outs_admin_manage on public.external_import_opt_outs for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy listing_claims_admin_read on public.listing_claims for select to authenticated
using (
  claimant_user_id = (select auth.uid())
  or (select public.has_admin_permission((select auth.uid()), 'listings.view'))
);
create policy listing_claims_user_insert on public.listing_claims for insert to authenticated
with check (claimant_user_id = (select auth.uid()));
create policy listing_claims_admin_manage on public.listing_claims for update to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy listing_duplicate_groups_admin_manage on public.listing_duplicate_groups for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));
create policy listing_duplicate_members_admin_manage on public.listing_duplicate_group_members for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy listing_provenance_events_admin_read on public.listing_provenance_events for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'audit_logs.view')));
create policy listing_provenance_events_system_insert on public.listing_provenance_events for insert to authenticated
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')) or actor_user_id = (select auth.uid()));

create policy listing_quality_signals_admin_manage on public.listing_quality_signals for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy listing_contact_events_public_insert on public.listing_contact_events for insert to anon, authenticated
with check (true);
create policy listing_contact_events_admin_read on public.listing_contact_events for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.view')));

grant select, insert on table public.listing_contact_events to anon, authenticated;
grant select on table public.listing_contact_events to authenticated;
grant select on table public.listing_sources to authenticated;
grant select on table public.listing_freshness_policies to authenticated;
grant select, insert on table public.listing_claims to authenticated;
