-- Step 2: Seller acquisition and buyer demand foundation.
-- Additive, privacy-first, and built on Step 1 provenance controls.

do $$ begin
  create type public.wanted_request_status as enum ('active','paused','fulfilled','expired','deleted');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.wanted_request_urgency as enum ('flexible','soon','urgent');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.wanted_match_status as enum ('candidate','notified','dismissed','accepted','not_relevant','throttled');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.scout_submission_status as enum ('draft','submitted','needs_review','approved','rejected','published','claimed','reward_pending','reward_verified','reward_blocked');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.organization_member_role as enum ('owner','admin','member');
exception when duplicate_object then null;
end $$;

create table if not exists public.wanted_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  locale public.language_code not null default 'fa',
  status public.wanted_request_status not null default 'active',
  urgency public.wanted_request_urgency not null default 'flexible',
  title text not null check (char_length(title) between 2 and 120),
  query_text text,
  category_id bigint references public.categories(id) on delete set null,
  category_node_id bigint references public.category_nodes(id) on delete set null,
  category_path text,
  province text,
  city text,
  district text,
  min_price numeric(14,2) check (min_price is null or min_price >= 0),
  max_price numeric(14,2) check (max_price is null or max_price >= 0),
  condition text,
  attributes jsonb not null default '{}'::jsonb,
  notification_channels text[] not null default array['in_app']::text[],
  notification_paused_at timestamptz,
  expires_at timestamptz not null default (now() + interval '90 days'),
  last_matched_at timestamptz,
  match_count int not null default 0 check (match_count >= 0),
  not_relevant_count int not null default 0 check (not_relevant_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wanted_requests_price_order check (min_price is null or max_price is null or min_price <= max_price),
  constraint wanted_requests_channels_safe check (notification_channels <@ array['in_app','email','whatsapp']::text[])
);

create table if not exists public.wanted_request_matches (
  id uuid primary key default gen_random_uuid(),
  wanted_request_id uuid not null references public.wanted_requests(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  status public.wanted_match_status not null default 'candidate',
  score numeric(5,4) not null check (score >= 0 and score <= 1),
  match_reasons jsonb not null default '{}'::jsonb,
  notified_at timestamptz,
  feedback text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint wanted_request_matches_unique unique (wanted_request_id, listing_id)
);

create table if not exists public.demand_signals (
  id bigint generated by default as identity primary key,
  signal_type text not null check (signal_type in ('search','zero_result_search','saved_search','wanted_request','favorite','detail_view','contact_action')),
  actor_user_id uuid references auth.users(id) on delete set null,
  locale public.language_code,
  query_text text,
  category_id bigint references public.categories(id) on delete set null,
  category_node_id bigint references public.category_nodes(id) on delete set null,
  category_path text,
  province text,
  city text,
  district text,
  price_band text,
  attributes jsonb not null default '{}'::jsonb,
  weight numeric(6,3) not null default 1 check (weight > 0 and weight <= 20),
  session_hash text,
  source text not null default 'web',
  created_at timestamptz not null default now()
);

create table if not exists public.seller_lead_summaries (
  listing_id uuid primary key references public.listings(id) on delete cascade,
  seller_entity_id uuid references public.seller_entities(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  impression_count int not null default 0 check (impression_count >= 0),
  detail_view_count int not null default 0 check (detail_view_count >= 0),
  phone_reveal_count int not null default 0 check (phone_reveal_count >= 0),
  call_click_count int not null default 0 check (call_click_count >= 0),
  whatsapp_click_count int not null default 0 check (whatsapp_click_count >= 0),
  save_count int not null default 0 check (save_count >= 0),
  bot_suspect_count int not null default 0 check (bot_suspect_count >= 0),
  last_lead_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 160),
  slug text not null unique,
  organization_type text not null check (organization_type in ('car_dealer','real_estate_agency','mobile_shop','general_shop','partner','other')),
  owner_user_id uuid references auth.users(id) on delete set null,
  contact_policy text not null default 'owner_approved' check (contact_policy in ('owner_approved','business_public','staff_review')),
  shop_description jsonb not null default '{}'::jsonb,
  public_shop_enabled boolean not null default false,
  qr_code_path text,
  status text not null default 'pending' check (status in ('pending','active','paused','suspended')),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role public.organization_member_role not null default 'member',
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create table if not exists public.scout_submissions (
  id uuid primary key default gen_random_uuid(),
  scout_user_id uuid not null references auth.users(id) on delete cascade,
  seller_entity_id uuid references public.seller_entities(id) on delete set null,
  candidate_id uuid references public.listing_ingest_candidates(id) on delete set null,
  listing_id uuid references public.listings(id) on delete set null,
  status public.scout_submission_status not null default 'submitted',
  permission_channel text not null check (permission_channel in ('in_person','phone','whatsapp','partner','written','other')),
  permission_summary text not null check (char_length(permission_summary) between 8 and 1000),
  proof_ref text,
  quality_score numeric(5,4) not null default 0 check (quality_score >= 0 and quality_score <= 1),
  pending_points int not null default 0 check (pending_points >= 0),
  verified_points int not null default 0 check (verified_points >= 0),
  fraud_flags jsonb not null default '{}'::jsonb,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_share_outputs (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  channel text not null check (channel in ('whatsapp','telegram','facebook','copy_link','generic')),
  locale public.language_code not null default 'fa',
  share_url text not null,
  share_text text not null,
  utm_source text,
  created_at timestamptz not null default now()
);

create index if not exists idx_wanted_requests_user_status on public.wanted_requests(user_id, status, updated_at desc);
create index if not exists idx_wanted_requests_market on public.wanted_requests(status, category_node_id, province, created_at desc);
create index if not exists idx_wanted_matches_listing on public.wanted_request_matches(listing_id, status, created_at desc);
create index if not exists idx_demand_signals_market on public.demand_signals(signal_type, category_node_id, province, created_at desc);
create index if not exists idx_seller_lead_summaries_seller on public.seller_lead_summaries(seller_entity_id, updated_at desc);
create index if not exists idx_organizations_owner on public.organizations(owner_user_id, status);
create index if not exists idx_scout_submissions_scout on public.scout_submissions(scout_user_id, status, created_at desc);

alter table public.wanted_requests enable row level security;
alter table public.wanted_request_matches enable row level security;
alter table public.demand_signals enable row level security;
alter table public.seller_lead_summaries enable row level security;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.scout_submissions enable row level security;
alter table public.listing_share_outputs enable row level security;

create policy wanted_requests_owner_manage on public.wanted_requests for all to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));
create policy wanted_requests_admin_read on public.wanted_requests for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.view')));

create policy wanted_matches_owner_read on public.wanted_request_matches for select to authenticated
using (exists (select 1 from public.wanted_requests wr where wr.id = wanted_request_id and wr.user_id = (select auth.uid())));
create policy wanted_matches_admin_manage on public.wanted_request_matches for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy demand_signals_insert on public.demand_signals for insert to anon, authenticated with check (true);
create policy demand_signals_admin_read on public.demand_signals for select to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'search.view')));

create policy seller_lead_owner_read on public.seller_lead_summaries for select to authenticated
using (user_id = (select auth.uid()) or (select public.has_admin_permission((select auth.uid()), 'listings.view')));
create policy seller_lead_admin_manage on public.seller_lead_summaries for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy organizations_public_active_read on public.organizations for select to anon, authenticated
using (public_shop_enabled = true and status = 'active');
create policy organizations_owner_read on public.organizations for select to authenticated
using (owner_user_id = (select auth.uid()) or exists (select 1 from public.organization_members m where m.organization_id = id and m.user_id = (select auth.uid())) or (select public.has_admin_permission((select auth.uid()), 'users.verify')));
create policy organizations_admin_manage on public.organizations for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'users.verify')))
with check ((select public.has_admin_permission((select auth.uid()), 'users.verify')));

create policy organization_members_self_read on public.organization_members for select to authenticated
using (user_id = (select auth.uid()) or (select public.has_admin_permission((select auth.uid()), 'users.verify')));
create policy organization_members_admin_manage on public.organization_members for all to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'users.verify')))
with check ((select public.has_admin_permission((select auth.uid()), 'users.verify')));

create policy scout_submissions_owner_insert on public.scout_submissions for insert to authenticated
with check (scout_user_id = (select auth.uid()));
create policy scout_submissions_owner_read on public.scout_submissions for select to authenticated
using (scout_user_id = (select auth.uid()) or (select public.has_admin_permission((select auth.uid()), 'listings.moderate')));
create policy scout_submissions_admin_update on public.scout_submissions for update to authenticated
using ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')))
with check ((select public.has_admin_permission((select auth.uid()), 'listings.moderate')));

create policy listing_share_outputs_owner_insert on public.listing_share_outputs for insert to authenticated
with check (user_id = (select auth.uid()));
create policy listing_share_outputs_owner_read on public.listing_share_outputs for select to authenticated
using (user_id = (select auth.uid()) or (select public.has_admin_permission((select auth.uid()), 'search.view')));

grant select, insert, update, delete on table public.wanted_requests to authenticated;
grant select on table public.wanted_request_matches to authenticated;
grant insert on table public.demand_signals to anon, authenticated;
grant select on table public.demand_signals to authenticated;
grant select on table public.seller_lead_summaries to authenticated;
grant select on table public.organizations to anon, authenticated;
grant select on table public.organization_members to authenticated;
grant select, insert, update on table public.scout_submissions to authenticated;
grant select, insert on table public.listing_share_outputs to authenticated;

create or replace function public.record_demand_signal(
  p_signal_type text,
  p_locale text default null,
  p_query_text text default null,
  p_category_node_id bigint default null,
  p_category_path text default null,
  p_province text default null,
  p_district text default null,
  p_attributes jsonb default '{}'::jsonb,
  p_weight numeric default 1,
  p_source text default 'web'
)
returns bigint
language plpgsql
set search_path = ''
as $$
declare
  v_id bigint;
begin
  insert into public.demand_signals (
    signal_type, actor_user_id, locale, query_text, category_node_id, category_path,
    province, district, attributes, weight, source
  )
  values (
    p_signal_type,
    (select auth.uid()),
    case when p_locale in ('en','fa','ps') then p_locale::public.language_code else null end,
    nullif(left(coalesce(p_query_text, ''), 300), ''),
    p_category_node_id,
    nullif(left(coalesce(p_category_path, ''), 300), ''),
    nullif(left(coalesce(p_province, ''), 80), ''),
    nullif(left(coalesce(p_district, ''), 120), ''),
    coalesce(p_attributes, '{}'::jsonb),
    least(greatest(coalesce(p_weight, 1), 0.1), 20),
    nullif(left(coalesce(p_source, 'web'), 80), '')
  )
  returning id into v_id;
  return v_id;
end;
$$;

revoke execute on function public.record_demand_signal(text,text,text,bigint,text,text,text,jsonb,numeric,text) from public;
grant execute on function public.record_demand_signal(text,text,text,bigint,text,text,text,jsonb,numeric,text) to anon, authenticated, service_role;

create or replace view public.admin_supply_gap_cells
with (security_invoker = true)
as
select
  coalesce(category_path, 'uncategorized') as category_path,
  province,
  district,
  count(*) filter (where signal_type = 'search') as raw_searches,
  count(*) filter (where signal_type = 'zero_result_search') as zero_result_searches,
  count(*) filter (where signal_type = 'wanted_request') as wanted_requests,
  count(*) filter (where signal_type = 'contact_action') as contact_actions,
  sum(weight) as qualified_demand_score,
  case
    when count(*) >= 5 then round((sum(weight) + count(*) filter (where signal_type in ('wanted_request','contact_action')) * 2)::numeric, 2)
    else null
  end as privacy_safe_gap_score,
  max(created_at) as last_signal_at
from public.demand_signals
where created_at >= now() - interval '30 days'
group by coalesce(category_path, 'uncategorized'), province, district;

grant select on public.admin_supply_gap_cells to authenticated;

insert into public.feature_flags(key, description, enabled, rollout_percent)
values
  ('find_it_for_me', 'Show wanted-request capture after weak or zero search results', true, 100),
  ('seller_claim_value_preview', 'Show privacy-safe lead totals to sellers after claim verification', true, 100),
  ('step2_distribution_outputs', 'Enable share-ready localized listing outputs', true, 100)
on conflict (key) do update set description = excluded.description, enabled = excluded.enabled, rollout_percent = excluded.rollout_percent, updated_at = now();

