begin;

create table public.marketplace_events (
  id bigint generated by default as identity primary key,
  event_name text not null check (event_name in ('home_view','category_view','filter_apply','listing_view','post_start','post_step','post_complete','moderation_approved','moderation_rejected','listing_sold','seller_sale_source_confirmation')),
  actor_user_id uuid references auth.users(id) on delete set null,
  listing_id uuid references public.listings(id) on delete cascade,
  locale text not null check (locale in ('en','fa','ps')),
  source text not null default 'web' check (source ~ '^[a-z0-9_-]{1,64}$'),
  properties jsonb not null default '{}'::jsonb check (jsonb_typeof(properties)='object' and pg_column_size(properties) <= 4096),
  created_at timestamptz not null default now()
);
create index marketplace_events_name_created_idx on public.marketplace_events(event_name,created_at desc);
create index marketplace_events_listing_created_idx on public.marketplace_events(listing_id,created_at desc) where listing_id is not null;
create index marketplace_events_actor_created_idx on public.marketplace_events(actor_user_id,created_at desc) where actor_user_id is not null;
alter table public.marketplace_events enable row level security;
create policy marketplace_events_admin_read on public.marketplace_events for select to authenticated using ((select public.is_admin((select auth.uid()))));
revoke all on table public.marketplace_events from anon,authenticated;
grant select on table public.marketplace_events to authenticated;

create table public.listing_risk_signals (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  signal_type text not null check (signal_type in ('duplicate_content','repeated_phone','implausible_price','prohibited_term','external_contact_spam','rapid_posting','user_reports')),
  score smallint not null check (score between 1 and 100),
  evidence jsonb not null default '{}'::jsonb check (jsonb_typeof(evidence)='object' and pg_column_size(evidence) <= 4096),
  status text not null default 'open' check (status in ('open','reviewed','dismissed','confirmed')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  unique(listing_id,signal_type)
);
create index listing_risk_signals_queue_idx on public.listing_risk_signals(status,score desc,created_at);
alter table public.listing_risk_signals enable row level security;
create policy listing_risk_signals_admin_manage on public.listing_risk_signals for all to authenticated using ((select public.has_admin_permission((select auth.uid()),'listings.moderate'))) with check ((select public.has_admin_permission((select auth.uid()),'listings.moderate')));
revoke all on table public.listing_risk_signals from anon,authenticated;
grant select,update on table public.listing_risk_signals to authenticated;

create table public.listing_moderation_events (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  from_status public.listing_status not null,
  to_status public.listing_status not null,
  reason_code text not null check (reason_code ~ '^[a-z0-9_-]{2,64}$'),
  internal_note text check (char_length(internal_note) <= 2000),
  seller_explanation text check (char_length(seller_explanation) <= 2000),
  created_at timestamptz not null default now()
);
create index listing_moderation_events_listing_idx on public.listing_moderation_events(listing_id,created_at desc);
create index listing_moderation_events_sla_idx on public.listing_moderation_events(to_status,created_at desc);
create index listing_moderation_events_actor_idx on public.listing_moderation_events(actor_user_id);
alter table public.listing_moderation_events enable row level security;
create policy listing_moderation_events_admin_read on public.listing_moderation_events for select to authenticated using ((select public.has_admin_permission((select auth.uid()),'listings.view')));
revoke all on table public.listing_moderation_events from anon,authenticated;
grant select on table public.listing_moderation_events to authenticated;

create table public.feature_flags (
  key text primary key check (key ~ '^[a-z0-9_-]{2,64}$'),
  description text not null check (char_length(description) between 1 and 300),
  enabled boolean not null default false,
  rollout_percent smallint not null default 0 check (rollout_percent between 0 and 100),
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);
alter table public.feature_flags enable row level security;
create policy feature_flags_public_read on public.feature_flags for select to anon,authenticated using (true);
create policy feature_flags_admin_insert on public.feature_flags for insert to authenticated with check ((select public.has_admin_permission((select auth.uid()),'settings.update')));
create policy feature_flags_admin_update on public.feature_flags for update to authenticated using ((select public.has_admin_permission((select auth.uid()),'settings.update'))) with check ((select public.has_admin_permission((select auth.uid()),'settings.update')));
create policy feature_flags_admin_delete on public.feature_flags for delete to authenticated using ((select public.has_admin_permission((select auth.uid()),'settings.update')));
revoke all on table public.feature_flags from anon,authenticated;
grant select on table public.feature_flags to anon,authenticated;
grant insert,update,delete on table public.feature_flags to authenticated;
create index feature_flags_updated_by_idx on public.feature_flags(updated_by) where updated_by is not null;
insert into public.feature_flags(key,description,enabled,rollout_percent) values
('similar_listings','Category, location, and price-band recommendations',true,100),
('saved_search_notifications','Notifications for newly matching genuine listings',false,0),
('ranking_v2','Transparent quality and relevance ranking',false,0)
on conflict(key) do nothing;

create or replace function private.record_marketplace_event(p_event_name text,p_listing_id uuid,p_locale text,p_source text,p_properties jsonb)
returns boolean language plpgsql security definer set search_path=''
as $$ begin
  if p_event_name not in ('home_view','category_view','filter_apply','listing_view','post_start','post_step','post_complete','moderation_approved','moderation_rejected','listing_sold','seller_sale_source_confirmation')
    or p_locale not in ('en','fa','ps') or p_source !~ '^[a-z0-9_-]{1,64}$' or jsonb_typeof(p_properties) <> 'object' or pg_column_size(p_properties)>4096 then return false; end if;
  if p_listing_id is not null and not exists(select 1 from public.listings where id=p_listing_id) then return false; end if;
  insert into public.marketplace_events(event_name,actor_user_id,listing_id,locale,source,properties) values(p_event_name,(select auth.uid()),p_listing_id,p_locale,p_source,p_properties);
  return true;
end $$;
create function public.record_marketplace_event(p_event_name text,p_listing_id uuid default null,p_locale text default 'en',p_source text default 'web',p_properties jsonb default '{}'::jsonb)
returns boolean language sql security invoker set search_path='' as $$ select private.record_marketplace_event(p_event_name,p_listing_id,p_locale,p_source,p_properties); $$;
revoke all on function private.record_marketplace_event(text,uuid,text,text,jsonb) from public;
grant execute on function private.record_marketplace_event(text,uuid,text,text,jsonb) to anon,authenticated,service_role;
revoke all on function public.record_marketplace_event(text,uuid,text,text,jsonb) from public;
grant execute on function public.record_marketplace_event(text,uuid,text,text,jsonb) to anon,authenticated,service_role;

create or replace function private.moderate_listing(p_listing_id uuid,p_to_status public.listing_status,p_reason_code text,p_internal_note text default null,p_seller_explanation text default null)
returns boolean language plpgsql security definer set search_path=''
as $$ declare v_actor uuid := (select auth.uid()); v_from public.listing_status; begin
  if v_actor is null or not public.has_admin_permission(v_actor,'listings.moderate') then raise exception 'forbidden'; end if;
  select status into v_from from public.listings where id=p_listing_id for update;
  if v_from is null then return false; end if;
  if not ((v_from='pending' and p_to_status in ('approved','rejected')) or (v_from='rejected' and p_to_status='pending') or (v_from='approved' and p_to_status in ('sold','expired','rejected')) or (v_from='expired' and p_to_status='pending')) then raise exception 'invalid listing status transition'; end if;
  if p_reason_code !~ '^[a-z0-9_-]{2,64}$' or char_length(coalesce(p_internal_note,''))>2000 or char_length(coalesce(p_seller_explanation,''))>2000 then raise exception 'invalid moderation input'; end if;
  update public.listings set status=p_to_status,approved_by=case when p_to_status='approved' then v_actor else approved_by end,approval_rejected_reason=case when p_to_status='rejected' then p_seller_explanation else null end,updated_at=now() where id=p_listing_id;
  insert into public.listing_moderation_events(listing_id,actor_user_id,from_status,to_status,reason_code,internal_note,seller_explanation) values(p_listing_id,v_actor,v_from,p_to_status,p_reason_code,nullif(trim(p_internal_note),''),nullif(trim(p_seller_explanation),''));
  return true;
end $$;
create function public.moderate_listing(p_listing_id uuid,p_to_status public.listing_status,p_reason_code text,p_internal_note text default null,p_seller_explanation text default null)
returns boolean language sql security invoker set search_path='' as $$ select private.moderate_listing(p_listing_id,p_to_status,p_reason_code,p_internal_note,p_seller_explanation); $$;
revoke all on function private.moderate_listing(uuid,public.listing_status,text,text,text) from public;
grant execute on function private.moderate_listing(uuid,public.listing_status,text,text,text) to authenticated,service_role;
revoke all on function public.moderate_listing(uuid,public.listing_status,text,text,text) from public;
grant execute on function public.moderate_listing(uuid,public.listing_status,text,text,text) to authenticated,service_role;

grant all on table public.marketplace_events,public.listing_risk_signals,public.listing_moderation_events,public.feature_flags to service_role;
grant usage,select on all sequences in schema public to service_role;
commit;
