-- Sahibash V6: AI-assisted category detection + phone specs foundation

begin;

-- =========================================================
-- 1) Schema additions
-- =========================================================

create table if not exists public.product_specs (
  id bigint generated by default as identity primary key,
  category_node_id bigint not null references public.category_nodes(id) on delete cascade,
  brand text not null,
  model text not null,
  aliases text[] not null default '{}'::text[],
  specs jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  constraint product_specs_unique_node_brand_model unique (category_node_id, brand, model)
);

create table if not exists public.ai_detection_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  image_urls text[] not null default '{}'::text[],
  title text,
  description text,
  detected_labels jsonb not null default '[]'::jsonb,
  suggested_category_node_id bigint references public.category_nodes(id) on delete set null,
  suggested_specs jsonb not null default '{}'::jsonb,
  confidence numeric(5,4),
  created_at timestamptz not null default now()
);

create index if not exists idx_product_specs_category_node_id on public.product_specs(category_node_id);
create index if not exists idx_product_specs_brand_model on public.product_specs(brand, model);
create index if not exists idx_product_specs_aliases_gin on public.product_specs using gin(aliases);
create index if not exists idx_product_specs_specs_gin on public.product_specs using gin(specs);

create index if not exists idx_ai_detection_logs_user_id_created_at on public.ai_detection_logs(user_id, created_at desc);
create index if not exists idx_ai_detection_logs_suggested_category_node_id on public.ai_detection_logs(suggested_category_node_id);

alter table public.product_specs enable row level security;
alter table public.ai_detection_logs enable row level security;

drop policy if exists product_specs_public_read on public.product_specs;
create policy product_specs_public_read
on public.product_specs
for select
using (is_active = true);

drop policy if exists product_specs_admin_manage on public.product_specs;
create policy product_specs_admin_manage
on public.product_specs
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists ai_detection_logs_owner_insert on public.ai_detection_logs;
create policy ai_detection_logs_owner_insert
on public.ai_detection_logs
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists ai_detection_logs_owner_select on public.ai_detection_logs;
create policy ai_detection_logs_owner_select
on public.ai_detection_logs
for select
to authenticated
using (user_id = auth.uid() or public.is_admin(auth.uid()));

-- =========================================================
-- 2) Category tree extension for phone brands/models
-- =========================================================

with mobile_root as (
  select id, category_id, level, path
  from public.category_nodes
  where path = 'phones-electronics/mobile-phones'
  limit 1
)
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select
  root.category_id,
  root.id,
  b.name,
  b.slug,
  root.level + 1,
  root.path || '/' || b.slug,
  b.display_order,
  true
from mobile_root root
cross join (
  values
    ('Apple', 'apple', 1),
    ('Samsung', 'samsung', 2),
    ('Xiaomi', 'xiaomi', 3),
    ('Huawei', 'huawei', 4),
    ('Honor', 'honor', 5),
    ('Nokia', 'nokia', 6),
    ('Tecno', 'tecno', 7),
    ('Infinix', 'infinix', 8),
    ('Oppo', 'oppo', 9),
    ('Vivo', 'vivo', 10),
    ('Realme', 'realme', 11),
    ('LG', 'lg', 12),
    ('Sony', 'sony', 13),
    ('Motorola', 'motorola', 14),
    ('OnePlus', 'oneplus', 15),
    ('Itel', 'itel', 16),
    ('Other', 'other', 17)
) as b(name, slug, display_order)
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

with model_seed as (
  select * from (
    values
      -- Apple iPhone
      ('apple', 'iPhone 6', 'iphone-6', 1),
      ('apple', 'iPhone 6 Plus', 'iphone-6-plus', 2),
      ('apple', 'iPhone 6s', 'iphone-6s', 3),
      ('apple', 'iPhone 6s Plus', 'iphone-6s-plus', 4),
      ('apple', 'iPhone 7', 'iphone-7', 5),
      ('apple', 'iPhone 7 Plus', 'iphone-7-plus', 6),
      ('apple', 'iPhone 8', 'iphone-8', 7),
      ('apple', 'iPhone 8 Plus', 'iphone-8-plus', 8),
      ('apple', 'iPhone X', 'iphone-x', 9),
      ('apple', 'iPhone XR', 'iphone-xr', 10),
      ('apple', 'iPhone XS', 'iphone-xs', 11),
      ('apple', 'iPhone XS Max', 'iphone-xs-max', 12),
      ('apple', 'iPhone 11', 'iphone-11', 13),
      ('apple', 'iPhone 11 Pro', 'iphone-11-pro', 14),
      ('apple', 'iPhone 11 Pro Max', 'iphone-11-pro-max', 15),
      ('apple', 'iPhone 12', 'iphone-12', 16),
      ('apple', 'iPhone 12 Mini', 'iphone-12-mini', 17),
      ('apple', 'iPhone 12 Pro', 'iphone-12-pro', 18),
      ('apple', 'iPhone 12 Pro Max', 'iphone-12-pro-max', 19),
      ('apple', 'iPhone 13', 'iphone-13', 20),
      ('apple', 'iPhone 13 Mini', 'iphone-13-mini', 21),
      ('apple', 'iPhone 13 Pro', 'iphone-13-pro', 22),
      ('apple', 'iPhone 13 Pro Max', 'iphone-13-pro-max', 23),
      ('apple', 'iPhone 14', 'iphone-14', 24),
      ('apple', 'iPhone 14 Plus', 'iphone-14-plus', 25),
      ('apple', 'iPhone 14 Pro', 'iphone-14-pro', 26),
      ('apple', 'iPhone 14 Pro Max', 'iphone-14-pro-max', 27),
      ('apple', 'iPhone 15', 'iphone-15', 28),
      ('apple', 'iPhone 15 Plus', 'iphone-15-plus', 29),
      ('apple', 'iPhone 15 Pro', 'iphone-15-pro', 30),
      ('apple', 'iPhone 15 Pro Max', 'iphone-15-pro-max', 31),
      ('apple', 'iPhone 16', 'iphone-16', 32),
      ('apple', 'iPhone 16 Plus', 'iphone-16-plus', 33),
      ('apple', 'iPhone 16 Pro', 'iphone-16-pro', 34),
      ('apple', 'iPhone 16 Pro Max', 'iphone-16-pro-max', 35),

      -- Samsung
      ('samsung', 'Galaxy S8', 'galaxy-s8', 1),
      ('samsung', 'Galaxy S9', 'galaxy-s9', 2),
      ('samsung', 'Galaxy S10', 'galaxy-s10', 3),
      ('samsung', 'Galaxy S20', 'galaxy-s20', 4),
      ('samsung', 'Galaxy S21', 'galaxy-s21', 5),
      ('samsung', 'Galaxy S22', 'galaxy-s22', 6),
      ('samsung', 'Galaxy S23', 'galaxy-s23', 7),
      ('samsung', 'Galaxy S24', 'galaxy-s24', 8),
      ('samsung', 'Galaxy S25', 'galaxy-s25', 9),
      ('samsung', 'Galaxy Note 8', 'galaxy-note-8', 10),
      ('samsung', 'Galaxy Note 9', 'galaxy-note-9', 11),
      ('samsung', 'Galaxy Note 10', 'galaxy-note-10', 12),
      ('samsung', 'Galaxy Note 20', 'galaxy-note-20', 13),
      ('samsung', 'Galaxy A10', 'galaxy-a10', 14),
      ('samsung', 'Galaxy A12', 'galaxy-a12', 15),
      ('samsung', 'Galaxy A13', 'galaxy-a13', 16),
      ('samsung', 'Galaxy A14', 'galaxy-a14', 17),
      ('samsung', 'Galaxy A15', 'galaxy-a15', 18),
      ('samsung', 'Galaxy A20', 'galaxy-a20', 19),
      ('samsung', 'Galaxy A21s', 'galaxy-a21s', 20),
      ('samsung', 'Galaxy A22', 'galaxy-a22', 21),
      ('samsung', 'Galaxy A23', 'galaxy-a23', 22),
      ('samsung', 'Galaxy A24', 'galaxy-a24', 23),
      ('samsung', 'Galaxy A25', 'galaxy-a25', 24),
      ('samsung', 'Galaxy A30', 'galaxy-a30', 25),
      ('samsung', 'Galaxy A31', 'galaxy-a31', 26),
      ('samsung', 'Galaxy A32', 'galaxy-a32', 27),
      ('samsung', 'Galaxy A33', 'galaxy-a33', 28),
      ('samsung', 'Galaxy A34', 'galaxy-a34', 29),
      ('samsung', 'Galaxy A35', 'galaxy-a35', 30),
      ('samsung', 'Galaxy A50', 'galaxy-a50', 31),
      ('samsung', 'Galaxy A51', 'galaxy-a51', 32),
      ('samsung', 'Galaxy A52', 'galaxy-a52', 33),
      ('samsung', 'Galaxy A53', 'galaxy-a53', 34),
      ('samsung', 'Galaxy A54', 'galaxy-a54', 35),
      ('samsung', 'Galaxy A55', 'galaxy-a55', 36),
      ('samsung', 'Galaxy M10', 'galaxy-m10', 37),
      ('samsung', 'Galaxy M12', 'galaxy-m12', 38),
      ('samsung', 'Galaxy M20', 'galaxy-m20', 39),
      ('samsung', 'Galaxy M30', 'galaxy-m30', 40),
      ('samsung', 'Galaxy M31', 'galaxy-m31', 41),
      ('samsung', 'Galaxy M32', 'galaxy-m32', 42),
      ('samsung', 'Galaxy M33', 'galaxy-m33', 43),
      ('samsung', 'Galaxy M34', 'galaxy-m34', 44),
      ('samsung', 'Galaxy M35', 'galaxy-m35', 45),

      -- Xiaomi / Redmi / Poco
      ('xiaomi', 'Redmi Note 8', 'redmi-note-8', 1),
      ('xiaomi', 'Redmi Note 9', 'redmi-note-9', 2),
      ('xiaomi', 'Redmi Note 10', 'redmi-note-10', 3),
      ('xiaomi', 'Redmi Note 11', 'redmi-note-11', 4),
      ('xiaomi', 'Redmi Note 12', 'redmi-note-12', 5),
      ('xiaomi', 'Redmi Note 13', 'redmi-note-13', 6),
      ('xiaomi', 'Redmi 9', 'redmi-9', 7),
      ('xiaomi', 'Redmi 10', 'redmi-10', 8),
      ('xiaomi', 'Redmi 12', 'redmi-12', 9),
      ('xiaomi', 'Redmi 13', 'redmi-13', 10),
      ('xiaomi', 'Poco X3', 'poco-x3', 11),
      ('xiaomi', 'Poco X4', 'poco-x4', 12),
      ('xiaomi', 'Poco X5', 'poco-x5', 13),
      ('xiaomi', 'Poco X6', 'poco-x6', 14),
      ('xiaomi', 'Poco F3', 'poco-f3', 15),
      ('xiaomi', 'Poco F4', 'poco-f4', 16),
      ('xiaomi', 'Poco F5', 'poco-f5', 17),
      ('xiaomi', 'Poco F6', 'poco-f6', 18),

      -- Huawei
      ('huawei', 'P20', 'p20', 1),
      ('huawei', 'P30', 'p30', 2),
      ('huawei', 'P40', 'p40', 3),
      ('huawei', 'P50', 'p50', 4),
      ('huawei', 'Mate 20', 'mate-20', 5),
      ('huawei', 'Mate 30', 'mate-30', 6),
      ('huawei', 'Mate 40', 'mate-40', 7),
      ('huawei', 'Y6', 'y6', 8),
      ('huawei', 'Y7', 'y7', 9),
      ('huawei', 'Y8', 'y8', 10),
      ('huawei', 'Y9', 'y9', 11),
      ('huawei', 'Nova 7', 'nova-7', 12),
      ('huawei', 'Nova 9', 'nova-9', 13),
      ('huawei', 'Nova 11', 'nova-11', 14),

      -- Honor
      ('honor', 'Honor 8', 'honor-8', 1),
      ('honor', 'Honor 9', 'honor-9', 2),
      ('honor', 'Honor 10', 'honor-10', 3),
      ('honor', 'Honor X6', 'honor-x6', 4),
      ('honor', 'Honor X7', 'honor-x7', 5),
      ('honor', 'Honor X8', 'honor-x8', 6),
      ('honor', 'Honor X9', 'honor-x9', 7),
      ('honor', 'Honor 50', 'honor-50', 8),
      ('honor', 'Honor 70', 'honor-70', 9),
      ('honor', 'Honor 90', 'honor-90', 10),
      ('honor', 'Honor Magic 5', 'honor-magic-5', 11),
      ('honor', 'Honor Magic 6', 'honor-magic-6', 12),

      -- Generic entries for other brands
      ('nokia', 'Nokia Generic', 'nokia-generic', 1),
      ('tecno', 'Tecno Generic', 'tecno-generic', 1),
      ('infinix', 'Infinix Generic', 'infinix-generic', 1),
      ('oppo', 'Oppo Generic', 'oppo-generic', 1),
      ('vivo', 'Vivo Generic', 'vivo-generic', 1),
      ('realme', 'Realme Generic', 'realme-generic', 1),
      ('lg', 'LG Generic', 'lg-generic', 1),
      ('sony', 'Sony Generic', 'sony-generic', 1),
      ('motorola', 'Motorola Generic', 'motorola-generic', 1),
      ('oneplus', 'OnePlus Generic', 'oneplus-generic', 1),
      ('itel', 'Itel Generic', 'itel-generic', 1)
  ) as t(brand_slug, model_name, model_slug, display_order)
), brand_nodes as (
  select id, category_id, level, path, slug
  from public.category_nodes
  where path like 'phones-electronics/mobile-phones/%'
    and level = 3
)
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select
  brand.category_id,
  brand.id,
  model.model_name,
  model.model_slug,
  brand.level + 1,
  brand.path || '/' || model.model_slug,
  model.display_order,
  true
from model_seed model
join brand_nodes brand on brand.slug = model.brand_slug
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

-- =========================================================
-- 3) Phone product specs seed
-- =========================================================

with model_specs_seed as (
  select * from (
    values
      ('apple', 'iphone-13-pro-max', array['iphone 13 pro max','apple iphone 13 pro max']::text[]),
      ('apple', 'iphone-14-pro-max', array['iphone 14 pro max','apple iphone 14 pro max']::text[]),
      ('apple', 'iphone-15-pro-max', array['iphone 15 pro max','apple iphone 15 pro max']::text[]),
      ('apple', 'iphone-16-pro-max', array['iphone 16 pro max','apple iphone 16 pro max']::text[]),
      ('samsung', 'galaxy-s24', array['s24','galaxy s24','samsung s24']::text[]),
      ('samsung', 'galaxy-s25', array['s25','galaxy s25','samsung s25']::text[]),
      ('xiaomi', 'redmi-note-13', array['redmi note 13','xiaomi redmi note 13']::text[]),
      ('xiaomi', 'poco-x6', array['poco x6','xiaomi poco x6']::text[]),
      ('huawei', 'p50', array['huawei p50','p50 huawei']::text[]),
      ('honor', 'honor-90', array['honor 90']::text[])
  ) as t(brand_slug, model_slug, aliases)
), all_model_nodes as (
  select
    model.id as category_node_id,
    brand.name as brand,
    model.name as model,
    brand.slug as brand_slug,
    model.slug as model_slug,
    model.path
  from public.category_nodes model
  join public.category_nodes brand on brand.id = model.parent_id
  where model.path like 'phones-electronics/mobile-phones/%/%'
    and model.level = 4
), final_specs as (
  select
    n.category_node_id,
    n.brand,
    n.model,
    coalesce(s.aliases, array[lower(n.model), regexp_replace(lower(n.model), '[^a-z0-9]+', '', 'g')]::text[]) as aliases,
    jsonb_build_object(
      'brand', n.brand,
      'model', n.model,
      'operating_system', case when n.brand_slug = 'apple' then 'iOS' else 'Android' end,
      'screen_size', case
        when n.model_slug like '%pro-max' then '6.7 inch'
        when n.model_slug like '%plus' then '6.7 inch'
        when n.model_slug like '%mini' then '5.4 inch'
        when n.model_slug in ('iphone-6','iphone-6s','iphone-7','iphone-8') then '4.7 inch'
        when n.model_slug in ('iphone-x','iphone-xr','iphone-xs') then '6.1 inch'
        when n.model_slug like 'galaxy-note-%' then '6.7 inch'
        else '6.5 inch'
      end,
      'storage_options', case
        when n.brand_slug = 'apple' then '["64 GB","128 GB","256 GB","512 GB","1 TB"]'::jsonb
        when n.brand_slug = 'samsung' then '["64 GB","128 GB","256 GB","512 GB"]'::jsonb
        when n.brand_slug = 'xiaomi' then '["64 GB","128 GB","256 GB"]'::jsonb
        else '["64 GB","128 GB","256 GB"]'::jsonb
      end,
      'ram_options', case
        when n.brand_slug = 'apple' then '["4 GB","6 GB","8 GB"]'::jsonb
        when n.brand_slug = 'samsung' then '["4 GB","6 GB","8 GB","12 GB"]'::jsonb
        when n.brand_slug = 'xiaomi' then '["4 GB","6 GB","8 GB","12 GB"]'::jsonb
        else '["4 GB","6 GB","8 GB"]'::jsonb
      end,
      'camera_info', case
        when n.model_slug = 'iphone-13-pro-max' then '12 MP'
        when n.model_slug like '%pro%' then '48 MP'
        when n.model_slug like 'galaxy-s2%' then '50 MP'
        else '48 MP'
      end,
      'front_camera', case
        when n.model_slug like 'iphone-%' then '12 MP'
        else '16 MP'
      end,
      'sim_type', case
        when n.brand_slug = 'apple' then 'Nano-SIM and eSIM'
        else 'Dual SIM'
      end
    ) as specs
  from all_model_nodes n
  left join model_specs_seed s
    on s.brand_slug = n.brand_slug
   and s.model_slug = n.model_slug
)
insert into public.product_specs (category_node_id, brand, model, aliases, specs, is_active)
select
  f.category_node_id,
  f.brand,
  f.model,
  f.aliases,
  f.specs,
  true
from final_specs f
on conflict (category_node_id, brand, model) do update
set
  aliases = excluded.aliases,
  specs = excluded.specs,
  is_active = true;

-- Additional phone-specific category fields for full post-ad flow.
insert into public.category_fields (category_node_id, field_key, field_label, field_type, is_required, options_json, unit, display_order, is_active)
select
  n.id,
  f.field_key,
  f.field_label,
  f.field_type,
  f.is_required,
  f.options_json,
  f.unit,
  f.display_order,
  true
from public.category_nodes n
cross join (
  values
    ('operating_system', 'Operating System', 'text', false, null::jsonb, null::text, 20),
    ('screen_size', 'Screen Size', 'text', false, null::jsonb, null::text, 21),
    ('storage_options', 'Storage Options', 'select', false, '["64 GB","128 GB","256 GB","512 GB","1 TB"]'::jsonb, null::text, 22),
    ('ram_options', 'RAM Options', 'select', false, '["4 GB","6 GB","8 GB","12 GB"]'::jsonb, null::text, 23),
    ('camera_info', 'Rear Camera', 'text', false, null::jsonb, null::text, 24),
    ('front_camera', 'Front Camera', 'text', false, null::jsonb, null::text, 25),
    ('sim_type', 'SIM Type', 'text', false, null::jsonb, null::text, 26),
    ('purchased_from', 'Purchased From', 'text', false, null::jsonb, null::text, 27),
    ('exchange_available', 'Exchange Available', 'boolean', false, null::jsonb, null::text, 28)
) as f(field_key, field_label, field_type, is_required, options_json, unit, display_order)
where n.path like 'phones-electronics/mobile-phones/%/%'
on conflict (category_node_id, field_key) do update
set
  field_label = excluded.field_label,
  field_type = excluded.field_type,
  is_required = excluded.is_required,
  options_json = excluded.options_json,
  unit = excluded.unit,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

commit;
