-- Afghanistan-first category redesign

begin;

create extension if not exists pg_trgm;

create table if not exists public.category_aliases (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.category_nodes(id) on delete cascade,
  alias text not null,
  language text not null default 'en',
  created_at timestamptz not null default now()
);

create unique index if not exists idx_category_aliases_unique
  on public.category_aliases (category_id, lower(alias), language);
create index if not exists idx_category_aliases_alias on public.category_aliases using gin (alias gin_trgm_ops);
create index if not exists idx_category_aliases_category on public.category_aliases(category_id, language);

alter table public.category_aliases enable row level security;

drop policy if exists category_aliases_public_select on public.category_aliases;
create policy category_aliases_public_select
on public.category_aliases
for select
using (true);

drop policy if exists category_aliases_admin_manage on public.category_aliases;
create policy category_aliases_admin_manage
on public.category_aliases
for all
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

insert into public.categories (name, slug, description, display_order, is_active)
values
  ('Vehicles', 'vehicles', 'Cars, motorcycles, rickshaws, trucks, and parts.', 1, true),
  ('Real Estate', 'real-estate', 'Houses, apartments, land, and commercial property.', 2, true),
  ('Mobile Phones & Tablets', 'mobile-phones-tablets', 'Phones, tablets, smart watches, and accessories.', 3, true),
  ('Electronics & Computers', 'electronics-computers', 'Laptops, TVs, cameras, and computer equipment.', 4, true),
  ('Home, Furniture & Appliances', 'home-furniture-appliances', 'Furniture, home items, and appliances.', 5, true),
  ('Clothing & Personal Items', 'clothing-personal-items', 'Clothes, shoes, bags, and personal items.', 6, true),
  ('Jobs', 'jobs', 'Full-time, part-time, and labor jobs.', 7, true),
  ('Services', 'services', 'Repairs, transport, documents, and local services.', 8, true),
  ('Business & Industry', 'business-industry', 'Shops, machinery, wholesale, and industrial goods.', 9, true),
  ('Farm & Animals', 'farm-animals', 'Livestock, farm tools, feed, and pets.', 10, true),
  ('Education', 'education', 'Books, tutoring, classes, and training.', 11, true),
  ('Sports & Hobbies', 'sports-hobbies', 'Sports items, music, games, and leisure goods.', 12, true),
  ('Other', 'other', 'Miscellaneous items with manual entry.', 13, true)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf, description, icon)
select c.id, null, c.name, c.slug, 1, c.slug, c.display_order, c.display_order, true, false, c.description, case c.slug
  when 'vehicles' then 'car'
  when 'real-estate' then 'home'
  when 'mobile-phones-tablets' then 'smartphone'
  when 'electronics-computers' then 'laptop'
  when 'home-furniture-appliances' then 'sofa'
  when 'clothing-personal-items' then 'shirt'
  when 'jobs' then 'briefcase'
  when 'services' then 'wrench'
  when 'business-industry' then 'factory'
  when 'farm-animals' then 'tractor'
  when 'education' then 'book-open'
  when 'sports-hobbies' then 'trophy'
  else 'dots-horizontal'
end
from public.categories c
where c.slug in (
  'vehicles', 'real-estate', 'mobile-phones-tablets', 'electronics-computers',
  'home-furniture-appliances', 'clothing-personal-items', 'jobs', 'services',
  'business-industry', 'farm-animals', 'education', 'sports-hobbies', 'other'
)
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  sort_order = excluded.sort_order,
  description = excluded.description,
  icon = excluded.icon,
  is_active = true,
  is_leaf = false,
  updated_at = now();

-- Vehicles
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf, description, icon)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, v.display_order, true, false, v.description, v.icon
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('Cars', 'cars', 1, 'Passenger cars, sedans, SUVs, and crossovers.', 'car'),
    ('Motorcycles', 'motorcycles', 2, 'Motorbikes and Afghan common motorcycle types.', 'bike'),
    ('Rickshaws / Three-Wheelers', 'rickshaws-three-wheelers', 3, 'Passenger and cargo rickshaws.', 'motorbike'),
    ('Bicycles', 'bicycles', 4, 'Bicycles and electric bicycles.', 'bicycle'),
    ('Pickup Trucks', 'pickup-trucks', 5, 'Pickup trucks and light utility pickups.', 'truck'),
    ('Vans & Minibuses', 'vans-minibuses', 6, 'Family vans and minibuses.', 'bus'),
    ('Trucks & Heavy Vehicles', 'trucks-heavy-vehicles', 7, 'Trucks, haulers, and heavy vehicles.', 'truck'),
    ('Agricultural Vehicles', 'agricultural-vehicles', 8, 'Tractors and rural work vehicles.', 'tractor'),
    ('Vehicle Parts & Accessories', 'vehicle-parts-accessories', 9, 'Spare parts, tires, and accessories.', 'settings'),
    ('Damaged Vehicles / For Parts', 'damaged-vehicles-for-parts', 10, 'Damaged vehicles and dismantling projects.', 'alert-triangle'),
    ('Other Vehicles', 'other-vehicles', 11, 'Anything else manual.', 'dots-horizontal')
) as v(name, slug, display_order, description, icon)
where c.slug = 'vehicles'
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  sort_order = excluded.sort_order,
  description = excluded.description,
  icon = excluded.icon,
  is_active = true,
  is_leaf = false,
  updated_at = now();

-- Car brands
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf, description, icon)
select c.id, cars.id, b.name, b.slug, 3, cars.path || '/' || b.slug, b.display_order, b.display_order, true, false, null, 'car'
from public.categories c
join public.category_nodes vehicles on vehicles.category_id = c.id and vehicles.path = 'vehicles'
join public.category_nodes cars on cars.parent_id = vehicles.id and cars.slug = 'cars'
cross join (
  values
    ('Toyota', 'toyota', 1),
    ('Honda', 'honda', 2),
    ('Hyundai', 'hyundai', 3),
    ('Kia', 'kia', 4),
    ('Nissan', 'nissan', 5),
    ('Mazda', 'mazda', 6),
    ('Mitsubishi', 'mitsubishi', 7),
    ('Suzuki', 'suzuki', 8),
    ('Mercedes-Benz', 'mercedes-benz', 9),
    ('BMW', 'bmw', 10),
    ('Lexus', 'lexus', 11),
    ('Ford', 'ford', 12),
    ('Chevrolet', 'chevrolet', 13),
    ('Volkswagen', 'volkswagen', 14),
    ('Land Rover', 'land-rover', 15),
    ('Jeep', 'jeep', 16),
    ('Other Brand', 'other-brand', 17)
) as b(name, slug, display_order)
where c.slug = 'vehicles'
on conflict (path) do update
set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, is_active = true, is_leaf = false, updated_at = now();

-- Toyota models
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf)
select c.id, toyota.id, m.name, m.slug, 4, toyota.path || '/' || m.slug, m.display_order, m.display_order, true, true
from public.categories c
join public.category_nodes vehicles on vehicles.category_id = c.id and vehicles.path = 'vehicles'
join public.category_nodes cars on cars.parent_id = vehicles.id and cars.slug = 'cars'
join public.category_nodes toyota on toyota.parent_id = cars.id and toyota.slug = 'toyota'
cross join (
  values
    ('Corolla', 'corolla', 1),
    ('Land Cruiser', 'land-cruiser', 2),
    ('Land Cruiser Prado', 'land-cruiser-prado', 3),
    ('Hilux', 'hilux', 4),
    ('4Runner', '4runner', 5),
    ('Camry', 'camry', 6),
    ('Mark X', 'mark-x', 7),
    ('Crown', 'crown', 8),
    ('Vitz', 'vitz', 9),
    ('Yaris', 'yaris', 10),
    ('Fielder', 'fielder', 11),
    ('Aqua', 'aqua', 12),
    ('Prius', 'prius', 13),
    ('RAV4', 'rav4', 14),
    ('Highlander', 'highlander', 15),
    ('Surf / Hilux Surf', 'surf-hilux-surf', 16),
    ('TownAce / Saracha', 'townace-saracha', 17),
    ('Other Toyota Model', 'other-toyota-model', 18)
) as m(name, slug, display_order)
where c.slug = 'vehicles'
on conflict (path) do update set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, is_leaf = true, is_active = true, updated_at = now();

-- Real Estate
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf, description, icon)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, v.display_order, true, false, v.description, v.icon
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('Houses', 'houses', 1, 'Sale, rent, and older houses.', 'home'),
    ('Apartments', 'apartments', 2, 'Apartments and flats.', 'building-2'),
    ('Rooms', 'rooms', 3, 'Rooms, shared rooms, and dormitory rooms.', 'bed'),
    ('Shops & Commercial', 'shops-commercial', 4, 'Shops, bazaars, and commercial spaces.', 'store'),
    ('Offices', 'offices', 5, 'Office and admin spaces.', 'briefcase'),
    ('Land', 'land', 6, 'Land, plots, and land lease.', 'map'),
    ('Warehouses', 'warehouses', 7, 'Storage and warehouse units.', 'warehouse'),
    ('Gardens / Farms', 'gardens-farms', 8, 'Gardens, orchards, and farms.', 'sprout'),
    ('Short-Term Rent', 'short-term-rent', 9, 'Daily or short stay rental.', 'calendar-clock'),
    ('Other Property', 'other-property', 10, 'Manual property posting.', 'dots-horizontal')
) as v(name, slug, display_order, description, icon)
where c.slug = 'real-estate'
on conflict (path) do update set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, description = excluded.description, icon = excluded.icon, is_active = true, is_leaf = false, updated_at = now();

-- Property styles
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf)
select c.id, houses.id, s.name, s.slug, 3, houses.path || '/' || s.slug, s.display_order, s.display_order, true, true
from public.categories c
join public.category_nodes root on root.category_id = c.id and root.path = 'real-estate'
join public.category_nodes houses on houses.parent_id = root.id and houses.slug = 'houses'
cross join (
  values
    ('Normal House', 'normal-house', 1),
    ('Luxury House', 'luxury-house', 2),
    ('Villa', 'villa', 3),
    ('Duplex', 'duplex', 4),
    ('Multi-Floor House', 'multi-floor-house', 5),
    ('Old House', 'old-house', 6),
    ('Under Construction', 'under-construction', 7),
    ('Other House Type', 'other-house-type', 8)
) as s(name, slug, display_order)
where c.slug = 'real-estate'
on conflict (path) do update set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, is_leaf = true, is_active = true, updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf)
select c.id, apartments.id, s.name, s.slug, 3, apartments.path || '/' || s.slug, s.display_order, s.display_order, true, true
from public.categories c
join public.category_nodes root on root.category_id = c.id and root.path = 'real-estate'
join public.category_nodes apartments on apartments.parent_id = root.id and apartments.slug = 'apartments'
cross join (
  values
    ('Apartment', 'apartment', 1),
    ('Flat', 'flat', 2),
    ('Modern Apartment', 'modern-apartment', 3),
    ('Old Apartment', 'old-apartment', 4),
    ('Furnished Apartment', 'furnished-apartment', 5),
    ('Unfurnished Apartment', 'unfurnished-apartment', 6)
) as s(name, slug, display_order)
where c.slug = 'real-estate'
on conflict (path) do update set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, is_leaf = true, is_active = true, updated_at = now();

-- Mobile Phones & Tablets
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf, description, icon)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, v.display_order, true, false, v.description, v.icon
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('Mobile Phones', 'mobile-phones', 1, 'Smartphones and feature phones.', 'smartphone'),
    ('Tablets', 'tablets', 2, 'Tablets and iPads.', 'tablet'),
    ('Smart Watches', 'smart-watches', 3, 'Smart watches and wearables.', 'watch'),
    ('Phone Accessories', 'phone-accessories', 4, 'Cases, chargers, and accessories.', 'headphones'),
    ('SIM Cards & Numbers', 'sim-cards-numbers', 5, 'SIM cards, numbers, and packages.', 'sim-card'),
    ('Phone Repair Services', 'phone-repair-services', 6, 'Repair and maintenance services.', 'wrench'),
    ('Other', 'other', 7, 'Manual entry for anything else.', 'dots-horizontal')
) as v(name, slug, display_order, description, icon)
where c.slug = 'mobile-phones-tablets'
on conflict (path) do update set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, description = excluded.description, icon = excluded.icon, is_active = true, is_leaf = false, updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, sort_order, is_active, is_leaf)
select c.id, mobile.id, b.name, b.slug, 3, mobile.path || '/' || b.slug, b.display_order, b.display_order, true, true
from public.categories c
join public.category_nodes root on root.category_id = c.id and root.path = 'mobile-phones-tablets'
join public.category_nodes mobile on mobile.parent_id = root.id and mobile.slug = 'mobile-phones'
cross join (
  values
    ('Apple iPhone', 'apple-iphone', 1),
    ('Samsung', 'samsung', 2),
    ('Xiaomi', 'xiaomi', 3),
    ('Huawei', 'huawei', 4),
    ('Honor', 'honor', 5),
    ('Oppo', 'oppo', 6),
    ('Vivo', 'vivo', 7),
    ('Nokia', 'nokia', 8),
    ('Infinix', 'infinix', 9),
    ('Tecno', 'tecno', 10),
    ('Realme', 'realme', 11),
    ('OnePlus', 'oneplus', 12),
    ('Other Brand', 'other-brand', 13)
) as b(name, slug, display_order)
where c.slug = 'mobile-phones-tablets'
on conflict (path) do update set name = excluded.name, display_order = excluded.display_order, sort_order = excluded.sort_order, is_leaf = true, is_active = true, updated_at = now();

-- Aliases for local Afghan search terms
insert into public.category_aliases (category_id, alias, language)
select n.id, a.alias, 'en'
from public.category_nodes n
join (
  values
    ('vehicles/cars/toyota', 'Toyota'),
    ('vehicles/cars/toyota', 'Toyota Saracha'),
    ('vehicles/cars/toyota', 'Fielder'),
    ('vehicles/cars/toyota', 'Prado'),
    ('vehicles/cars/toyota', 'Land Cruiser'),
    ('vehicles/cars/toyota', 'Corolla'),
    ('vehicles/cars/toyota', 'Saracha'),
    ('vehicles/cars/toyota', 'Seraacha'),
    ('vehicles/cars/toyota', 'Rahn'),
    ('vehicles/rickshaws-three-wheelers', 'Rickshaw'),
    ('vehicles/rickshaws-three-wheelers', 'Tuk Tuk'),
    ('vehicles/motorcycles', 'Honda 70'),
    ('vehicles/motorcycles', 'Honda 125'),
    ('mobile-phones-tablets/mobile-phones/apple-iphone', 'iPhone'),
    ('mobile-phones-tablets/mobile-phones/samsung', 'Samsung Galaxy')
) as a(path, alias) on a.path = n.path
on conflict do nothing;

commit;
