begin;

create table if not exists public.product_brands (
  id bigint generated by default as identity primary key,
  category_node_id bigint not null references public.category_nodes(id) on delete cascade,
  name text not null,
  slug text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_brands_unique_per_category unique (category_node_id, slug)
);

create table if not exists public.product_series (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.product_brands(id) on delete cascade,
  name text not null,
  slug text not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_series_unique_per_brand unique (brand_id, slug)
);

create table if not exists public.product_models (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.product_brands(id) on delete cascade,
  series_id bigint references public.product_series(id) on delete set null,
  category_node_id bigint references public.category_nodes(id) on delete set null,
  name text not null,
  slug text not null,
  release_year int,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint product_models_unique_per_brand unique (brand_id, slug)
);

create table if not exists public.model_specifications (
  id bigint generated by default as identity primary key,
  product_model_id bigint not null references public.product_models(id) on delete cascade,
  spec_key text not null,
  spec_label text not null,
  spec_value text not null,
  is_locked boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint model_specifications_unique_key_per_model unique (product_model_id, spec_key)
);

alter table public.listings
  add column if not exists product_model_id bigint references public.product_models(id) on delete set null;

alter table public.listing_attributes
  add column if not exists field_label text,
  add column if not exists is_locked boolean not null default false;

create index if not exists idx_product_brands_category_node on public.product_brands(category_node_id, is_active);
create index if not exists idx_product_series_brand on public.product_series(brand_id, sort_order, is_active);
create index if not exists idx_product_models_brand_series on public.product_models(brand_id, series_id, is_active);
create index if not exists idx_model_specifications_model on public.model_specifications(product_model_id, sort_order);
create index if not exists idx_listings_product_model_id on public.listings(product_model_id);

commit;
