begin;

create table if not exists public.site_settings_versions (
  id bigint generated by default as identity primary key,
  site_settings_id smallint not null references public.site_settings(id) on delete cascade,
  version_number integer not null,
  change_summary text,
  settings_snapshot jsonb not null,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  published_at timestamptz not null default now(),
  constraint site_settings_versions_unique_version unique (site_settings_id, version_number)
);

create index if not exists site_settings_versions_created_at_idx
  on public.site_settings_versions (site_settings_id, created_at desc);

alter table public.site_settings_versions enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'site_settings_versions' and policyname = 'site_settings_versions_readable_by_admins'
  ) then
    create policy "site_settings_versions_readable_by_admins"
    on public.site_settings_versions
    for select
    using (public.is_admin(auth.uid()));
  end if;
end
$$;

create or replace function public.save_site_settings(
  payload jsonb,
  change_summary text,
  editor_id uuid
)
returns public.site_settings
language plpgsql
security definer
set search_path = public
as $$
declare
  updated_row public.site_settings;
  next_version integer;
begin
  insert into public.site_settings (id, site_name, site_tagline, contact_email, contact_phone, default_locale)
  values (
    1,
    coalesce(nullif(btrim(payload->>'site_name'), ''), 'Sahibash'),
    nullif(btrim(payload->>'site_tagline'), ''),
    coalesce(nullif(btrim(payload->>'contact_email'), ''), 'hello@sahibash.com'),
    coalesce(nullif(btrim(payload->>'contact_phone'), ''), '+93700000000'),
    coalesce(nullif(btrim(payload->>'default_locale'), ''), 'fa')
  )
  on conflict (id) do update set
    site_name = excluded.site_name,
    site_tagline = excluded.site_tagline,
    contact_email = excluded.contact_email,
    contact_phone = excluded.contact_phone,
    default_locale = excluded.default_locale,
    updated_at = now()
  returning * into updated_row;

  select coalesce(max(version_number), 0) + 1
  into next_version
  from public.site_settings_versions
  where site_settings_id = 1;

  insert into public.site_settings_versions (
    site_settings_id,
    version_number,
    change_summary,
    settings_snapshot,
    created_by
  ) values (
    1,
    next_version,
    nullif(btrim(change_summary), ''),
    to_jsonb(updated_row),
    editor_id
  );

  return updated_row;
end;
$$;

create or replace function public.restore_site_settings_version(
  version_row_id bigint,
  change_summary text,
  editor_id uuid
)
returns public.site_settings
language plpgsql
security definer
set search_path = public
as $$
declare
  snapshot record;
  restored_row public.site_settings;
  next_version integer;
begin
  select *
  into snapshot
  from public.site_settings_versions
  where id = version_row_id
    and site_settings_id = 1;

  if not found then
    raise exception 'Site settings version not found';
  end if;

  insert into public.site_settings (id, site_name, site_tagline, contact_email, contact_phone, default_locale)
  values (
    1,
    coalesce(nullif(btrim(snapshot.settings_snapshot->>'site_name'), ''), 'Sahibash'),
    nullif(btrim(snapshot.settings_snapshot->>'site_tagline'), ''),
    coalesce(nullif(btrim(snapshot.settings_snapshot->>'contact_email'), ''), 'hello@sahibash.com'),
    coalesce(nullif(btrim(snapshot.settings_snapshot->>'contact_phone'), ''), '+93700000000'),
    coalesce(nullif(btrim(snapshot.settings_snapshot->>'default_locale'), ''), 'fa')
  )
  on conflict (id) do update set
    site_name = excluded.site_name,
    site_tagline = excluded.site_tagline,
    contact_email = excluded.contact_email,
    contact_phone = excluded.contact_phone,
    default_locale = excluded.default_locale,
    updated_at = now()
  returning * into restored_row;

  select coalesce(max(version_number), 0) + 1
  into next_version
  from public.site_settings_versions
  where site_settings_id = 1;

  insert into public.site_settings_versions (
    site_settings_id,
    version_number,
    change_summary,
    settings_snapshot,
    created_by
  ) values (
    1,
    next_version,
    coalesce(nullif(btrim(change_summary), ''), 'Restored site settings version ' || version_row_id::text),
    to_jsonb(restored_row),
    editor_id
  );

  return restored_row;
end;
$$;

do $$
begin
  if not exists (
    select 1
    from public.site_settings_versions
    where site_settings_id = 1
      and version_number = 1
  ) then
    insert into public.site_settings_versions (
      site_settings_id,
      version_number,
      change_summary,
      settings_snapshot
    )
    select
      1,
      1,
      'Initial site settings',
      to_jsonb(s)
    from public.site_settings s
    where s.id = 1;
  end if;
end
$$;


commit;
