-- Sahibash V2 migration wrapper

begin;

-- Delegate to the canonical schema for single-source-of-truth.
-- Keep this migration in sync with supabase/schema.sql.

create extension if not exists pgcrypto;

-- NOTE:
-- Supabase CLI migrations should contain full SQL in production repos.
-- Copy of supabase/schema.sql content starts below.

-- Sahibash V2 - Afghanistan Marketplace Database
-- Database-first setup: schema, RLS, storage policies, seeds

-- =========================================================
-- 1) Types / Enums
-- =========================================================
do $$
begin
  if not exists (select 1 from pg_type where typname = 'profile_role') then
    create type public.profile_role as enum ('user', 'admin');
  end if;

  if not exists (select 1 from pg_type where typname = 'listing_status') then
    create type public.listing_status as enum ('pending', 'approved', 'rejected', 'sold', 'expired');
  end if;

  if not exists (select 1 from pg_type where typname = 'currency_code') then
    create type public.currency_code as enum ('AFN', 'USD');
  end if;

  if not exists (select 1 from pg_type where typname = 'report_status') then
    create type public.report_status as enum ('open', 'reviewed', 'dismissed', 'actioned');
  end if;

  if not exists (select 1 from pg_type where typname = 'message_status') then
    create type public.message_status as enum ('sent', 'delivered', 'read');
  end if;

  if not exists (select 1 from pg_type where typname = 'promotion_type') then
    create type public.promotion_type as enum ('featured', 'urgent', 'bump');
  end if;

  if not exists (select 1 from pg_type where typname = 'notification_type') then
    create type public.notification_type as enum (
      'listing_approved',
      'listing_rejected',
      'listing_expiring',
      'listing_message',
      'listing_offer',
      'system'
    );
  end if;

  if not exists (select 1 from pg_type where typname = 'language_code') then
    create type public.language_code as enum ('en', 'fa', 'ps');
  end if;
end $$;


-- =========================================================
-- 2) Core Tables
-- =========================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  city text,
  province text,
  avatar_url text,
  preferred_language public.language_code not null default 'en',
  role public.profile_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  description text,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_slug_format check (slug = lower(slug))
);

create table if not exists public.category_nodes (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  parent_id bigint references public.category_nodes(id) on delete cascade,
  name text not null,
  slug text not null,
  level int not null default 1 check (level >= 1 and level <= 5),
  path text not null,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint category_nodes_unique_slug_per_parent unique (category_id, parent_id, slug),
  constraint category_nodes_path_unique unique (path),
  constraint category_nodes_slug_format check (slug = lower(slug))
);

create table if not exists public.category_fields (
  id bigint generated by default as identity primary key,
  category_node_id bigint not null references public.category_nodes(id) on delete cascade,
  field_key text not null,
  field_label text not null,
  field_type text not null check (field_type in ('text', 'number', 'boolean', 'select', 'date')),
  is_required boolean not null default false,
  options_json jsonb,
  unit text,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint category_fields_unique_key_per_node unique (category_node_id, field_key)
);

create table if not exists public.listings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete restrict,
  category_node_id bigint not null references public.category_nodes(id) on delete restrict,
  title text not null check (char_length(title) between 5 and 140),
  description text not null check (char_length(description) between 20 and 8000),
  price numeric(14,2) not null check (price >= 0),
  currency public.currency_code not null default 'AFN',
  city text not null,
  province text,
  district text,
  address_optional text,
  contact_phone text not null,
  contact_name text,
  delivery_preference text,
  meeting_preference text,
  negotiable boolean not null default false,
  minimum_offer numeric(14,2),
  status public.listing_status not null default 'pending',
  featured boolean not null default false,
  urgent boolean not null default false,
  views_count bigint not null default 0,
  favorites_count bigint not null default 0,
  messages_count bigint not null default 0,
  listing_score numeric(10,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  published_at timestamptz,
  last_bumped_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  approved_at timestamptz,
  rejection_reason text,
  archived_at timestamptz
);

create table if not exists public.listing_attributes (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  category_field_id bigint references public.category_fields(id) on delete set null,
  attribute_key text not null,
  attribute_value_text text,
  attribute_value_number numeric,
  attribute_value_boolean boolean,
  attribute_value_json jsonb,
  unit text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_attributes_unique_key_per_listing unique (listing_id, attribute_key),
  constraint listing_attributes_value_required check (
    attribute_value_text is not null
    or attribute_value_number is not null
    or attribute_value_boolean is not null
    or attribute_value_json is not null
  )
);

create table if not exists public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  storage_path text not null unique,
  public_url text,
  is_primary boolean not null default false,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint favorites_unique_user_listing unique (user_id, listing_id)
);

create table if not exists public.saved_searches (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  query_text text,
  filters jsonb not null default '{}'::jsonb,
  notifications_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  sender_user_id uuid not null references auth.users(id) on delete cascade,
  recipient_user_id uuid not null references auth.users(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  status public.message_status not null default 'sent',
  created_at timestamptz not null default now(),
  read_at timestamptz,
  deleted_by_sender boolean not null default false,
  deleted_by_recipient boolean not null default false,
  constraint messages_sender_recipient_diff check (sender_user_id <> recipient_user_id)
);

create table if not exists public.reports (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null,
  details text,
  status public.report_status not null default 'open',
  admin_note text,
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.listing_views (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  viewer_user_id uuid references auth.users(id) on delete set null,
  viewer_ip inet,
  user_agent text,
  viewed_at timestamptz not null default now()
);

create table if not exists public.listing_price_history (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  changed_by uuid not null references auth.users(id) on delete restrict,
  old_price numeric(14,2),
  new_price numeric(14,2) not null,
  currency public.currency_code not null,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.listing_notes (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  note text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint listing_notes_unique_listing_user unique (listing_id, user_id)
);

create table if not exists public.listing_promotions (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  promotion_type public.promotion_type not null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  type public.notification_type not null,
  title text not null,
  body text,
  payload jsonb not null default '{}'::jsonb,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

-- Upgrade path from V1 schema: add missing columns/constraints safely
alter table public.profiles add column if not exists province text;
alter table public.profiles add column if not exists preferred_language public.language_code not null default 'en';

alter table public.categories add column if not exists description text;

alter table public.listings add column if not exists category_node_id bigint;
alter table public.listings add column if not exists province text;
alter table public.listings add column if not exists contact_name text;
alter table public.listings add column if not exists delivery_preference text;
alter table public.listings add column if not exists meeting_preference text;
alter table public.listings add column if not exists negotiable boolean not null default false;
alter table public.listings add column if not exists minimum_offer numeric(14,2);
alter table public.listings add column if not exists urgent boolean not null default false;
alter table public.listings add column if not exists favorites_count bigint not null default 0;
alter table public.listings add column if not exists messages_count bigint not null default 0;
alter table public.listings add column if not exists listing_score numeric(10,2) not null default 0;
alter table public.listings add column if not exists last_bumped_at timestamptz;
alter table public.listings add column if not exists archived_at timestamptz;

alter table public.listings alter column district drop not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'listings_category_node_id_fkey'
      and conrelid = 'public.listings'::regclass
  ) then
    alter table public.listings
      add constraint listings_category_node_id_fkey
      foreign key (category_node_id) references public.category_nodes(id) on delete restrict;
  end if;
end $$;

alter table public.listing_attributes add column if not exists category_field_id bigint references public.category_fields(id) on delete set null;

-- Backfill category nodes from existing category/subcategory data
insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select c.id, null, c.name, c.slug, 1, c.slug, c.display_order, c.is_active
from public.categories c
on conflict (path) do nothing;

do $$
begin
  if to_regclass('public.subcategories') is not null then
    execute $sql$
      insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
      select s.category_id,
             p.id,
             s.name,
             s.slug,
             2,
             p.path || '/' || s.slug,
             s.display_order,
             s.is_active
      from public.subcategories s
      join public.categories c on c.id = s.category_id
      join public.category_nodes p on p.category_id = c.id and p.parent_id is null
      on conflict (path) do nothing
    $sql$;

    execute $sql$
      update public.listings l
      set category_node_id = cn.id
      from public.subcategories s
      join public.category_nodes root on root.category_id = s.category_id and root.parent_id is null
      join public.category_nodes cn on cn.path = root.path || '/' || s.slug
      where l.subcategory_id = s.id
        and l.category_node_id is null
    $sql$;
  end if;
end $$;

update public.listings l
set category_node_id = root.id
from public.category_nodes root
where l.category_node_id is null
  and root.category_id = l.category_id
  and root.parent_id is null;

-- =========================================================
-- 3) Indexes
-- =========================================================

create index if not exists idx_category_nodes_category_parent on public.category_nodes(category_id, parent_id);
create index if not exists idx_category_nodes_path on public.category_nodes(path);
create index if not exists idx_category_fields_node on public.category_fields(category_node_id, display_order);

create index if not exists idx_listings_status_created_at on public.listings(status, created_at desc);
create index if not exists idx_listings_category_id on public.listings(category_id);
create index if not exists idx_listings_category_node_id on public.listings(category_node_id);
create index if not exists idx_listings_city on public.listings(city);
create index if not exists idx_listings_province on public.listings(province);
create index if not exists idx_listings_price on public.listings(price);
create index if not exists idx_listings_user_id on public.listings(user_id);
create index if not exists idx_listings_featured_urgent on public.listings(featured, urgent, status);
create index if not exists idx_listings_expires_at on public.listings(expires_at);

create index if not exists idx_listing_images_listing_id on public.listing_images(listing_id);
create index if not exists idx_listing_attributes_listing_key on public.listing_attributes(listing_id, attribute_key);
create index if not exists idx_listing_attributes_key on public.listing_attributes(attribute_key);

create index if not exists idx_favorites_user_id on public.favorites(user_id);
create index if not exists idx_favorites_listing_id on public.favorites(listing_id);

create index if not exists idx_saved_searches_user_id on public.saved_searches(user_id);
create index if not exists idx_messages_listing_id on public.messages(listing_id);
create index if not exists idx_messages_recipient_status on public.messages(recipient_user_id, status, created_at desc);

create index if not exists idx_reports_listing_id on public.reports(listing_id);
create index if not exists idx_reports_reporter_user_id on public.reports(reporter_user_id);
create index if not exists idx_reports_status on public.reports(status);

create index if not exists idx_listing_views_listing_viewed_at on public.listing_views(listing_id, viewed_at desc);
create index if not exists idx_listing_price_history_listing_created on public.listing_price_history(listing_id, created_at desc);
create index if not exists idx_listing_notes_user on public.listing_notes(user_id);
create index if not exists idx_listing_promotions_listing on public.listing_promotions(listing_id, promotion_type);
create index if not exists idx_notifications_user_read on public.notifications(user_id, is_read, created_at desc);

create unique index if not exists idx_listing_images_primary_once
  on public.listing_images(listing_id)
  where is_primary = true;

-- =========================================================
-- 4) Functions + Triggers
-- =========================================================

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  );
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name')
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.validate_listing_category_node()
returns trigger
language plpgsql
as $$
declare
  node_category_id bigint;
begin
  select category_id into node_category_id
  from public.category_nodes
  where id = new.category_node_id;

  if node_category_id is null then
    raise exception 'Invalid category_node_id: %', new.category_node_id;
  end if;

  if node_category_id <> new.category_id then
    raise exception 'category_node_id % does not belong to category_id %', new.category_node_id, new.category_id;
  end if;

  return new;
end;
$$;

create or replace function public.set_listing_approval_fields()
returns trigger
language plpgsql
as $$
begin
  if new.status = 'approved' and old.status is distinct from 'approved' then
    new.approved_at = coalesce(new.approved_at, now());
    new.published_at = coalesce(new.published_at, now());
  end if;

  if new.status = 'rejected' and old.status is distinct from 'rejected' then
    new.featured = false;
    new.urgent = false;
  end if;

  if new.status in ('pending', 'rejected') then
    new.approved_by = null;
    if new.status = 'pending' then
      new.approved_at = null;
      new.published_at = null;
      new.rejection_reason = null;
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.ensure_single_primary_image()
returns trigger
language plpgsql
as $$
begin
  if new.is_primary then
    update public.listing_images
      set is_primary = false
    where listing_id = new.listing_id
      and id <> coalesce(new.id, '00000000-0000-0000-0000-000000000000'::uuid)
      and is_primary = true;
  end if;
  return new;
end;
$$;

create or replace function public.assign_first_primary_image()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.listing_images li
    where li.listing_id = new.listing_id
      and li.is_primary = true
  ) then
    update public.listing_images
    set is_primary = true
    where id = new.id;
  end if;
  return null;
end;
$$;

create or replace function public.increment_listing_view_count()
returns trigger
language plpgsql
as $$
begin
  update public.listings
    set views_count = views_count + 1
  where id = new.listing_id;
  return null;
end;
$$;

create or replace function public.adjust_favorite_count()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    update public.listings set favorites_count = favorites_count + 1 where id = new.listing_id;
    return new;
  elsif tg_op = 'DELETE' then
    update public.listings set favorites_count = greatest(favorites_count - 1, 0) where id = old.listing_id;
    return old;
  end if;
  return null;
end;
$$;

create or replace function public.adjust_message_count()
returns trigger
language plpgsql
as $$
begin
  update public.listings set messages_count = messages_count + 1 where id = new.listing_id;
  return new;
end;
$$;

create or replace function public.track_listing_price_changes()
returns trigger
language plpgsql
as $$
begin
  if new.price is distinct from old.price then
    insert into public.listing_price_history (listing_id, changed_by, old_price, new_price, currency, reason)
    values (
      new.id,
      auth.uid(),
      old.price,
      new.price,
      new.currency,
      'listing_price_updated'
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

drop trigger if exists trg_category_nodes_updated_at on public.category_nodes;
create trigger trg_category_nodes_updated_at
before update on public.category_nodes
for each row execute function public.set_updated_at();

drop trigger if exists trg_category_fields_updated_at on public.category_fields;
create trigger trg_category_fields_updated_at
before update on public.category_fields
for each row execute function public.set_updated_at();

drop trigger if exists trg_listings_updated_at on public.listings;
create trigger trg_listings_updated_at
before update on public.listings
for each row execute function public.set_updated_at();

drop trigger if exists trg_listings_validate_category_node on public.listings;
create trigger trg_listings_validate_category_node
before insert or update of category_id, category_node_id on public.listings
for each row execute function public.validate_listing_category_node();

drop trigger if exists trg_listings_approval_fields on public.listings;
create trigger trg_listings_approval_fields
before update of status on public.listings
for each row execute function public.set_listing_approval_fields();

drop trigger if exists trg_listings_track_price on public.listings;
create trigger trg_listings_track_price
after update of price on public.listings
for each row execute function public.track_listing_price_changes();

drop trigger if exists trg_listing_images_updated_at on public.listing_images;
create trigger trg_listing_images_updated_at
before update on public.listing_images
for each row execute function public.set_updated_at();

drop trigger if exists trg_listing_images_single_primary on public.listing_images;
create trigger trg_listing_images_single_primary
before insert or update of is_primary on public.listing_images
for each row execute function public.ensure_single_primary_image();

drop trigger if exists trg_listing_images_assign_first_primary on public.listing_images;
create trigger trg_listing_images_assign_first_primary
after insert on public.listing_images
for each row execute function public.assign_first_primary_image();

drop trigger if exists trg_listing_attributes_updated_at on public.listing_attributes;
create trigger trg_listing_attributes_updated_at
before update on public.listing_attributes
for each row execute function public.set_updated_at();

drop trigger if exists trg_saved_searches_updated_at on public.saved_searches;
create trigger trg_saved_searches_updated_at
before update on public.saved_searches
for each row execute function public.set_updated_at();

drop trigger if exists trg_reports_updated_at on public.reports;
create trigger trg_reports_updated_at
before update on public.reports
for each row execute function public.set_updated_at();

drop trigger if exists trg_listing_notes_updated_at on public.listing_notes;
create trigger trg_listing_notes_updated_at
before update on public.listing_notes
for each row execute function public.set_updated_at();

drop trigger if exists trg_listing_views_increment on public.listing_views;
create trigger trg_listing_views_increment
after insert on public.listing_views
for each row execute function public.increment_listing_view_count();

drop trigger if exists trg_favorites_adjust_count_ins on public.favorites;
create trigger trg_favorites_adjust_count_ins
after insert on public.favorites
for each row execute function public.adjust_favorite_count();

drop trigger if exists trg_favorites_adjust_count_del on public.favorites;
create trigger trg_favorites_adjust_count_del
after delete on public.favorites
for each row execute function public.adjust_favorite_count();

drop trigger if exists trg_messages_adjust_count_ins on public.messages;
create trigger trg_messages_adjust_count_ins
after insert on public.messages
for each row execute function public.adjust_message_count();

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- =========================================================
-- 5) RLS + Policies
-- =========================================================

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.category_nodes enable row level security;
alter table public.category_fields enable row level security;
alter table public.listings enable row level security;
alter table public.listing_attributes enable row level security;
alter table public.listing_images enable row level security;
alter table public.favorites enable row level security;
alter table public.saved_searches enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
alter table public.listing_views enable row level security;
alter table public.listing_price_history enable row level security;
alter table public.listing_notes enable row level security;
alter table public.listing_promotions enable row level security;
alter table public.notifications enable row level security;

drop policy if exists profiles_select_own_or_admin on public.profiles;
create policy profiles_select_own_or_admin
on public.profiles
for select
using (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists profiles_insert_own on public.profiles;
create policy profiles_insert_own
on public.profiles
for insert
with check (auth.uid() = id);

drop policy if exists profiles_update_own_or_admin on public.profiles;
create policy profiles_update_own_or_admin
on public.profiles
for update
using (auth.uid() = id or public.is_admin(auth.uid()))
with check (auth.uid() = id or public.is_admin(auth.uid()));

drop policy if exists categories_public_select_active on public.categories;
create policy categories_public_select_active
on public.categories
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists categories_admin_manage on public.categories;
create policy categories_admin_manage
on public.categories
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists category_nodes_public_select_active on public.category_nodes;
create policy category_nodes_public_select_active
on public.category_nodes
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists category_nodes_admin_manage on public.category_nodes;
create policy category_nodes_admin_manage
on public.category_nodes
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists category_fields_public_select_active on public.category_fields;
create policy category_fields_public_select_active
on public.category_fields
for select
using (is_active = true or public.is_admin(auth.uid()));

drop policy if exists category_fields_admin_manage on public.category_fields;
create policy category_fields_admin_manage
on public.category_fields
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists listings_select_public_or_owner_or_admin on public.listings;
create policy listings_select_public_or_owner_or_admin
on public.listings
for select
using (
  status = 'approved'
  or user_id = auth.uid()
  or public.is_admin(auth.uid())
);

drop policy if exists listings_insert_owner_only on public.listings;
create policy listings_insert_owner_only
on public.listings
for insert
to authenticated
with check (
  user_id = auth.uid()
  and status = 'pending'
  and approved_by is null
  and approved_at is null
);

drop policy if exists listings_update_owner_or_admin on public.listings;
create policy listings_update_owner_or_admin
on public.listings
for update
using (user_id = auth.uid() or public.is_admin(auth.uid()))
with check (
  public.is_admin(auth.uid())
  or (
    user_id = auth.uid()
    and status in ('pending', 'rejected', 'sold', 'expired')
  )
);

drop policy if exists listings_delete_owner_or_admin on public.listings;
create policy listings_delete_owner_or_admin
on public.listings
for delete
using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists listing_attributes_select_visible on public.listing_attributes;
create policy listing_attributes_select_visible
on public.listing_attributes
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.status = 'approved' or l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_attributes_owner_or_admin_write on public.listing_attributes;
create policy listing_attributes_owner_or_admin_write
on public.listing_attributes
for all
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_attributes.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_images_select_visible on public.listing_images;
create policy listing_images_select_visible
on public.listing_images
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.status = 'approved' or l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_images_owner_or_admin_write on public.listing_images;
create policy listing_images_owner_or_admin_write
on public.listing_images
for all
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
)
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_images.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists favorites_select_own on public.favorites;
create policy favorites_select_own
on public.favorites
for select
using (user_id = auth.uid());

drop policy if exists favorites_insert_own on public.favorites;
create policy favorites_insert_own
on public.favorites
for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists favorites_delete_own_or_admin on public.favorites;
create policy favorites_delete_own_or_admin
on public.favorites
for delete
using (user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists saved_searches_owner_only on public.saved_searches;
create policy saved_searches_owner_only
on public.saved_searches
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists messages_select_sender_or_recipient on public.messages;
create policy messages_select_sender_or_recipient
on public.messages
for select
using (sender_user_id = auth.uid() or recipient_user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists messages_insert_sender_only on public.messages;
create policy messages_insert_sender_only
on public.messages
for insert
to authenticated
with check (sender_user_id = auth.uid());

drop policy if exists messages_update_recipient_or_admin on public.messages;
create policy messages_update_recipient_or_admin
on public.messages
for update
using (recipient_user_id = auth.uid() or public.is_admin(auth.uid()))
with check (recipient_user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists reports_insert_reporter_only on public.reports;
create policy reports_insert_reporter_only
on public.reports
for insert
to authenticated
with check (reporter_user_id = auth.uid());

drop policy if exists reports_select_own_or_admin on public.reports;
create policy reports_select_own_or_admin
on public.reports
for select
using (reporter_user_id = auth.uid() or public.is_admin(auth.uid()));

drop policy if exists reports_admin_manage on public.reports;
create policy reports_admin_manage
on public.reports
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists listing_views_insert_anyone on public.listing_views;
create policy listing_views_insert_anyone
on public.listing_views
for insert
with check (true);

drop policy if exists listing_views_select_owner_or_admin on public.listing_views;
create policy listing_views_select_owner_or_admin
on public.listing_views
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_views.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_price_history_select_owner_or_admin on public.listing_price_history;
create policy listing_price_history_select_owner_or_admin
on public.listing_price_history
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_price_history.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_price_history_insert_owner_or_admin on public.listing_price_history;
create policy listing_price_history_insert_owner_or_admin
on public.listing_price_history
for insert
to authenticated
with check (
  exists (
    select 1
    from public.listings l
    where l.id = listing_price_history.listing_id
      and (l.user_id = auth.uid() or public.is_admin(auth.uid()))
  )
);

drop policy if exists listing_notes_owner_only on public.listing_notes;
create policy listing_notes_owner_only
on public.listing_notes
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists listing_promotions_select_owner_or_admin_or_public on public.listing_promotions;
create policy listing_promotions_select_owner_or_admin_or_public
on public.listing_promotions
for select
using (
  exists (
    select 1
    from public.listings l
    where l.id = listing_promotions.listing_id
      and (
        l.status = 'approved'
        or l.user_id = auth.uid()
        or public.is_admin(auth.uid())
      )
  )
);

drop policy if exists listing_promotions_admin_manage on public.listing_promotions;
create policy listing_promotions_admin_manage
on public.listing_promotions
for all
using (public.is_admin(auth.uid()))
with check (public.is_admin(auth.uid()));

drop policy if exists notifications_owner_only on public.notifications;
create policy notifications_owner_only
on public.notifications
for all
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- =========================================================
-- 6) Storage Bucket + Storage Policies
-- =========================================================

insert into storage.buckets (id, name, public)
values ('listing-images', 'listing-images', true)
on conflict (id) do nothing;

drop policy if exists listing_images_public_read_storage on storage.objects;
create policy listing_images_public_read_storage
on storage.objects
for select
using (bucket_id = 'listing-images');

drop policy if exists listing_images_upload_owner_or_admin on storage.objects;
create policy listing_images_upload_owner_or_admin
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
);

drop policy if exists listing_images_update_owner_or_admin on storage.objects;
create policy listing_images_update_owner_or_admin
on storage.objects
for update
to authenticated
using (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
)
with check (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
);

drop policy if exists listing_images_delete_owner_or_admin on storage.objects;
create policy listing_images_delete_owner_or_admin
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'listing-images'
  and (
    (storage.foldername(name))[1] = auth.uid()::text
    or public.is_admin(auth.uid())
  )
);

-- =========================================================
-- 7) Seed Data (Afghanistan Categories + Multi-level Nodes)
-- =========================================================

insert into public.categories (name, slug, description, display_order, is_active)
values
  ('Real Estate', 'real-estate', 'Homes, apartments, land, and commercial properties.', 1, true),
  ('Vehicles', 'vehicles', 'Cars, motorcycles, and transport listings.', 2, true),
  ('Phones & Electronics', 'phones-electronics', 'Phones, laptops, and consumer electronics.', 3, true),
  ('Second-Hand Items', 'second-hand-items', 'Used household and personal goods.', 4, true)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  display_order = excluded.display_order,
  is_active = excluded.is_active,
  updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select c.id, null, c.name, c.slug, 1, c.slug, c.display_order, true
from public.categories c
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, true
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('House for Sale', 'house-for-sale', 1),
    ('House for Rent', 'house-for-rent', 2),
    ('Apartment for Sale', 'apartment-for-sale', 3),
    ('Apartment for Rent', 'apartment-for-rent', 4),
    ('Land', 'land', 5),
    ('Commercial', 'commercial', 6)
) as v(name, slug, display_order)
where c.slug = 'real-estate'
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, true
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('Cars', 'cars', 1),
    ('Motorcycles', 'motorcycles', 2),
    ('Trucks', 'trucks', 3),
    ('Spare Parts', 'spare-parts', 4)
) as v(name, slug, display_order)
where c.slug = 'vehicles'
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, true
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('Mobile Phones', 'mobile-phones', 1),
    ('Laptops', 'laptops', 2),
    ('Tablets', 'tablets', 3),
    ('Accessories', 'accessories', 4)
) as v(name, slug, display_order)
where c.slug = 'phones-electronics'
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_nodes (category_id, parent_id, name, slug, level, path, display_order, is_active)
select c.id, p.id, v.name, v.slug, 2, p.path || '/' || v.slug, v.display_order, true
from public.categories c
join public.category_nodes p on p.category_id = c.id and p.parent_id is null
cross join (
  values
    ('Furniture', 'furniture', 1),
    ('Home Appliances', 'home-appliances', 2),
    ('Clothing', 'clothing', 3),
    ('Other', 'other', 4)
) as v(name, slug, display_order)
where c.slug = 'second-hand-items'
on conflict (path) do update
set
  name = excluded.name,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_fields (category_node_id, field_key, field_label, field_type, is_required, display_order, is_active)
select n.id, f.field_key, f.field_label, f.field_type, f.is_required, f.display_order, true
from public.category_nodes n
join public.categories c on c.id = n.category_id
cross join (
  values
    ('property_type', 'Property Type', 'text', true, 1),
    ('sale_or_rent', 'Sale or Rent', 'select', true, 2),
    ('rooms', 'Rooms', 'number', true, 3),
    ('size_m2', 'Size (m2)', 'number', true, 4),
    ('floor', 'Floor', 'number', false, 5),
    ('total_floors', 'Total Floors', 'number', false, 6),
    ('furnished', 'Furnished', 'boolean', false, 7),
    ('heating', 'Heating', 'text', false, 8),
    ('building_age', 'Building Age', 'number', false, 9),
    ('bathroom_count', 'Bathroom Count', 'number', false, 10),
    ('balcony', 'Balcony', 'boolean', false, 11),
    ('parking', 'Parking', 'boolean', false, 12),
    ('ownership_status', 'Ownership Status', 'text', false, 13)
) as f(field_key, field_label, field_type, is_required, display_order)
where c.slug = 'real-estate' and n.level = 2
on conflict (category_node_id, field_key) do update
set
  field_label = excluded.field_label,
  field_type = excluded.field_type,
  is_required = excluded.is_required,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_fields (category_node_id, field_key, field_label, field_type, is_required, display_order, is_active)
select n.id, f.field_key, f.field_label, f.field_type, f.is_required, f.display_order, true
from public.category_nodes n
join public.categories c on c.id = n.category_id
cross join (
  values
    ('brand', 'Brand', 'text', true, 1),
    ('model', 'Model', 'text', true, 2),
    ('year', 'Year', 'number', true, 3),
    ('mileage', 'Mileage', 'number', false, 4),
    ('fuel_type', 'Fuel Type', 'select', false, 5),
    ('transmission', 'Transmission', 'select', false, 6),
    ('color', 'Color', 'text', false, 7),
    ('condition', 'Condition', 'select', true, 8),
    ('body_type', 'Body Type', 'text', false, 9),
    ('engine_size', 'Engine Size', 'text', false, 10),
    ('drive_type', 'Drive Type', 'text', false, 11),
    ('seller_type', 'Seller Type', 'select', false, 12)
) as f(field_key, field_label, field_type, is_required, display_order)
where c.slug = 'vehicles' and n.level = 2
on conflict (category_node_id, field_key) do update
set
  field_label = excluded.field_label,
  field_type = excluded.field_type,
  is_required = excluded.is_required,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_fields (category_node_id, field_key, field_label, field_type, is_required, display_order, is_active)
select n.id, f.field_key, f.field_label, f.field_type, f.is_required, f.display_order, true
from public.category_nodes n
join public.categories c on c.id = n.category_id
cross join (
  values
    ('brand', 'Brand', 'text', true, 1),
    ('model', 'Model', 'text', true, 2),
    ('condition', 'Condition', 'select', true, 3),
    ('storage', 'Storage', 'text', false, 4),
    ('ram', 'RAM', 'text', false, 5),
    ('warranty', 'Warranty', 'text', false, 6),
    ('color', 'Color', 'text', false, 7),
    ('device_type', 'Device Type', 'text', false, 8)
) as f(field_key, field_label, field_type, is_required, display_order)
where c.slug = 'phones-electronics' and n.level = 2
on conflict (category_node_id, field_key) do update
set
  field_label = excluded.field_label,
  field_type = excluded.field_type,
  is_required = excluded.is_required,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

insert into public.category_fields (category_node_id, field_key, field_label, field_type, is_required, display_order, is_active)
select n.id, f.field_key, f.field_label, f.field_type, f.is_required, f.display_order, true
from public.category_nodes n
join public.categories c on c.id = n.category_id
cross join (
  values
    ('item_type', 'Item Type', 'text', true, 1),
    ('brand', 'Brand', 'text', false, 2),
    ('condition', 'Condition', 'select', true, 3),
    ('material', 'Material', 'text', false, 4),
    ('usage_status', 'Usage Status', 'text', false, 5)
) as f(field_key, field_label, field_type, is_required, display_order)
where c.slug = 'second-hand-items' and n.level = 2
on conflict (category_node_id, field_key) do update
set
  field_label = excluded.field_label,
  field_type = excluded.field_type,
  is_required = excluded.is_required,
  display_order = excluded.display_order,
  is_active = true,
  updated_at = now();

commit;
