begin;

-- Admin RBAC tables and bootstrap data

create table if not exists public.admin_roles (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_permissions (
  id bigint generated by default as identity primary key,
  key text not null unique,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_role_permissions (
  role_id bigint not null references public.admin_roles(id) on delete cascade,
  permission_id bigint not null references public.admin_permissions(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (role_id, permission_id)
);

create table if not exists public.admin_user_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.admin_roles(id) on delete cascade,
  assigned_at timestamptz not null default now(),
  primary key (user_id, role_id)
);

create or replace function public.has_admin_permission(uid uuid, permission_key text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  )
  or exists (
    select 1
    from public.admin_user_roles ur
    join public.admin_role_permissions rp on rp.role_id = ur.role_id
    join public.admin_permissions perm on perm.id = rp.permission_id
    where ur.user_id = uid
      and perm.key = permission_key
  );
$$;

create or replace function public.is_admin(uid uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    where p.id = uid
      and p.role = 'admin'
  )
  or exists (
    select 1
    from public.admin_user_roles ur
    where ur.user_id = uid
  );
$$;

insert into public.admin_roles (name, description)
values
  ('super_administrator', 'Can manage all administrator and marketplace configuration.'),
  ('marketplace_administrator', 'Can manage listings, users, categories, promotions, and reports.'),
  ('content_administrator', 'Can manage homepage, static pages, navigation, translations, and media.'),
  ('moderator', 'Can review listings, reports, and moderation actions.'),
  ('support_agent', 'Can assist with support-related workflows.')
on conflict (name) do nothing;

insert into public.admin_permissions (key, description)
values
  ('categories.view', 'View categories and category configuration'),
  ('categories.create', 'Create categories and subcategories'),
  ('categories.update', 'Update category metadata and hierarchy'),
  ('categories.archive', 'Archive or deactivate categories'),
  ('categories.publish', 'Publish category changes'),
  ('listing_fields.view', 'View listing field definitions'),
  ('listing_fields.create', 'Create new listing fields'),
  ('listing_fields.update', 'Update existing listing fields'),
  ('listing_fields.archive', 'Archive listing fields'),
  ('listing_fields.publish', 'Publish listing field changes'),
  ('pages.view', 'View page and homepage section configuration'),
  ('pages.create', 'Create static pages and homepage sections'),
  ('pages.update', 'Update page and homepage section content'),
  ('pages.publish', 'Publish page and homepage section changes'),
  ('listings.view', 'View marketplace listings and moderation queues'),
  ('listings.moderate', 'Approve, reject, or suspend listings'),
  ('listings.edit', 'Edit listing details on behalf of users'),
  ('listings.feature', 'Manage featured listing placements'),
  ('listings.suspend', 'Suspend prohibited or problematic listings'),
  ('users.view', 'View user profiles and account data'),
  ('users.update', 'Update user profiles and verify users'),
  ('users.suspend', 'Suspend or reinstate user accounts'),
  ('users.verify', 'Verify user identities and contact information'),
  ('translations.view', 'View translation entries'),
  ('translations.update', 'Update translation entries'),
  ('translations.publish', 'Publish translation changes'),
  ('search.view', 'View search system configuration and analytics'),
  ('search.manage', 'Manage search alias rules and telemetry'),
  ('electronics.view', 'View electronics inventory and marketplace configuration'),
  ('electronics.manage', 'Manage electronics brands, models, specs, and options'),
  ('admins.view', 'View administrator accounts and activity'),
  ('admins.create', 'Create new administrator accounts'),
  ('admins.update', 'Update administrator accounts'),
  ('admins.disable', 'Disable administrator access'),
  ('roles.view', 'View role definitions and permissions'),
  ('roles.manage', 'Manage role assignments and permission mappings'),
  ('settings.view', 'View site settings'),
  ('settings.update', 'Update site settings'),
  ('settings.publish', 'Publish site settings changes'),
  ('audit_logs.view', 'View audit log entries'),
  ('configuration.rollback', 'Restore previous configuration versions')
on conflict (key) do nothing;

insert into public.admin_role_permissions (role_id, permission_id)
select super_role.id, perm.id
from public.admin_roles super_role,
     public.admin_permissions perm
where super_role.name = 'super_administrator'
on conflict do nothing;

insert into public.admin_role_permissions (role_id, permission_id)
select role.id, perm.id
from public.admin_roles role,
     public.admin_permissions perm
where role.name = 'marketplace_administrator'
  and perm.key in (
    'categories.view', 'categories.create', 'categories.update', 'categories.archive',
    'listing_fields.view', 'listing_fields.create', 'listing_fields.update', 'listing_fields.archive',
    'listings.view', 'listings.moderate', 'listings.edit', 'listings.feature', 'listings.suspend',
    'users.view', 'users.update', 'users.suspend', 'users.verify',
    'audit_logs.view'
  )
on conflict do nothing;

insert into public.admin_role_permissions (role_id, permission_id)
select role.id, perm.id
from public.admin_roles role,
     public.admin_permissions perm
where role.name = 'content_administrator'
  and perm.key in (
    'pages.view', 'pages.create', 'pages.update', 'pages.publish',
    'translations.view', 'translations.update', 'translations.publish',
    'audit_logs.view'
  )
on conflict do nothing;

insert into public.admin_role_permissions (role_id, permission_id)
select role.id, perm.id
from public.admin_roles role,
     public.admin_permissions perm
where role.name = 'moderator'
  and perm.key in (
    'listings.view', 'listings.moderate', 'listings.edit', 'listings.suspend'
  )
on conflict do nothing;

insert into public.admin_role_permissions (role_id, permission_id)
select role.id, perm.id
from public.admin_roles role,
     public.admin_permissions perm
where role.name = 'support_agent'
  and perm.key in (
    'users.view', 'listings.view'
  )
on conflict do nothing;

do $$
begin
  if not exists (
    select 1
    from pg_type
    where typname = 'audit_action_type'
  ) then
    create type public.audit_action_type as enum (
      'CATEGORY_CREATED',
      'CATEGORY_UPDATED',
      'CATEGORY_ARCHIVED',
      'CATEGORY_PUBLISHED',
      'LISTING_FIELD_CREATED',
      'LISTING_FIELD_RETIRED',
      'PAGE_PUBLISHED',
      'CONFIGURATION_ROLLED_BACK',
      'ADMIN_CREATED',
      'ROLE_UPDATED',
      'MFA_DISABLED',
      'LISTING_APPROVED',
      'LISTING_REJECTED',
      'SETTING_CHANGED'
    );
  end if;
end
$$;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete cascade,
  action public.audit_action_type not null,
  entity_type text not null,
  entity_id text,
  safe_changes jsonb,
  ip_address inet,
  created_at timestamptz not null default now()
);

commit;
