-- Smart search and dynamic category-aware filters

begin;

create extension if not exists pg_trgm;

create table if not exists public.filter_definitions (
  id bigint generated by default as identity primary key,
  category_node_id bigint references public.category_nodes(id) on delete cascade,
  filter_key text not null,
  filter_label text not null,
  filter_type text not null check (filter_type in ('select','multi_select','range','boolean','text','date','location','distance')),
  options jsonb,
  source_table text,
  source_column text,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint filter_definitions_unique_key_per_node unique (category_node_id, filter_key)
);

create index if not exists idx_filter_definitions_category on public.filter_definitions(category_node_id, is_active, sort_order);
create index if not exists idx_filter_definitions_key on public.filter_definitions(filter_key);

alter table public.filter_definitions enable row level security;

drop policy if exists filter_definitions_public_read on public.filter_definitions;
create policy filter_definitions_public_read on public.filter_definitions
  for select using (is_active = true);

drop policy if exists filter_definitions_admin_write on public.filter_definitions;
create policy filter_definitions_admin_write on public.filter_definitions
  for all using (
    exists (
      select 1 from public.profiles p
      where p.id = auth.uid() and p.role = 'admin'
    )
  );

-- Search performance indexes
create index if not exists idx_listings_title on public.listings(title);
create index if not exists idx_listings_description on public.listings(description);
create index if not exists idx_listings_category_node on public.listings(category_node_id);
create index if not exists idx_listings_price on public.listings(price);
create index if not exists idx_listings_province on public.listings(province);
create index if not exists idx_listings_district on public.listings(district);
create index if not exists idx_listings_created_at on public.listings(created_at);
create index if not exists idx_listings_status on public.listings(status);
create index if not exists idx_listings_tsv on public.listings using gin (
  to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))
);

create index if not exists idx_listing_attributes_key_text on public.listing_attributes(attribute_key, attribute_value_text);
create index if not exists idx_listing_attributes_key_num on public.listing_attributes(attribute_key, attribute_value_number);
create index if not exists idx_listing_attributes_key_bool on public.listing_attributes(attribute_key, attribute_value_boolean);

-- Global/common filters
insert into public.filter_definitions (
  category_node_id, filter_key, filter_label, filter_type, options, source_table, source_column, sort_order, is_active
)
values
  (null, 'province', 'Province', 'select', null, 'listings', 'province', 5, true),
  (null, 'district', 'District', 'text', null, 'listings', 'district', 6, true),
  (null, 'min_price', 'Price Min', 'range', null, 'listings', 'price', 10, true),
  (null, 'max_price', 'Price Max', 'range', null, 'listings', 'price', 11, true)
on conflict (category_node_id, filter_key) do update
set filter_label = excluded.filter_label,
    filter_type = excluded.filter_type,
    options = excluded.options,
    source_table = excluded.source_table,
    source_column = excluded.source_column,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

-- Vehicles broad filters
with vehicles_node as (
  select id from public.category_nodes where path = 'vehicles' limit 1
)
insert into public.filter_definitions (
  category_node_id, filter_key, filter_label, filter_type, options, source_table, source_column, sort_order, is_active
)
select (select id from vehicles_node), x.filter_key, x.filter_label, x.filter_type, x.options::jsonb, x.source_table, x.source_column, x.sort_order, true
from (
  values
    ('vehicle_type', 'Vehicle Type', 'select', '["passenger_vehicles","motorcycles","rickshaw_three_wheelers","bicycles","commercial_vehicles","agricultural_rural_vehicles","other_custom"]', 'listings', 'vehicle_type', 20),
    ('vehicle_brand', 'Brand', 'text', null, 'listings', 'vehicle_brand', 21),
    ('vehicle_model', 'Model', 'text', null, 'listings', 'vehicle_model', 22),
    ('year_min', 'Year Min', 'range', null, 'listings', 'vehicle_year', 23),
    ('year_max', 'Year Max', 'range', null, 'listings', 'vehicle_year', 24),
    ('km_min', 'KM Min', 'range', null, 'listing_attributes', 'mileage', 25),
    ('km_max', 'KM Max', 'range', null, 'listing_attributes', 'mileage', 26),
    ('fuel_type', 'Fuel Type', 'select', '["Petrol","Diesel","Hybrid","Electric","CNG"]', 'listing_attributes', 'locked__fuel_type', 27),
    ('transmission', 'Transmission', 'select', '["Automatic","Manual"]', 'listing_attributes', 'locked__gear', 28),
    ('color', 'Color', 'text', null, 'listing_attributes', 'color', 29),
    ('seller_type', 'Seller Type', 'select', '["owner","dealer"]', 'listing_attributes', 'seller_type', 30),
    ('warranty', 'Warranty', 'select', '["Yes","No"]', 'listing_attributes', 'warranty', 31),
    ('exchange', 'Exchange', 'boolean', null, 'listing_attributes', 'exchange_available', 32),
    ('plate_status', 'Plate Status', 'text', null, 'listing_attributes', 'plate_status', 33),
    ('condition', 'Condition', 'select', '["New","Like New","Used","Damaged"]', 'listing_attributes', 'condition', 34),
    ('accident_status', 'Accident/Salvage', 'select', '["No Accident","Minor Accident","Major Accident"]', 'listing_attributes', 'accident_status', 35),
    ('old_vehicle', 'Old Vehicle', 'boolean', null, 'listings', 'vehicle_is_classic', 36),
    ('imported_vehicle', 'Imported Vehicle', 'boolean', null, 'listings', 'vehicle_manual_specs.imported', 37)
) as x(filter_key, filter_label, filter_type, options, source_table, source_column, sort_order)
where (select id from vehicles_node) is not null
on conflict (category_node_id, filter_key) do update
set filter_label = excluded.filter_label,
    filter_type = excluded.filter_type,
    options = excluded.options,
    source_table = excluded.source_table,
    source_column = excluded.source_column,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

-- Motorcycles (Honda 70 specific)
with motorcycles_node as (
  select id from public.category_nodes where path = 'vehicles/motorcycles' limit 1
)
insert into public.filter_definitions (
  category_node_id, filter_key, filter_label, filter_type, options, source_table, source_column, sort_order, is_active
)
select (select id from motorcycles_node), x.filter_key, x.filter_label, x.filter_type, x.options::jsonb, x.source_table, x.source_column, x.sort_order, true
from (
  values
    ('honda_70', 'Honda 70', 'boolean', null, 'listings', 'vehicle_subtype', 40),
    ('engine_cc', 'Engine CC', 'text', null, 'listings', 'vehicle_manual_specs.engine_cc', 41)
) as x(filter_key, filter_label, filter_type, options, source_table, source_column, sort_order)
where (select id from motorcycles_node) is not null
on conflict (category_node_id, filter_key) do update
set filter_label = excluded.filter_label,
    filter_type = excluded.filter_type,
    options = excluded.options,
    source_table = excluded.source_table,
    source_column = excluded.source_column,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

-- Rickshaw filters
with rickshaw_node as (
  select id from public.category_nodes where path = 'vehicles/rickshaw-three-wheelers' limit 1
)
insert into public.filter_definitions (
  category_node_id, filter_key, filter_label, filter_type, options, source_table, source_column, sort_order, is_active
)
select (select id from rickshaw_node), x.filter_key, x.filter_label, x.filter_type, x.options::jsonb, x.source_table, x.source_column, x.sort_order, true
from (
  values
    ('rickshaw_type', 'Rickshaw Type', 'select', '["auto-rickshaw","cargo-rickshaw","passenger-rickshaw","electric-rickshaw","modified-three-wheeler"]', 'listings', 'vehicle_subtype', 50),
    ('passenger_capacity', 'Passenger Capacity', 'text', null, 'listings', 'vehicle_manual_specs.passenger_capacity', 51),
    ('cargo_capacity', 'Cargo Capacity', 'text', null, 'listings', 'vehicle_manual_specs.cargo_capacity', 52)
) as x(filter_key, filter_label, filter_type, options, source_table, source_column, sort_order)
where (select id from rickshaw_node) is not null
on conflict (category_node_id, filter_key) do update
set filter_label = excluded.filter_label,
    filter_type = excluded.filter_type,
    options = excluded.options,
    source_table = excluded.source_table,
    source_column = excluded.source_column,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

-- Phones filters
with phones_node as (
  select id from public.category_nodes where path = 'phones-electronics' limit 1
)
insert into public.filter_definitions (
  category_node_id, filter_key, filter_label, filter_type, options, source_table, source_column, sort_order, is_active
)
select (select id from phones_node), x.filter_key, x.filter_label, x.filter_type, x.options::jsonb, x.source_table, x.source_column, x.sort_order, true
from (
  values
    ('phone_model', 'Model', 'text', null, 'listing_attributes', 'model', 60),
    ('storage', 'Storage', 'select', '["32GB","64GB","128GB","256GB","512GB","1TB"]', 'listing_attributes', 'storage', 61),
    ('ram', 'RAM', 'select', '["2GB","3GB","4GB","6GB","8GB","12GB","16GB"]', 'listing_attributes', 'ram', 62),
    ('battery_health_min', 'Battery Health Min', 'range', null, 'listing_attributes', 'battery_health', 63)
) as x(filter_key, filter_label, filter_type, options, source_table, source_column, sort_order)
where (select id from phones_node) is not null
on conflict (category_node_id, filter_key) do update
set filter_label = excluded.filter_label,
    filter_type = excluded.filter_type,
    options = excluded.options,
    source_table = excluded.source_table,
    source_column = excluded.source_column,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

-- Real estate filters
with real_estate_node as (
  select id from public.category_nodes where path = 'real-estate' limit 1
)
insert into public.filter_definitions (
  category_node_id, filter_key, filter_label, filter_type, options, source_table, source_column, sort_order, is_active
)
select (select id from real_estate_node), x.filter_key, x.filter_label, x.filter_type, x.options::jsonb, x.source_table, x.source_column, x.sort_order, true
from (
  values
    ('property_type', 'Property Type', 'text', null, 'listing_attributes', 'property_type', 70),
    ('rental_type', 'For Sale / Rent / Gerawy', 'select', '["For Sale","Monthly Rent","Yearly Rent","Gerawy / Rahn","Gerawy + Monthly Rent","Dormitory","Land Lease"]', 'listing_attributes', 'rental_type', 71),
    ('rooms_min', 'Rooms Min', 'range', null, 'listing_attributes', 'rooms', 72),
    ('bathrooms_min', 'Bathrooms Min', 'range', null, 'listing_attributes', 'bathrooms', 73),
    ('property_size_min', 'Property Size Min', 'range', null, 'listing_attributes', 'property_size', 74),
    ('furnished', 'Furnished', 'boolean', null, 'listing_attributes', 'furnished', 75),
    ('owner_agent', 'Owner/Agent', 'select', '["owner","agent","manager","developer"]', 'listing_attributes', 'owner_type', 76)
) as x(filter_key, filter_label, filter_type, options, source_table, source_column, sort_order)
where (select id from real_estate_node) is not null
on conflict (category_node_id, filter_key) do update
set filter_label = excluded.filter_label,
    filter_type = excluded.filter_type,
    options = excluded.options,
    source_table = excluded.source_table,
    source_column = excluded.source_column,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = now();

commit;
