-- Sahibash Vehicle Smart Posting: brands / models / generations / variants / specs / damage

begin;

create table if not exists public.vehicle_brands (
  id bigint generated by default as identity primary key,
  category_node_id bigint references public.category_nodes(id) on delete set null,
  name text not null,
  slug text not null,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_brands_slug_unique unique (slug)
);

create table if not exists public.vehicle_models (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.vehicle_brands(id) on delete cascade,
  name text not null,
  slug text not null,
  body_type text,
  doors int,
  seats int,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_models_brand_slug_unique unique (brand_id, slug)
);

create table if not exists public.vehicle_generations (
  id bigint generated by default as identity primary key,
  model_id bigint not null references public.vehicle_models(id) on delete cascade,
  name text not null,
  slug text not null,
  year_start int,
  year_end int,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_generations_model_slug_unique unique (model_id, slug)
);

create table if not exists public.vehicle_variants (
  id bigint generated by default as identity primary key,
  generation_id bigint not null references public.vehicle_generations(id) on delete cascade,
  name text not null,
  slug text not null,
  fuel_type text,
  transmission text,
  engine_size text,
  drive_type text,
  display_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_variants_gen_slug_unique unique (generation_id, slug)
);

create table if not exists public.vehicle_specifications (
  id bigint generated by default as identity primary key,
  variant_id bigint not null references public.vehicle_variants(id) on delete cascade,
  spec_key text not null,
  spec_label text not null,
  spec_value text not null,
  is_locked boolean not null default true,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_specifications_variant_key_unique unique (variant_id, spec_key)
);

create table if not exists public.vehicle_damage_reports (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.listings(id) on delete cascade,
  all_original boolean not null default false,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint vehicle_damage_reports_listing_unique unique (listing_id)
);

create table if not exists public.vehicle_damage_parts (
  id bigint generated by default as identity primary key,
  damage_report_id bigint not null references public.vehicle_damage_reports(id) on delete cascade,
  part_key text not null,
  part_label text not null,
  condition text not null default 'original',
  created_at timestamptz not null default now(),
  constraint vehicle_damage_parts_report_part_unique unique (damage_report_id, part_key)
);

alter table public.listings
  add column if not exists vehicle_variant_id bigint references public.vehicle_variants(id) on delete set null;

create index if not exists idx_vehicle_models_brand on public.vehicle_models(brand_id, is_active, display_order);
create index if not exists idx_vehicle_generations_model on public.vehicle_generations(model_id, is_active, display_order);
create index if not exists idx_vehicle_variants_gen on public.vehicle_variants(generation_id, is_active, display_order);
create index if not exists idx_vehicle_specifications_variant on public.vehicle_specifications(variant_id, sort_order);
create index if not exists idx_vehicle_damage_reports_listing on public.vehicle_damage_reports(listing_id);
create index if not exists idx_listings_vehicle_variant on public.listings(vehicle_variant_id);

alter table public.vehicle_brands enable row level security;
alter table public.vehicle_models enable row level security;
alter table public.vehicle_generations enable row level security;
alter table public.vehicle_variants enable row level security;
alter table public.vehicle_specifications enable row level security;
alter table public.vehicle_damage_reports enable row level security;
alter table public.vehicle_damage_parts enable row level security;

create policy vehicle_brands_public_read on public.vehicle_brands for select using (is_active = true);
create policy vehicle_models_public_read on public.vehicle_models for select using (is_active = true);
create policy vehicle_generations_public_read on public.vehicle_generations for select using (is_active = true);
create policy vehicle_variants_public_read on public.vehicle_variants for select using (is_active = true);
create policy vehicle_specifications_public_read on public.vehicle_specifications for select using (true);
create policy vehicle_damage_reports_owner_read on public.vehicle_damage_reports
  for select using (
    exists (select 1 from public.listings l where l.id = listing_id and (l.status = 'approved' or l.user_id = auth.uid()))
  );
create policy vehicle_damage_parts_owner_read on public.vehicle_damage_parts
  for select using (
    exists (
      select 1 from public.vehicle_damage_reports r
      join public.listings l on l.id = r.listing_id
      where r.id = damage_report_id and (l.status = 'approved' or l.user_id = auth.uid())
    )
  );
create policy vehicle_damage_reports_owner_write on public.vehicle_damage_reports
  for all using (
    exists (select 1 from public.listings l where l.id = listing_id and l.user_id = auth.uid())
  );
create policy vehicle_damage_parts_owner_write on public.vehicle_damage_parts
  for all using (
    exists (
      select 1 from public.vehicle_damage_reports r
      join public.listings l on l.id = r.listing_id
      where r.id = damage_report_id and l.user_id = auth.uid()
    )
  );

commit;
